### ISSUE TITLE
Bug: Type guards on Type can lead to never type

### ISSUE THREAD

**Issue by lilezek** [dsherret/ts-simple-ast#113]
This simple code does not compile:

```ts
    if (type.isAnonymousType()) {
    
    } else if (type.isArrayType()) {
     
    } else if (type.isEnumType()) {
     
    } else if (type.isBooleanType()) { // Line 77
      
    }
```

> message: 'Property 'isBooleanType' does not exist on type 'never'.'
> at: '77,21'

And I think it is because of a bug in the TypeScript compiler:

https://stackoverflow.com/questions/47111236/generic-type-guards-assuming-never

**Comment by dsherret** [comment]
That is interesting! Thanks for reporting it. I've changed these to all be straight booleans and in the future will (1) wrap the different kinds of compiler types and (2) add back the type guards. This is fixed in 0.81.1 (just packaging for release... will be released in a few mins).

**Comment by ezequiel-umu** [comment]
Wait! @dsherret, you can actually have a better fix.

Just add a dummy field `__dummy: T` in the class where T is the Type of the node. Check the answer of the StackOverflow question.

**Comment by dsherret** [comment]
That's strange, because it already uses the type parameter type on the `compilerType` property. Maybe there's something else going on here

Anyway, when working on #114, I found out that these type guards were only added for internal reasons and aren't really that useful outside the library. I scraped #114 since everything is already available on `Type`. So this is no big deal to remove.

**Comment by dsherret** [comment]
Oh, it probably didn't work in this scenario because `ts.EnumType` extends `ts.Type`.

**Comment by ezequiel-umu** [comment]
I think type guards are useful. They just need to be implemented carefully. By the way, can I invite you to slack? We could discuss these issues faster.

**Comment by dsherret** [comment]
@ezequiel-umu I'm sporadically at my computer today. In general I agree that type guards are very useful, but for this case, can you give one scenario where the type guards that were previously here are useful? All the functionality I can see is available on `Type`.
