### ISSUE TITLE
How does `require` work when using Deno?

### ISSUE THREAD

**Issue by vedantroy** [dsherret/ts-simple-ast#1154]
This is not a bug with tsmorph (I think?), rather I'm trying to understand how to fix [this bug](https://github.com/dalcib/esbuild-plugin-cache/issues/2) in a esbuild plugin/this is a curiosity question.

It looks like the compiled output of tsmorph has `require` statements, but Deno doesn't support require, so how is tsmorph running in `Deno`?

**Comment by dsherret** [comment]
Those require statements are in the TS compiler source within typescript.js (https://raw.githubusercontent.com/dsherret/ts-morph/latest/deno/common/typescript.js). The reason it works is because those expressions won't ever (should never) be executed.

**Comment by dalcib** [comment]
See https://github.com/dalcib/esbuild-plugin-cache/issues/2#issuecomment-830865398
