### ISSUE TITLE
fixUnusedIdentifiers() remove all expressions when they are all in a single line

### ISSUE THREAD

**Issue by mingzepeng** [dsherret/ts-simple-ast#1162]
**Describe the bug**

Version: 11.0.0

when I use fixUnusedIdentifiers api to remove UnusedIdentifiers,while the `export const a = 1` and the unused `const c = 2` are in the same line,the  `export const a = 1` will be removed too; if they are in different lines, `export const a = 1` will not be removed; 

**To Reproduce**

```ts
import { Project } from "ts-morph";

const project = new Project();
const sourceFile = project.createSourceFile("test.ts", `export const a = 1;const c = 2`);
sourceFile .fixUnusedIdentifiers()
console.log(sourceFile .getFullText())
// reproduce the problem here
```

**Expected behavior**

when  export statement and the UnusedIdentifiers are in the same line, export statement should not be removed

**Comment by dsherret** [comment]
I opened https://github.com/microsoft/TypeScript/issues/44465

Please follow that issue for updates. Seems like it started happening in TS 3.9.
