### ISSUE TITLE
Calling `getSymbol` of type makes the file to be forgotten

### ISSUE THREAD

**Issue by roymiloh** [dsherret/ts-simple-ast#1164]
When I `.getSymbol` of some type, add some statements to the file right after, and eventually call `project.getSourceFiles()` - the file seems to be gone. No diagnostics appear.

Version: 11.0.0 (checked other versions, reproduced there as well).

**To Reproduce**

```ts
const { Project } = require('ts-morph');

const project = new Project();

const sourceFile = project.createSourceFile('index.ts', '');

const i = sourceFile.addInterface({ name: 'Foo' }).getType();

sourceFile.addInterface({ name: 'FooBar' }); // If I remove this line, the file will be present

i.getSymbol(); // This line is the problematic one - it makes {sourceFile} to be forgotten 

console.log(project.getSourceFiles().length); // => 0
```

**Expected behavior**

To have this file in source files array / project.

**Comment by dsherret** [comment]
It's not possible to reliably inspect symbols or types between manipulations. Only AST nodes are tracked.

You can keep around nodes between manipulations as long as they are not removed:

```ts
const i = sourceFile.addInterface({ name: 'Foo' });

sourceFile.addInterface({ name: 'FooBar' });

i.getType().getSymbol(); // should be ok
```

That said, it having `project.getSources().length === 0` at the end is definitely a bug and that's super strange.

**Comment by roymiloh** [comment]
Basically I only need the name of the symbol (should be reliable, I guess), so I thought it would be nice to have a `getName` function that accepts _any_ `Type` and simply returns its name, as `Type` is a pretty generic type I can rely on.

```ts
function getName(type: Type) {
  const maybeSymbol = type.getSymbol();

  return maybeSymbol ? maybeSymbol.getName() : type.getText();
}
```

So in order to make it work with interfaces, I need to do something like:

```ts
getName(interface.getType());
```

... and then it breaks everything right after `.getSymbol` call.

I guess I'll have to work it around for now. Thanks for a super quick answer!

_* Yes, I know I can call `interface.getName()` - but it's not what I'm looking for:)_
