### ISSUE TITLE
getPreEmitDiagnostics and formatDiagnosticsWithColorAndContext taking a lot of time

### ISSUE THREAD

**Issue by jrabello** [dsherret/ts-simple-ast#1167]
Hi, thanks for releasing your project, very helpful

Some of my code is taking too much time to compile and format errors, there is any way to debug why it's taking so much time? and then trying to optimize it?
execution1:
sourceFileDiagnostics: 1759.197ms
formatDiagnosticsWithColorAndContext: 3.058ms
execution2:
sourceFileDiagnostics: 966.310ms
formatDiagnosticsWithColorAndContext: 1.315ms

Here is the compilerOptions I'm using:
```
    private static compilerOptions: ts.CompilerOptions = {
        "noEmitOnError": true,
        "strictNullChecks": true,
        "strictFunctionTypes": true,
        "strictPropertyInitialization": true,
        "strictBindCallApply": true,
        "noImplicitThis": true,
        "noImplicitReturns": true,
        "alwaysStrict": true,
        "esModuleInterop": true,
        "declaration": false,
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "target": ts.ScriptTarget.ES2017,
        "module": ts.ModuleKind.ESNext,
        "moduleResolution": ts.ModuleResolutionKind.NodeJs,
    }
```

thanks!!!

**Comment by dsherret** [comment]
The `getPreEmitDiagnostics` code is almost exclusively typescript compiler API code. I believe it would be almost the same code path, though slightly slower in ts-morph than using `tsc` with `noEmit: true`. You may wish to look at this document: https://github.com/microsoft/TypeScript/wiki/Performance-Tracing
