### ISSUE TITLE
Creating an arrow function and assigning to an object property. 

### ISSUE THREAD

**Issue by eltiare** [dsherret/ts-simple-ast#1170]
I want to generate code like this:  

```
const obj = {
   func: (arg: number) => 3
}
```

I have the `ObjectLiteralExpression` already and need to add it. I'm guessing through `addProperty` or`addPropertyAssignment`, but I cannot figure out how to pass it an arrow function for the assignment, nor how to create the arrow function in the first place.

**Comment by dsherret** [comment]
There's are a few ways that this could be done. I would just do something along the lines of:

```ts
sourceFile.addStatements(writer => {
  writer.write("const obj = ").inlineBlock(() => {
    writer.write("func: (arg: number) => 3,");
  }).write(";");
});

// or something like (or some combination between the two)
sourceFile.addVariableStatement({
  declarationKind: VariableDeclarationKind.Const,
  declarations: [{
    name: "obj",
    initializer: Writers.object({
      "func": "(arg: number) => 3,",
    })
  }]
});
```

There isn't any way to add an array function expression right now because #683 is not implemented and there are no helper `Writer` functions for array function expressions (that might be better).
