### ISSUE TITLE
Better JSDoc support

### ISSUE THREAD

**Issue by dsherret** [dsherret/ts-simple-ast#118]
This is an issue just to remind myself to go through and improve the JSDoc support.

**Comment by dsherret** [comment]
I'm going to close this issue because it's obvious to see this now in the output-nodes.md report.

If someone would like me to escalate priority on this issue, then please comment on this issue.

**Comment by Jack-Works** [comment]
Hello, I want to transform the JSDoc nodes, how can I do that? It seems like there is no API for it in ts-morph and the raw typescript compiler

**Comment by dsherret** [comment]
@Jack-Works see #766. It's best to open new issues for questions as it's easy for me to forget about these comments.

**Comment by dsherret** [comment]
@Jack-Works in the upcoming version 6.0 there will be methods for inserting, removing, and changing js doc tags. Not sure when I'll release 6.0, but probably sometime next week.
