### ISSUE TITLE
Braces of classes are affected by `placeOpenBraceOnNewLineForFunctions`

### ISSUE THREAD

**Issue by neurolag** [dsherret/ts-simple-ast#1180]
**Describe the bug**
While I'd expect braces of classes to be affected by `placeOpenBraceOnNewLineForControlBlocks`, they are only affected by `placeOpenBraceOnNewLineForFunctions`.

Version: 11.0.3

**To Reproduce**

Format an empty class with `placeOpenBraceOnNewLineForFunctions`.

##### With `placeOpenBraceOnNewLineForControlBlocks` enabled
```ts
import { Project } from "ts-morph";

let sourceFile = new Project().createSourceFile("test.ts", null, { overwrite: true });

sourceFile.addClass(
    {
        name: "Test"
    });

sourceFile.formatText(
    {
        placeOpenBraceOnNewLineForControlBlocks: true
    });

console.log(sourceFile.getFullText());
```

***Output:***
```
class Test {
}
```

##### With `placeOpenBraceOnNewLineForFunctions` enabled
```ts
sourceFile.formatText(
    {
        placeOpenBraceOnNewLineForFunctions: true
    });

console.log(sourceFile.getFullText());
```

***Output:***
```
class Test
{
}
```

**Expected behavior**
I'd either expect a separate `FormatCodeSettings`-option for placing braces of classes on a new line or another name for `placeOpenBraceOnNewLineForFunctions` which points out the fact, that classes are affected, too.

Probably related to #1179

**Comment by dsherret** [comment]
See my answer here: https://github.com/dsherret/ts-morph/issues/1179#issuecomment-894823769

Going to close this as there's not much I can do. Recommend opening a bug on the TS repo if you really want this, but overall I'd recommend using dprint-plugin-typescript.
