### ISSUE TITLE
Non-string constraint type

### ISSUE THREAD

**Issue by sadiqhabib** [dsherret/ts-simple-ast#1181]
I have this code example
`let param: OptionalKind<TypeParameterDeclarationStructure> = { name: 'T', constraint: 'Array' }`
which is producing
`<T extends Array>`
But how can I create 
`<T extends Array<Number>>`
because constraint has only string and writerFunction and I don't want to use both.

**Comment by dsherret** [comment]
Sorry for my delay. Currently there are no expression structures, so you have to do something along the lines of:

```ts
{ name: 'T', constraint: 'Array<number>' }
```

**Comment by sadiqhabib** [comment]
So we can call it feature instead of only question. no ?

**Comment by dsherret** [comment]
That is tracked in #683. I don't think I will ever get to it as it is a lot of work.
