### ISSUE TITLE
Bootstrap: Update diagnostics after editing file without another createProgram()

### ISSUE THREAD

**Issue by phil294** [dsherret/ts-simple-ast#1182]
To generate diagnostics from a source string, you can do
```ts
project = await createProject({ useInMemoryFileSystem: true })
project.createSourceFile("file.ts", "let a: string = 1")
program = project.createProgram()
ts.getPreEmitDiagnostics(program)
```
which is awesome. But now, to reflect changes in diagnostics after editing a source file, you cannot just
```ts
project.updateSourceFile("file.ts", "let a: string = 'asdf'")
ts.getPreEmitDiagnostics(program)
```
as the diagnostics will be outdated and *not* reflect the change to `file.ts`!

To update the diagnostics after file changes, you need to do yet another
```ts
program = project.createProgram()
```
And this will take you about 1000-2000 ms, making it way too resource intensive and slow. Is this really intended?

**Comment by phil294** [comment]
I tried the same thing with non-bootstrap `ts-morph` now
```ts
sourceFile.replaceWithText(js)
await sourceFile.save()
project.getPreEmitDiagnostics()
```
and it seems to be just as slow, about 1500 ms on a modern computer.
So I guess this is more of a performance question issue after all
Thanks!

**Comment by dsherret** [comment]
Yup, it's necessary. ts-morph/bootstrap only helps with setting up the compiler API and not with using it.

You may find a bit of a performance boost by providing the old program (which is what ts-morph does internally):

```ts
program = project.createProgram({ oldProgram: program });
```

This is why it's recommended to [analyze first then manipulate afterwards](https://ts-morph.com/manipulation/performance#performance-tip-analyze-then-manipulate).

**Comment by phil294** [comment]
Thank you for clarification! I'll close this then.

For the record, passing `oldProgram` or using `ts-morph` instead of bootstrap both did not speed up performance.
