### ISSUE TITLE
is it normal for emitToMemory of a 40 lines file to take 3sec?

### ISSUE THREAD

**Issue by archywillhe** [dsherret/ts-simple-ast#1190]
what can cause it take a while to emitToMemory? Maybe I have too many dependencies and the module resolution during type-inference is taking too much time?

all I did is 

`
const result = sourceFile.emitToMemory()
`

It takes 3 seconds for 40 lines

**Comment by dsherret** [comment]
It could. That's basically just calling the TS compiler, which is slow.
