### ISSUE TITLE
Question: Getting declaration from parent

### ISSUE THREAD

**Issue by jmls** [dsherret/ts-simple-ast#1191]
I was wanting to write some code to find where a class method was being called from. 

so, I have

                   const referencedSymbols = method.findReferences();

                    for (const referencedSymbol of referencedSymbols) {
                        for (const reference of referencedSymbol.getReferences()) {
                            const kind = reference
                                .getNode()
                                .getParent()
                                .getKindName();

                            if (kind !== 'PropertyAccessExpression') {
                                continue;
                            }

                            console.log(
                                'File path: ' +
                                    reference.getSourceFile().getFilePath()
                            );

                            const parent = reference
                                .getNode()
                                .getParentWhile(
                                    (parent) =>
                                        parent.getKindName() !==
                                        'MethodDeclaration'
                                );

At this point the "parent" node is a MethodDeclaration kind - but how do I actually get the name of the method from this parent node ?

**Comment by jmls** [comment]
ok, so with some trial and error I think I've solved the problem. The code is below

```
const project = new Project({
            tsConfigFilePath: 'src/server/tsconfig.json'
        });

        const files = project.getSourceFiles([
            'src/server/**/*.service.ts'
        ]);

        for (const file of files) {
            const classes = file.getClasses();

            for (const serviceClass of classes) {
                const methods = serviceClass.getMethods();

                for (const method of methods) {
                    if (method.getScope() !== 'public') {
                        continue;
                    }

                    const referencedSymbols = method.findReferences();

                    for (const referencedSymbol of referencedSymbols) {
                        for (const reference of referencedSymbol.getReferences()) {
                            const kind = reference
                                .getNode()
                                .getParent()
                                .getKindName();

                            if (kind !== 'PropertyAccessExpression') {
                                continue;
                            }

                            const parent = reference
                                .getNode()
                                .getParentWhile(
                                    (parent) =>
                                        parent.getKindName() !==
                                        'MethodDeclaration'
                                )
                                .getParentIfKind(SyntaxKind.MethodDeclaration);

                            console.log(
                                method.getName(),
                                '<== called by',
                                parent.getName(),
                                'in',
                                reference.getSourceFile().getFilePath(),
                                '\n'
                            );
                        }
                    }
                }
            }
        }
```

**Comment by dsherret** [comment]
@jmls I would highly recommend using the `Node.isMethodDeclaration(node)` and similar type guards. That will allow you to do stuff like:

```ts
if (Node.isMethodDeclaration(parent)) {
  const methodName = parent.getName();
}
```
