### ISSUE TITLE
Type is undefined for method parameter with initializer

### ISSUE THREAD

**Issue by VaasRamsay** [dsherret/ts-simple-ast#1193]
While trying to get parameters of a method, `type` of a parameter is undefined if it has an initializer. 

Consider this example - 
```
  doSomething(key: string, timeTaken = defaultTimeTaken) {
    ...
    ...
  }
```

The second parameter with initializer doesn't have `type` information. 
```
    name: 'timeTaken',
    initializer: 'defaultTimeTaken',
    type: undefined
```

**Comment by Gerrit0** [comment]
Sounds like you're trying to get the type node - that's expected to not be set if it isn't specified in the source. If you ask the type checker for the type instead, you can get inferred type information. <https://ts-morph.com/navigation/type-checker>

**Comment by VaasRamsay** [comment]
that worked, thank you!
