### ISSUE TITLE
forEachDescendant for types

### ISSUE THREAD

**Issue by aleclarson** [dsherret/ts-simple-ast#1196]
Related to #727

**Is your feature request related to a problem? Please describe.**

I want to gather all non-builtin types from external modules, and there seems to be nothing like `forEachDescendant` to make that process easier.

**Describe the solution you'd like**

No particular solution in mind (other than it works like `forEachDescendant`).

**Describe alternatives you've considered**

Write my own implementation :(

**Comment by dsherret** [comment]
I think there would be some implementation specific details that would make implementing a general use version of this hard (for example, how to handle recursive types and should properties on all types be iterated over?). For that reason I'm going to say this is out of scope and I would recommend writing your own. Sorry!
