### ISSUE TITLE
Line ending without semicolon support

### ISSUE THREAD

**Issue by DVLP** [dsherret/ts-simple-ast#1200]
**Is your feature request related to a problem? Please describe.**

Ts-morph is being used to add imports in files but by default it always adds a semicolon at the end. There's no option to switch to no-semicolon line ending.

**Describe the solution you'd like**

It would be good to have a new option in manipulationSettings, i.e. "semicolon" with default **true** which can be set to **false**.

**Comment by dsherret** [comment]
I recommend people use code formatters like dprint or prettier on the output of ts-morph to achieve this as it would be too much work to maintain this.
