### ISSUE TITLE
Evaluate static expressions

### ISSUE THREAD

**Issue by derolf** [dsherret/ts-simple-ast#1203]
I am currently using the following function to evaluate an `ObjectLiteralExpression` into an object:

```TypeScript
function getObjectLiteral(node: ObjectLiteralExpression): Partial<Record<string, unknown>> {
  const text = node.getText();
  try {
    // eslint-disable-next-line @typescript-eslint/no-unsafe-return
    return eval(`(${text})`);
  } catch (e) {
    // eslint-disable-next-line @typescript-eslint/restrict-template-expressions
    throwError(node, `${node.getText()}: Error eval ${e}`);
  }
}
```

However, that's just a hack using `eval` and only works for simple objects.

Could we have a function in `ts-morph` that tries to evaluate expressions at compile time (static expressions)?

**Comment by dsherret** [comment]
It's difficult to do this correctly and handle all the situations unfortunately so I would say this is out of scope for this library. There are also cases where it can't resolve the value. I'd recommend people implement custom solutions for this to work in their specific scenarios that implement what they need.
