### ISSUE TITLE
setInitializer does not exist on type ObjectLiteralElementLike

### ISSUE THREAD

**Issue by souporserious** [dsherret/ts-simple-ast#1211]
**Describe the bug**

Version: 12.2.0

I'm not entirely sure if this is a bug, but I'm trying to modify the properties of an object and TS complains that `setInitializer' does not exist on type 'ObjectLiteralElementLike'. However, I noticed the `setInitializer` method was available on prototype and seems to work as expected. Not sure if I need to constrain this better or possibly do it another way?

**To Reproduce**

```ts
const project = new Project()
const code = `
animate('#box', { scale: 0.9, opacity: 1 })
`
const sourceFile = project.createSourceFile('index.ts', code)

sourceFile
  .getChildrenOfKind(ts.SyntaxKind.ExpressionStatement)
  .forEach((expression) => {
    expression
      .getDescendantsOfKind(ts.SyntaxKind.ObjectLiteralExpression)
      .forEach((expression) => {
        const scaleProperty = expression.getProperty('scale')
        if (scaleProperty) {
          scaleProperty.setInitializer('0.3')
        }

        const property = expression.addProperty('hello')
        property.setInitializer('world')

        console.log(expression.getFullText())
      })
  })
```

![image](https://user-images.githubusercontent.com/2762082/140020640-005c3246-d729-4710-97fa-e18f51d6a605.png)

**Expected behavior**

`setInitializer` and `getInitializer` are available to use and TS doesn't complain.

**Comment by dsherret** [comment]
The definition of `ObjectLiteralElementLike` is the following:

```ts
export type ObjectLiteralElementLike = PropertyAssignment | ShorthandPropertyAssignment | SpreadAssignment | MethodDeclaration | AccessorDeclaration;
```

...which mirrors the `ts.ObjectLiteralElementLike` type:

https://github.com/dsherret/ts-morph/blob/0e9e916f08216d88646161a9e945ccb5689c7727/packages/common/lib/typescript.d.ts#L753

The `ObjectLiteralElementLike` is what's used for properties on an `ObjectLiteralExpression`:

https://github.com/dsherret/ts-morph/blob/0e9e916f08216d88646161a9e945ccb5689c7727/packages/common/lib/typescript.d.ts#L1224-L1229

...so not all of those properties will have a `setInitializer` method.

What you could do is check if it's a PropertyAssignment:

```ts
if (Node.isPropertyAssignment(scaleProperty)) {
  scaleProperty.SetInitialize('0.3');
}
```

Or do something like:

```ts
const scaleProperty = expression.getProperty('scale')?.asKind(SyntaxKind.PropertyAssignment);
```

**Comment by souporserious** [comment]
Ah, this works perfect! I had a feeling it was lack of TS knowledge on my part, I appreciate the help! 🙏
