### ISSUE TITLE
oddity with same SyntaxKind values not matching

### ISSUE THREAD

**Issue by jmls** [dsherret/ts-simple-ast#1212]
I'm really confused about this.

```
        const children = schema.getChildren().filter(item => item.getKindName() === 'TypeLiteral')
        const children2 = schema.getChildrenOfKind(SyntaxKind.TypeLiteral);
```

I would expect children and children2 to be the same length (in this case 1). However, children2 has a length of 0

![image](https://user-images.githubusercontent.com/929523/140614038-80a71916-ae20-4a7c-b05b-475202dfd307.png)

so I did a little digging

and if I did 
```
        const literal1 = schema.getChildrenOfKind(180)[0];

        console.log("180 -->", literal1?.getKindName(), "TypeLiteral -->", SyntaxKind.TypeLiteral)
```
the result is

```180 --> TypeLiteral TypeLiteral --> 173```

and if I hover over the `SyntaxKind.TypeLiteral` in the editor, it shows that as a value of 173 - however AST viewer says it should be 180 ... 

There is something very screwy here ... probably on my end but I have no idea what I have done.

"ts-morph": "^12.2.0"

**Comment by dsherret** [comment]
@jmls how are you importing `SyntaxKind`? Are you importing it from ts-morph or using the `ts` export from ts-morph then doing `ts.SyntaxKind`? The values of `SyntaxKind.whatever` will change between versions of TypeScript quite a lot so mixing different TS compiler versions will cause trouble. For me, the value of `SyntaxKind.TypeLiteral` in 12.2.0 is 180.

**Comment by jmls** [comment]
ah! that would explain a lot ;)

```
import { ConstructorTypeNode, Identifier, Project, SourceFile } from "ts-morph";
import { SyntaxKind, TypeLiteralNode } from "typescript";
```

change to 

```
import { SyntaxKind, TypeLiteralNode, ConstructorTypeNode, Identifier, Project, SourceFile } from "ts-morph";
```

and it's all working as expected. Many thanks for the prompt response

**Comment by dsherret** [comment]
Cool. Yeah, this used to be a very common issue before ts-morph bundled its own compiler version.
