### ISSUE TITLE
Regression in `getReferencingNodesInOtherSourceFiles` from ts-morph@10 → ts-morph@11

### ISSUE THREAD

**Issue by danvk** [dsherret/ts-simple-ast#1227]
**Describe the bug**

Version: 11.0.0 and later

I've run into a situation (https://github.com/nadeesha/ts-prune/issues/151) where `file.getReferencingNodesInOtherSourceFiles()` returns the expected referencing nodes in ts-morph@10 and earlier, but returns no nodes in ts-morph@11 and later.

**To Reproduce**

```ts
import { Project } from 'ts-morph';

const project = new Project({
  tsConfigFilePath: '/Users/danvk/github/ts-prune-151-repro/tsconfig.json',
});

const file = project.getSourceFileOrThrow('/Users/danvk/github/ts-prune-151-repro/server/constants.ts');
const rawReferenced = file.getReferencingNodesInOtherSourceFiles();
console.log(rawReferenced.map(node => node.getText()));
```

For the repo being loaded, see https://github.com/danvk/ts-prune-151-repro/. It's three small files, included here for convenience:

```ts
// server/server.ts
import {run} from './mid';

run();
```

```ts
// server/mid.ts
import {A, B} from './constants';

export function run() {
  console.log(A, B);
  return null as any;
}
```

```ts
// server/constants.ts
export const A = 'a';
export const B = 'b';
```

**Expected behavior**

When I run that snippet with ts-morph@10 or earlier, I get the following output, which seems correct to me (it's a node that references `constants.ts`):

```json
[ "import {A, B} from './constants';" ]
```

When I run the same snippet with ts-morph@11 or later, I get the following output:

```json
[]
```

So what happened to the referencing node? I think this is a bug, but please let me know if I'm misunderstanding what this method is supposed to do or initializing my project in some invalid way.

**Comment by dsherret** [comment]
Thanks for the reproduction. I will fix it soon.

Caused by https://github.com/dsherret/ts-morph/commit/a41b7b54ab2ac47c95d91125cbc51a5488515b7d

**Comment by dsherret** [comment]
Fixed in 13.0.1

**Comment by danvk** [comment]
Confirmed that this fixes the original issue in ts-prune. Thanks for the quick fix @dsherret! Gotta put those curlies on `if` statements! :)

**Comment by dsherret** [comment]
@danvk no problem! The change that caused the regression was deliberate... it was just a bad fix 😅. I actually did start putting curly braces on all these in my other repos, but haven't switched this one over yet. With the config I set, the code formatter I use automatically does the indentation and braces like this so it would be hard-ish to get bitten by something like...

```ts
if (condition)
  statement;
  statement;
```

...because it would auto-format to...

```ts
if (condition)
  statement;
statement;
```
