### ISSUE TITLE
Should `ts-morph` analyze types of variables imported from external file?

### ISSUE THREAD

**Issue by cawa-93** [dsherret/ts-simple-ast#1229]
I tried a simple experiment:

```js
const project = new Project()
project.createSourceFile('./external.ts', `export const api = {foo: 'bar'}`)
project
  .createSourceFile('./demo.ts', `import {api} from './external.ts'; expose('k', api)`)
  .getFirstDescendantByKindOrThrow(SyntaxKind.CallExpression)
  .getArguments()[1]
  .getType()
  .getText() // return "any"
```

I expected the ts-morph return the type `{ foo: string; }` of variable that was imported. 

Am I doing something wrong, or is this expected behavior?

**Comment by dsherret** [comment]
See the output of `project.getPreEmitDiagnostics()`.

You might need to do node module resolution, so change `'./external.ts` to `./external`. For analyzing Deno code it's not very good at the moment and there's still lots of work to do to get that working properly. See #950.

**Comment by cawa-93** [comment]
Thanks. I forgot that the TS expect files without an extension.
