### ISSUE TITLE
`String` type isn't always considered a `string`

### ISSUE THREAD

**Issue by johngeorgewright** [dsherret/ts-simple-ast#1230]
**Describe the bug**

Version: 13.0.2

I'm not 100% sure if this is a bug, or maybe I'm just not fully understanding what "apparent" types are. I would have thought that the apparent type of `string`, or `String` (which is `String`) would be considered a `string`. However, this is not the case.

**To Reproduce**

```ts
import { Project } from "ts-morph";

const project = new Project();
const sourceFile = project.createSourceFile("test.ts", `type T1 = string; type T2 = String;`);

const type1 = sourceFile.getTypeAlias('T1').getType();
type1.getText(); // 'string'
type1.isString(); // true
type1.getApparentType().getText(); // 'String'
type1.getApparentType().isString(); // false
type1.getApparentType().isInterface(); // true

const type2 = sourceFile.getTypeAlias('T2').getType();
type2.getText(); // 'String'
type2.isString(); // true
type2.getApparentType().getText(); // 'String'
type2.getApparentType().isString(); // false
type2.getApparentType().isInterface(); // true
```

**Expected behavior**

```typescript
type1.getApparentType().isString(); // true
type2.getApparentType().isString(); // true
```

**Comment by dsherret** [comment]
This returns `false` for me and not `true`:

```ts
sourceFile.getTypeAlias("T2").getType().isString(); // false, not true
```

...which is expected because that's what the ts compiler does.

See this and look under "flags" in "Type" at how `string` has the type flag "String", but `String` doesn't:

https://ts-ast-viewer.com/#code/C4TwDgpgBAKgjFAvFAzsATgSwHYHMDcAUKJLAExJQDKGOBQA
