### ISSUE TITLE
Not possible to use different TS version than ts-morph's TS version

### ISSUE THREAD

**Issue by aem** [dsherret/ts-simple-ast#1231]
**Describe the bug**

Before diving in, super possible my use case isn't valid. If I'm using this wrong, let me know 😂

Version: ^0.9 -> ^0.12 tested, but likely present in all versions

tl;dr: Using `@ts-morph/bootstrap` with a TypeScript version different than `ts-morph`'s TS version is not possible. 

Because `@ts-morph/common` provides its own TS types rather than importing from a peer dependency, if there is a version mismatch between the TS types embedded in `ts-morph` and the installed typescript version, it's impossible for projects to mix types from their local TS version and `ts-morph`'s types. A minimal repro with the error I'm getting when trying to implement ts-morph internally is below.

CodeSandbox: https://codesandbox.io/s/beautiful-tu-9xpw8?file=/src/index.ts

**To Reproduce**

```ts
import { createProject } from '@ts-morph/bootstrap';
import ts from 'typescript';

export const run = async () => {
  const project = await createProject({tsConfigFilePath: '../tsconfig.json'})
  const files: ts.SourceFile[] = project.getSourceFiles()
}

run()
```

The output is the following type error:

```
Type 'import("/Users/{{me}}/git/{{project}}/node_modules/@ts-morph/common/lib/typescript").SyntaxKind.SourceFile' is not assignable to type 'import("/Users/{{me}}/git/{{project}}/node_modules/typescript/lib/typescript").SyntaxKind.SourceFile'.
```

**Expected behavior**

No type errors, I'd expect ts-morph to be pulling its TS definitions from node_modules rather than a .d.ts file

**Comment by dsherret** [comment]
This is a design limitation because there will often be breaking changes between patch versions of the TS compiler. I used to try to maintain peer dependencies and it was a nightmare.

I'd recommend to use the `ts` export from `@ts-morph/bootstrap`. Does that work in your scenario?

```ts
import { createProject, ts } from '@ts-morph/bootstrap';
```

**Comment by aem** [comment]
Hm. Since it was just a type incompatibility that might work, let me see! My only concern is that we maintain an internal fork of TS (which I know is indeed a nightmare to maintain 😬 so I empathize) that's a little behind the version in this project. Because of some custom module resolution code we have in webpack plugins, we needed to fork TS so that `tsc` would understand these custom module resolution rules which don't follow standard `node_modules` resolution patterns. Looks like our fork is up to the 4.4 TS series, so maybe that's close enough to the 4.5 in this project that the runtime impact won't be too big 🤞

I'll update here once I migrate to that `ts` import. If It looks like the versions are runtime incompatible I'll either look into getting our fork updated for 4.5 or fork this project internally so I can get things working. Either way, thanks for the speedy and helpful response!

**Comment by aem** [comment]
I ended up moving us back to 0.11.1 instead of 0.12.2 (so 4.4 series instead of 4.5 for TS) and then used `patch-package` in ts-morph's `.d.ts` file to import `from 'typescript'` instead of `from './typescript'` since moving to the `ts` export was going to be a pretty huge diff for us. This seems to be working ok! Since our usecase is pretty unique with our custom module resolution I'm just going to close this out, doesn't seem worth figuring out custom support for just one consumer :)
