### ISSUE TITLE
How to create a literal node expression and append to a file?

### ISSUE THREAD

**Issue by luiz290788** [dsherret/ts-simple-ast#1238]
I was able to create a variable declaration but then I need to provide a string or a writer function to define the object literal expression. Is there an easy more safe way to do this?

**Comment by brandongregoryscott** [comment]
I think what you're looking for are the `add`/`insert` property assignment functions off of `ObjectLiteralExpression`: https://ts-morph.com/details/object-literal-expressions#property-assignments

There's also functions for more specific use-cases, such as methods or shorthand assignments.

It's not obvious how to _add_ a new object literal expression without using the underlying `ts.factory` methods, but you can set the `initializer` for the variable declaration to an empty object and then act on it using the wrapped methods provided by `ts-morph`. I spun up a short CodeSandbox with an example: https://codesandbox.io/s/ts-morph-1238-j64xu?file=/src/create-source-file.ts

**Comment by luiz290788** [comment]
That's interesting, thanks for putting this up.

It would be nice to be able to pass a structure to the initializer. But I guess this is already good enough for me, thanks again!

**Comment by brandongregoryscott** [comment]
> It would be nice to be able to pass a structure to the initializer. But I guess this is already good enough for me, thanks again!

I agree - I assume it's just something that hasn't been implemented/widely needed yet. Happy to help!

**Comment by dsherret** [comment]
This is essentially #683, but it's a lot of work and I'm not sure it would be worth it. You can use the `Writers` export to help with this. An example is in https://github.com/dsherret/ts-morph/issues/895#issue-758508082
