### ISSUE TITLE
Specifying types causes emit to include directory name

### ISSUE THREAD

**Issue by weidehai** [dsherret/ts-simple-ast#1239]
**Describe the bug**

Version: 13.0.2

**To Reproduce**

```ts
const path = require('path');
const fs = require('fs/promises');
const { Project } = require('ts-morph');

const generateTypesDefinitions = async () => {
  const project = new Project({
    compilerOptions: {
      declaration: true,
      emitDeclarationOnly: true,
      outDir: path.resolve('./dist'),
      types: ['cypress'],
    },
  });

  const sourceFiles = [];
  const content = await fs.readFile(path.resolve('./src/index.ts'), 'utf-8');
  sourceFiles.push(project.createSourceFile(path.resolve('./src/index.ts'), content, { overwrite: true }));

  await project.emit();

  sourceFiles.map(async (sourceFile) => {
    const emitOutput = sourceFile.getEmitOutput();
    const emitFiles = emitOutput.getOutputFiles();
    emitFiles.map((file) => {
      console.log(file.getFilePath());
    });
  });
};

generateTypesDefinitions();
```
my folder structure like this
![image](https://user-images.githubusercontent.com/25458528/149537330-232ba6af-a89e-4101-a9bd-f8227fcbe7e0.png)

the fisrt bug is ,if i don't use the  { overwrite: true } option in project.createSourceFile,there will has a error as follow
![image](https://user-images.githubusercontent.com/25458528/149537802-9aab04c4-ce67-4684-acda-3174373eb9d2.png)
but actually i don't push anything to sourceFiles before,why it say  file already exists?

the second bug is,if i use types: ['cypress'] in new Project,then the console.log(file.getFilePath()) will print 
### **E:/data/data2/ts-morph-test/dist/src/index.d.ts**
but actually is output to dist,not dist/src
when i not use types: ['cypress'],then all thing as expected,the console.log(file.getFilePath()) print 
### **E:/data/data2/ts-morph-test/dist/index.d.ts**
this is consistent with the tsc compiler

and i try to change cypress to any other,is work consistent with the tsc compiler,just cypress is abnormal,i don't not what happend

**Expected behavior**

**Comment by weidehai** [comment]
@dsherret @cancerberoSgx @dicarlo2 @Pineapples

**Comment by Pineapples** [comment]
Hi, you probably want to use `addSourceFileAtPath` to add your source file. Using `createSourceFile` actually creates the file. As the file already exists, it throws an error.

[Check the documentation for more info](../tree/latest/docs/setup/adding-source-files.md)

**Comment by weidehai** [comment]
> 

thanks for your answer，Could you please explain the second question，why the actually output  directory is different with emitFiles path when set types: ['cypress'] option

**Comment by weidehai** [comment]
> Hi, you probably want to use `addSourceFileAtPath` to add your source file. Using `createSourceFile` actually creates the file. As the file already exists, it throws an error.
> 
> [Check the documentation for more info](../tree/latest/docs/setup/adding-source-files.md)

thanks for your answer，Could you please explain the second question，why the actually output directory is different with emitFiles path when set types: ['cypress'] option

**Comment by Pineapples** [comment]
I can verify your second issue, its quite curious. Sadly I don't know enough about the project to have an explanation nor can I quickly find one. Interestingly if you do a `project.emit()` after you do the `file.getFilePath()` it gets the correct paths.

**Comment by weidehai** [comment]
> I can verify your second issue, its quite curious. Sadly I don't know enough about the project to have an explanation nor can I quickly find one. Interestingly if you do a `project.emit()` after you do the `file.getFilePath()` it gets the correct paths.

ok thanks again, hope someone can explain the problem

**Comment by dsherret** [comment]
@weidehai when "types" wasn't provided, the TS compiler considered the `./src` directory to be the root directory. So when emitted it would go to `./dist/index.d.ts`, but once "types" was added, it now considered `./` to be the root directory because it's now using stuff from the `./src` directory and `./node_modules` directories.

If you add a `rootDir: "./src",` compiler option it will force the root directory to be `./src` and it will fix your issue.

**Comment by dsherret** [comment]
Also, please don't tag a bunch of people who have contributed to a repo when opening issues. Opening an issue is sufficient.

**Comment by weidehai** [comment]
> Also, please don't tag a bunch of people who have contributed to a repo when opening issues. Opening an issue is sufficient.

https://github.com/dsherret/ts-morph/issues/1239#issuecomment-1019348844

**Comment by weidehai** [comment]
> Also, please don't tag a bunch of people who have contributed to a repo when opening issues. Opening an issue is sufficient.

ok i got it, thanks a lot
