### ISSUE TITLE
Empty results on getVariableDeclarations

### ISSUE THREAD

**Issue by jon9090** [dsherret/ts-simple-ast#1243]
**Describe the bug**

Version:`^13.0.2`

I try to find all the variable declarations within the class:
```
const vars = sourceFile.getVariableDeclarations();
```
But I got empty array. which is incorrect because I have in the code `VariableDeclarations`:
```
 export class Foo {

    test() {
        const that = this;
        that.open();
    }
  }
  `
```

In ts-ast-viewer.com it show the `VariableDeclaration` in the tree:
https://ts-ast-viewer.com/#code/ATCmA8AcHsCcBdgGMA2BDAzh4Axa1gBvAKGJBHlA3gAoBKIs85paAO2uHgAs1EBeLtwCWGANxNmFXvAB00SKDb0JzAL5M1QA

![image](https://user-images.githubusercontent.com/74149517/152991008-7fc9cdc6-e1fa-4ba2-9565-a95251f8a7b1.png)

**To Reproduce**

```ts
  import { Project } from "ts-morph";

  const project = new Project({
    skipAddingFilesFromTsConfig: true,
  });

  const sourceFile = project.createSourceFile(
    'myNewFile.ts',
    `
  export class Foo {

    test() {
        const that = this;
        that.open();
    }
  }
  `
  );
  const vars = sourceFile.getVariableDeclarations();
  console.log({ vars }); // <--- vars === [] - but why??

```

**Expected behavior**

**Comment by dsherret** [comment]
`sourceFile.getVariableDeclarations();` will only return the source file's children variable declarations. You'll need to do something like `sourceFile.getClassOrThrow("Foo").getMethodOrThrow("test").getVariableDeclarations()` (going from memory, but it's something along those lines).
