### ISSUE TITLE
print removes newlines in the code

### ISSUE THREAD

**Issue by wizardnet972** [dsherret/ts-simple-ast#1246]
**Describe the bug**

Version: ^13.0.2

`print` removes newlines in the code, inside the functions, and/or between the functions.

**To Reproduce**

```ts
import { Project } from "ts-morph";

  const project = new Project({
     skipAddingFilesFromTsConfig: true,
  });

  const sourceFile = project.createSourceFile(
    'foo.ts',
    `
  
    function foo() {
       console.log('x');

       console.log('x');

       console.log('x');
 
   }

    function bar() {

    }
  `
  );

  fs.writeFileSync('test.ts', sourceFile.print());

```

The content of `test.ts`:
```
function foo() { 
 console.log('x'); 
 console.log('x');
 console.log('x');
}
function bar() {
}
```
**Expected behavior**
```

function foo() {
 console.log('x');

 console.log('x');

 console.log('x');

}

function bar() {
}
```

**Comment by dsherret** [comment]
`sourceFile.print()` uses the typescript printer (`ts.createPrinter`) to "print" out the code and ts-morph doesn't have any control over how it prints out the AST to a string beyond the options provided. Use `sourceFile.getFullText()` instead.
