### ISSUE TITLE
Manipulating a class in an ambient context

### ISSUE THREAD

**Issue by dsherret** [dsherret/ts-simple-ast#125]
Separating this out into its own task from #27.

**Comment by dsherret** [comment]
I think this is already done. Please open an issue if there's anything I forgot or comment here.

**Comment by derolf** [comment]
Are you sure? I have an ambient module with classes. If I add a member function, I get “{}”, but I would expect just “;”.

**Comment by dsherret** [comment]
@derolf thanks for bringing that to my attention! There was a bug where it wouldn't thoroughly check if it was in an ambient context when adding/inserting a class to an ambient module in a non-declaration file. This is released and should be fixed now in 10.3.3. I believe that was probably the issue you encountered? If not, could you submit a short example that shows the problem? Thanks!
