### ISSUE TITLE
Question: Setting up a project with in-memory FS + typeRoots from disk?

### ISSUE THREAD

**Issue by jasonkuhrt** [dsherret/ts-simple-ast#1252]
I'm trying to setup a project using in memory FS but need the usual consumption of `node_modules/@types`. Is this possible? am I doing something wrong? Is the proper way to do that is manually using the `.createSourceFile`  method of the project?

<img width="820" alt="CleanShot 2022-03-02 at 19 00 00@2x" src="https://user-images.githubusercontent.com/284476/156470103-1bcbbf97-8488-4528-b79c-d474f9a3d0a9.png">

What currently happens is that stuff like `Promise.resolve(1)` infers to `any` type.

**Comment by jasonkuhrt** [comment]
Actually, my problem is around having the `node_modules/typescript/lib` files loaded. As I think `Promise` global comes from that, not Node. Anyways, confidence around both these aspects would be great.

**Comment by dsherret** [comment]
The `node_modules/typescript/lib` files should get automatically loaded if you remove `skipLoadingLibFiles: false`.

If you need additional types from the file system, then you can load them into an in memory file system host:

```
const fileSystem = new InMemoryFileSystemHost();

// read each file form the disk, then write it into the in memory file system host here
for (const file of ...) {
  fileSystem.writeFileSync("/node_modules/figure-out-some-path-name-here-for-the-file", file.text);
}

const project = new Project({
  // etc...
  fileSystem,
});
```

**Comment by jasonkuhrt** [comment]
> The node_modules/typescript/lib files should get automatically loaded if you remove skipLoadingLibFiles: false.

That doesn't seem to be the case. Could it be because there is a monorepo setup and the `node_modules` directory in this case is in an ancestor directory? The path from the module to that direct is: `Path.join(__dirname, '../../../../../node_modules/typescript/lib')`.

**Comment by jasonkuhrt** [comment]
Current situation:
```ts
const tsMorphProject = new tsm.Project({
    compilerOptions: {
      rootDir: './src',
      outDir: './dist',
      target: tsm.ts.ScriptTarget.ESNext,
    },
    skipAddingFilesFromTsConfig: true,
    useInMemoryFileSystem: true,
  })
```
```ts
export const a = Promise.resolve(1) // `a` is inferred to be `any`
```

**Comment by jasonkuhrt** [comment]
Oh, perhaps this is interesting:

```ts
export type A = Omit<{ a:1, b:2 }, 'a'>
```

Here, `Omit` is correctly understood as being declared in `/node_modules/typescript/lib/lib.es5.d.ts`.

So, the lib files, some, are being picked up OK it seems?

Perhaps I am configuring something wrong to not have Promise be defined globally?

**Comment by dsherret** [comment]
Works for me when targeting ESNext (I think the default is ES5 and that doesn't have Promise):

```ts
> import { Project, ts } from "https://deno.land/x/ts_morph@13.0.3/mod.ts";
undefined
> const project = new Project({ useInMemoryFileSystem: true, compilerOptions: { target: ts.ScriptTarget.ESNext } });
undefined
> const sourceFile = project.createSourceFile("test.ts", "function test() { return Promise.resolve(1); }");
undefined
> sourceFile.getFunctions()[0].getReturnType().getText()
"Promise<number>"
```

**Comment by jasonkuhrt** [comment]
I'll post notes here and close issue once resolved for posterity.

So `export type A = Promise<number>` works for me, tracked as being declared in `/node_modules/typescript/lib/lib.es5.d.ts`.

But as soon as I go to refer to `Promise` at the term level it become `any`: `export type A = typeof Promise` and `A` is seen as an `any` type.

I was able to reproduce your snippet in my terminal just fine:

```ts
❯ yarn ts-node
> import { Project, ts } from "ts-morph";
undefined
> const project = new Project({ useInMemoryFileSystem: true, compilerOptions: { target: ts.ScriptTarget.ESNext } });
undefined
> const sourceFile = project.createSourceFile("test.ts", "function test() { return Promise.resolve(1); }");
undefined
> sourceFile.getFunctions()[0].getReturnType().getText()
'Promise<number>'
```

Furthermore in code this works too:

<img width="1045" alt="CleanShot 2022-03-02 at 19 31 29@2x" src="https://user-images.githubusercontent.com/284476/156473088-44fb6685-b67e-4b41-8635-164c383ad3ce.png">

So, I'm beginning to think that something inside the Paka extractor must be wrong. Investigating.

**Comment by jasonkuhrt** [comment]
Nothing to do with ts-morph. There's nothing much to share for posterity really, since the issue was so specific and random to my codebase.

As always thanks @dsherret amazing project!

**Comment by souporserious** [comment]
I specifically got this working by setting `moduleResolution` which loaded the custom node module type definitions I added in a custom file system:

```ts
const project = new Project({
  fileSystem,
  compilerOptions: {
    target: ts.ScriptTarget.ESNext,
    moduleResolution: ts.ModuleResolutionKind.NodeJs,
  },
})
```
