### ISSUE TITLE
export class A extends Promise<1> {} returns undefined for base class

### ISSUE THREAD

**Issue by jasonkuhrt** [dsherret/ts-simple-ast#1253]
**Describe the bug**

Version: 12.0.0

**To Reproduce**

```ts
import { Project } from 'ts-morph'

const project = new Project()
const sourceFile = project.createSourceFile('test.ts', `export class A extends Promise<1>,  {}`)

// reproduce the problem here
console.log(sourceFile.getClasses()[0].getBaseClass()?.getText()) // undefined
```

**Expected behavior**

It should get the Promise class.

**Comment by dsherret** [comment]
```ts
> typeChecker.getBaseTypes(type)[0].symbol.declarations.map(d => d.getText())
(5) ['interface Promise<T>{then<TResult1=T,TResult2=neve…ke<TResult>)|undefined|null):Promise<T|TResult>;}', 'interface Promise<T>{}', 'Promise:PromiseConstructor', 'interface Promise<T>{finally(onfinally?:(()=>void)|undefined|null):Promise<T>}', 'interface Promise<T>{readonly[Symbol.toStringTag]:string;}']
> typeChecker.getBaseTypes(type)[0].symbol.declarations[2].parent.getText()
var Promise:PromiseConstructor
```

https://github.com/microsoft/TypeScript/blob/main/src/lib/es2015.promise.d.ts

Looking into it, Promise is not a class and so that's out of scope for that `getBaseClass` method. You'll have to use the lower-level methods like `classDecl.getBaseTypes()` to figure this out.

**Comment by jasonkuhrt** [comment]
@dsherret Do you think there is something actionable here for ts-morph? I'm actually not sure on what is correct here to support. Can class extends extend pretty much anything? If so, does ts-morph today make it as easy as it could be traverse this information at the type level?

**Comment by dsherret** [comment]
It's a little ambiguous what an additional helper method could return here. The `getBaseClass()` is intended to be a helper method for when the base is a class declaration because `.getBaseTypes()` is a little too low level for those simple situations. For this situation the recommended method to use is `.getBaseTypes()` and then you can decide if you want to get all the interfaces or just the variable declaration out of it.

**Comment by jasonkuhrt** [comment]
@dsherret In the following case why would it still be `undefined`?

```ts
import { Project } from 'ts-morph'

const project = new Project()
const sourceFile = project.createSourceFile('test.ts', `export class A extends Promise,  {}`)

// reproduce the problem here
console.log(sourceFile.getClasses()[0].getBaseClass()?.getText()) // undefined
```

**Comment by dsherret** [comment]
Use `getBaseTypes()` since `Promise` is not defined as a class declaration and target at least es2015 by specifying the `target` compiler option or whatever other compiler options would cause that promise es2015 lib file to be included.

**Comment by jasonkuhrt** [comment]
@dsherret I see, its based on the class syntax and older JS uses functions for classes.

**Comment by dsherret** [comment]
It’s just however it happens to be defined in the .d.ts files.

**Comment by jasonkuhrt** [comment]
Ah ok, I'll take a look at that too.
