### ISSUE TITLE
How does one add to a class private variables?

### ISSUE THREAD

**Issue by rexkenley** [dsherret/ts-simple-ast#1257]
I need to add private variables within a class. How do I do that?

I tried properties, but it doesn't have the toggleModifier method.

`export class Test implements ComponentFramework.StandardControl<IInputs, IOutputs> {  
private container: HTMLDivElement; }`

Thanks.

**Comment by dsherret** [comment]
the `#` is part of the name, so you should be able to specify `#nameOfYourProp` for the name instead of `nameOfYourProp`. Does that work?

**Comment by rexkenley** [comment]
Cool! That works. I can also add private to the name.

Is there a way to move it to the top of the class, before the constructor?

plop:
![image](https://user-images.githubusercontent.com/10548251/157546032-a73aae5f-1898-4c34-905e-40864ed3a7b7.png)

result:
![image](https://user-images.githubusercontent.com/10548251/157546494-dde02f7b-1093-415e-b70a-7bf629c3bd50.png)

**Comment by rexkenley** [comment]
@dsherret 

Solved it, I have to use insertProperties(0, {}). Thanks for your help!
