### ISSUE TITLE
Ability to emit to memory

### ISSUE THREAD

**Issue by dsherret** [dsherret/ts-simple-ast#126]
Right now an emit will always write a disk. As was discussed in #109, it would be useful to be able to emit to memory, manipulate it, then finally save it to disk.

Probably something like this:

```typescript
// needs different method name
const emitResult = project.softEmit(); // this probably would return another Project object
const sourceFile = emitResult.getSourceFileOrThrow("SomeFile.js");
sourceFile.insertStatements(sourceFile.getClassOrThrow("C").getChildIndex() + 1, "// code to insert would go here");
await emitResult.save();
```

**Comment by fbartho** [comment]
This is particularly valuable if you want to use 1 file as a template, and then fork it, replacing the content many times. Basically 1 exemplar of each thing you want to code-generate, and then rename each appropriate thing N times as you process your repo.

**Comment by dsherret** [comment]
Will be in the next version. For speed, this just plainly creates an object holding the text (without parsing it):

```ts
const project = new Project({ compilerOptions: { outDir: "dist" } });
project.createSourceFile("MyFile.ts", "const num = 1;");
const result = project.emitToMemory();

// output the emitted files to the console
for (const file of result.getFiles()) {
    console.log("----");
    console.log(file.filePath);
    console.log("----");
    console.log(file.text);
    console.log("\n");
}
```

And if you want to manipulate before saving, then load the file texts into a new project and manipulate that before saving:


```ts
const project = new Project({ compilerOptions: { outDir: "dist" } });
project.createSourceFile("MyFile.ts", "const num = 1;");
const result = project.emitToMemory();

// load the javascript files into a new project
const newProject = new Project();
for (const file of result.getFiles()) {
    newProject.createSourceFile(file.filePath, file.text, { overwrite: true });
}

// ...manipulate the javascript files here...

// save the new files to the file system
newProject.save();
```

That said, for speed you may want to use the custom transformers instead. See #409.
