### ISSUE TITLE
How can I calcute sourcefile's size?

### ISSUE THREAD

**Issue by Eve-Sama** [dsherret/ts-simple-ast#1262]
**Is your feature request related to a problem? Please describe.**
I wanna show file size just like angular schematics. 

```bash
UPDATE src/index.ts (152 bytes)
```

But I am not using angular shcematics, I wanna use ts-morph to calculate a file's size. Does this API existed?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by lazarljubenovic** [comment]
It's just the byte size of the string. Grab the source code of the file (as a string) and do `Buffer.byteLength(str, 'utf8')`.
