### ISSUE TITLE
Is it possible to get a class property is optional or not?

### ISSUE THREAD

**Issue by calidan-x** [dsherret/ts-simple-ast#1265]
class Book{
    title: string
    author?: string
}

I would like to know **author** is optional

**Comment by calidan-x** [comment]
got it, hasQuestionToken()

**Comment by rmagatti** [comment]
What if it is typed like this instead?
```
class Book{
  title: string;
  author: string | undefined;
}
```

**Comment by lazarljubenovic** [comment]
Then you'd have to cover that case too, if you want to. They're not equivalent (e.g. `in` operator would return different results).
