### ISSUE TITLE
Add helper properties for template literal type nodes

### ISSUE THREAD

**Issue by dsherret** [dsherret/ts-simple-ast#1266]
https://github.com/dsherret/ts-morph/blob/75c4a75659c4e15e13913e965b6150d54ade5de8/packages/ts-morph/src/compiler/ast/type/TemplateLiteralTypeNode.ts#L5

**Comment by louwers** [comment]
Is it possible to get the value of a template literal type? Or do you plan to add that?

`getLiteralValue()` seems only to work for simple template literal types. If you can share some knowledge, that would be awesome. I'm trying to use TypeScript's template literal types to generate code.

Edit: I got it to work with `getLiteralValue()`

**Comment by louwers** [comment]
Just saw your tweet! The approach I am taking now is assigning the template literal type to a non-matching string, and then using the diagnostics to get the value.

**Comment by dsherret** [comment]
@louwers yeah, I just realized that template literals with no substitutions are `LiteralType` with a `NoSubstitutionTemplateLiteral` in it, so you can just call `getLiteralValue()` on it https://ts-ast-viewer.com/#code/C4TwDgpgBAKhDOwoF4oAM6LQbiA
