### ISSUE TITLE
Is there a technical reason `VariableDeclaration` isn't an `ExportableNode`?

### ISSUE THREAD

**Issue by brandongregoryscott** [dsherret/ts-simple-ast#1267]
Hey there! I'm looking to implement a feature that transforms all in-line exports to exports at the end of a source file.

For functions that are defined as variables (i.e. `const noop = () => {};`, they are showing up in map that's returned from `sourceFile.getExportedDeclarations()` but it looks like they aren't classified as an `ExportableNode`:
https://codesandbox.io/s/silly-glade-us2jev?file=/src/create-source-file.ts

I'm seeing that it is an `ExportGetableNode`, but that interface doesn't have the `setIsExported` on it. Is there any technical reason for this? Or any recommended workarounds?

**Comment by dsherret** [comment]
Yes. `VariableStatement` is the node that gets exported. That's because it's possible to have multiple variable declarations per exported variable statement:

```ts
export const myVar1 = 1, myVar2 = 2;
```

https://ts-ast-viewer.com/#code/KYDwDg9gTgLgBAYwgOwM7wLYE8BqBDKARjgF45CAaObfKAJlLjoG4g

**Comment by brandongregoryscott** [comment]
Ah, okay! I always forget you can define variables in a list like that. I'm thinking I can probably get away with traversing back up to to the `VariableStatement`, removing the `export` keyword, and adding the names of the individual variables at the end of the file. Thanks!

**Comment by dsherret** [comment]
I think there's a `getVariableStatementOrThrow()` helper function on variable declarations that you could use to get the variable statement.

**Comment by brandongregoryscott** [comment]
Ooh - that makes it even easier 🎉 thanks for the help!
