### ISSUE TITLE
Support transforming a node into multiple nodes

### ISSUE THREAD

**Issue by 11joselu** [dsherret/ts-simple-ast#1269]
**Describe the bug**

Version: 14.0.0

**To Reproduce**

I'm trying to replace a Node with multiples nodes, but throws an error `Unhandled SyntaxKind: Unknown.`. For example

```javascript
function transformer(): string {
  const project = new Project({});
  const sourceFile = project.createSourceFile(
    "",
    `
    let a = 1;
    a = 2;
  `
  );

  sourceFile.transform((traversal) => {
    const node = traversal.visitChildren();

    if (ts.isExpressionStatement(node)) {
      // Return it twice.
      // Effectively duplicating the statement
      return [node, node];
    }

    return node;
  });

  return sourceFile.getFullText();
}
```

**Expected behavior**

Using the TS compiler directly we can achieved. Example at https://github.com/madou/typescript-transformer-handbook#replacing-a-node-with-multiple-nodes

**Comment by dsherret** [comment]
This enhancement is out of scope. Although this pattern is possible with the compiler api, returning multiple nodes is not guarnateed to work in every scenario and so I don't want to allow it. Instead what is possible and recommended is to update the parent node and insert multiple nodes in the place of the single node.
