### ISSUE TITLE
typescript 4.7.0 support

### ISSUE THREAD

**Issue by hugebdu** [dsherret/ts-simple-ast#1272]
Seems like typescript 4.7 [is around the corner](https://content.techgig.com/technology-guide/microsoft-launches-typescript-4-7-beta-version-know-more-here/articleshow/90817547.cms), however `ts-morph` [insists](https://github.com/dsherret/ts-morph/blob/latest/packages/common/package.json#L40) on v4.6.

Any plans to upgrade?

Thanks!

**Comment by dsherret** [comment]
I always do the upgrade after the TypeScript stable release. TS 4.7 will be released May 24th.

Yeah, it needs to be pinned to a specific TypeScript version because TS doesn't have a stable API, but ts-morph tries to be stable... so lots of stuff breaks between TS versions usually.

**Comment by dsherret** [comment]
Closed by #1281
