### ISSUE TITLE
Synthetic comments are not present in result after using transform

### ISSUE THREAD

**Issue by timvandam** [dsherret/ts-simple-ast#1273]
**Describe the bug**

Version: 14.0.0

When adding comments inside of `transform()`, the comments are not present in the result

**To Reproduce**

```ts
import { Project, ts, SyntaxKind } from "ts-morph";

const p = new Project({ compilerOptions: { removeComments: false } })
const psf = p.createSourceFile('x.ts', `const x: number = 5 * 9;`)
psf.transform(traversal => {
	const node = traversal.visitChildren()
	if (node.getChildCount() === 0) {
		return ts.addSyntheticLeadingComment(node, SyntaxKind.MultiLineCommentTrivia, 'A', false)
	}
	return node
})
console.log(psf.getFullText()) // const x: number = 5 * 9
```

**Expected behavior**

I would expect something along the lines of this would be the result:
```ts
const /*A*/ x: /*A*/ number = /*A*/ 5 /*A*/ * /*A*/ 9
```

**Comment by timvandam** [comment]
It appears that this is not a specific issue with transform, but rather with synthetic comments. The following also fails:
```ts
function transformRecursively(node: Node, fn: (node: Node) => void): void {
	fn(node)
	node.forEachChild(fn)
}

psf.getStatements().forEach(x => transformRecursively(x, node => {
	ts.addSyntheticLeadingComment(node.compilerNode, SyntaxKind.MultiLineCommentTrivia, 'A', false)
}))
```

**Comment by dsherret** [comment]
The second example using `getStatements()` and then `ts.addSyntheticLeadingComments` will never work because `node.compilerNode` is essentially meant to be readonly and any changes to it won't be reflected in the source file.

The first example is a bug.
