### ISSUE TITLE
Is it possible to speed up node.getType() method

### ISSUE THREAD

**Issue by calidan-x** [dsherret/ts-simple-ast#1282]
I have a project using ts-morph, and it's working amazing, as compile files become more and more, I found the most slow part is node.getType() .

Is it possible to speed up node.getType() method? It will be a huge performance upgrade.

**Comment by dsherret** [comment]
That essentially calls `typeChecker.getTypeAtLocation(...)` in the typescript compiler, so not possible to speed it up in ts-morph from my knowledge (unless there's some caching api that ts-morph is not taking advantage of)

**Comment by calidan-x** [comment]
thank you
