### ISSUE TITLE
replaceWithText modifies line breaking characters

### ISSUE THREAD

**Issue by timvahlbrock** [dsherret/ts-simple-ast#1284]
**Describe the bug**

Version: 14.0.0, can be reproduced in 15.0.0 too. (Windows)

When replacing a file or node with text, the line breaking character will be LF, even if it originally was CRLF and the replacement also uses CRLF.

**To Reproduce**

Project structure:

```
tsconfig.json
test.ts
src
  |-main.ts
 ```

Content of test.ts:
```ts
import { resolve } from "path";
import { Project } from "ts-morph";

const project = new Project({
    tsConfigFilePath: resolve(__dirname, "tsconfig.json")
});

const file = project.getSourceFileOrThrow(resolve(__dirname, "src/main.ts"));
const text = file.getText();
file.replaceWithText(text);
project.saveSync();
file.refreshFromFileSystemSync();
const newText = file.getText();

if (!newText.includes("\r\n")) {
    throw new Error("Line break changed");
}
console.log("Everything is fine");
```

main.ts can contain anything, but needs to use CRLF line breaks.

Run using `ts-node test.ts`.

**Expected behavior**

After writing, the file still contains CRLF line breaks, rather than LF only. Therefore this script shouldn't run into the error case.

**Comment by dsherret** [comment]
Try this:

```ts
import { Project, NewLineKind } from "ts-morph";

const project = new Project({
    tsConfigFilePath: resolve(__dirname, "tsconfig.json"),
    manipulationSettings: {
        newLineKind: NewLineKind.CarriageReturnLineFeed,
    },
});
```

**Comment by timvahlbrock** [comment]
`newLineKind: NewLineKind.CarriageReturnLineFeed,` does the trick, thanks. Thought this would be automatically recognized/restored.
