### ISSUE TITLE
Lib files aren't loaded into in-memory right away in some cases

### ISSUE THREAD

**Issue by pashakondratyev** [dsherret/ts-simple-ast#1289]
**Describe the bug**
TypeError thrown when getting definitions from lib files.
Version:  > 10.0.0

**To Reproduce**

I noticed that when navigating a project, checking for a decorator

```ts
decorator => {
        if (decorator.isDecoratorFactory()) {
            const definitions = decorator.getNameNode().getDefinitions();
            ...
         }
}
```
will throw with a TypeError
```
Cannot read properties of undefined (reading '_doActionPreNextModification')
TypeError: Cannot read properties of undefined (reading '_doActionPreNextModification')
    at new DocumentSpan (/node_modules/.pnpm/ts-morph@15.0.0/node_modules/ts-morph/dist/ts-morph.js:17064:26)
    at new DefinitionInfo (/node_modules/.pnpm/ts-morph@15.0.0/node_modules/ts-morph/dist/ts-morph.js:17121:9)
```
But when I call  `decorator.getNameNode().getSymbol()` first, it does not throw, and the behavior is as expected.
It seems that the lib files are not being loaded into memory. For context the decorator I am checking is the `Function` decorator

**Expected behavior**
The lib files should be loaded, and there should not be an error thrown

**Comment by dsherret** [comment]
Let me know if it still happens in 15.1.0 (released just now). If so, it would be useful to have a reproducible example.

**Comment by pashakondratyev** [comment]
15.1.0 appears to fix this, thanks so much for the quick fix
