### ISSUE TITLE
Calling `replaceWithText` on private static property with no spaces to be non-private leads to error

### ISSUE THREAD

**Issue by Wyctus** [dsherret/ts-simple-ast#1292]
**Describe the bug**

Version: 15.1.0

I have a class with a private static property that I would like to make public by renaming it. The weird thing is, that the issue only happens if the file is in minified form.

**To Reproduce**

```ts
import { Project, SyntaxKind } from "ts-morph";

// This works
const content1 = `
class Test{
    static #t = 23;
}`;

// This fails
const content2 = "class Test{static#t=23;}";

const project = new Project();
const file = project.createSourceFile("test.ts", content2);

const classNode = file.getFirstChildByKindOrThrow(SyntaxKind.ClassDeclaration);
const property = classNode.getFirstChildByKindOrThrow(SyntaxKind.PropertyDeclaration);
const privateIdentifier = property.getFirstChildByKindOrThrow(SyntaxKind.PrivateIdentifier);

// remove # from the beginning of the name
const publicName = privateIdentifier.getText().substring(1);
privateIdentifier.replaceWithText(publicName);

console.log(file.getText());
```

If I use the minified input (content2), then the following error is thrown: 
```
Stack: Error: Error replacing tree! Perhaps a syntax error was inserted (Current: SyntaxList -- New: Identifier).
```

**Expected behavior**

It should work with the minified version as well.

**Comment by Wyctus** [comment]
I guess that the issue is  that `class Test{static#t=23;}` gets turned into `class Test{statict=23;}` which is not recognized as a static property, but as a non-static property with name `statict`. 

If I prepend a space in from of the name, then it works fine:
`privateIdentifier.replaceWithText(" " + publicName);`
and produces the `class Test{static t=23;}` output, which confirms the above suspicion.

The AST Viewer also confirms this: https://ts-ast-viewer.com/#code/MYGwhgzhAEAqCmEAuBvZYkEthILwCYBmAbgF8g
Here you can see an `Identifier` with the name of `statict`.

So I guess the issue is that the `static` keyword is removed in this case by renaming the identifier which causes the AST to change structure since the 3 children of the `PropertyDeclaration` gets reduced to 2.

**Comment by dsherret** [comment]
replaceWithText is kind of a low level method, but I think it's easy enough to handle this scenario

**Comment by Wyctus** [comment]
Thanks. Yes, I ended up using this simple trick. It is also pretty rare that somebody is dealing with minified Typescript source, so not many people are affected by this, most likely only me. 😅

**Comment by dsherret** [comment]
Yeah, I started working on it, but it's a decent amount of additional code. I'm going to close this one as "wont do" and recommend adding some conditional logic like the following to tell if a space should be added:

```ts
const content2 = "class Test{static#t=23;}";

const project = new Project();
const file = project.createSourceFile("test.ts", content2);

const classNode = file.getClassOrThrow("Test");
const property = classNode.getPropertyOrThrow("#t");
const privateIdentifier = property.getNameNode();

// remove # from the beginning of the name
let publicName = privateIdentifier.getText().substring(1);
if (isAlphaNumeric(file.getFullText().charCodeAt(privateIdentifier.getStart() - 1))) {
  // add a space if the previous character is alphanumeric
  publicName = " " + publicName;
}
privateIdentifier.replaceWithText(publicName);

console.log(file.getText());

function isAlphaNumeric(charCode: number) {
  return charCode > 47 && charCode < 58 // 0-9
    || charCode > 64 && charCode < 91 // A-Z
    || charCode > 96 && charCode < 123; // a-z
}
```

**Comment by Wyctus** [comment]
This is clever, thank you!
