### ISSUE TITLE
Question: Saving AST to file

### ISSUE THREAD

**Issue by jfangrad** [dsherret/ts-simple-ast#1297]
Hi, first of all I have been using this library a lot lately and think its awesome.

I have a bit of an interesting use case for this library that I think is kinda pushing the boundaries a bit. We are collecting usages of functions/types/interfaces/enums/etc from our shared packages within a repo. As a result we are doing a lot of `findReferencesAsNodes` calls from a lot of different declaration nodes (we have a lot of shared types from our API definitions). The individual calls are pretty quick (avg 30ms or so) but the volume is the problem. On our bigger repos, running the script to collect usages can take upwards of 40 min 😢 .

As a result we started looking at parallelizing the process using node `Worker`s. Since the `Project` class can't be transferred each thread needs to make its own and thus each thread needs to generate the AST which takes a decent amount of time and a large amount of disk reads. In doing this we realized trying to instantiate multiple `Project`s at the same time is terrible since they all compete for reads while building their AST.

So **TL;DR** it would awesome if there was some way to save the AST to a file that could then be used to re-generate the AST from without starting from scratch. This way the threads could each just build their AST from the saved file saving some time and resources. Not sure if this is even possible but would love your thoughts here. Also happy to explain more about our use case if needed.

Thanks again for all your work here.

**Comment by jfangrad** [comment]
Closing since the answer to this was almost definitely no and I found an alternative method that sped up the process almost 10x.

**Comment by dsherret** [comment]
Sorry, I read this, but I wasn't sure of a way. Source files need to be reparsed each time because they contain a lot of references and aren't easily serializable. There is the incremental program internally in the compiler that could maybe be used in ts-morph and then exposed, but I'm not sure how much it would speed up this scenario.

If a lot of disk reads are causing trouble then maybe you could have a dedicated worker that caches disk reads and then the other workers provide a custom file system to ts-morph (`new Project{ fileSystem }`) that get files from this worker. It might speed things up, but I'm not sure.

**Comment by jfangrad** [comment]
> Sorry, I read this, but I wasn't sure of a way. Source files need to be reparsed each time because they contain a lot of references and aren't easily serializable. There is the incremental program internally in the compiler that could maybe be used in ts-morph and then exposed, but I'm not sure how much it would speed up this scenario.
> 
> If a lot of disk reads are causing trouble then maybe you could have a dedicated worker that caches disk reads and then the other workers provide a custom file system to ts-morph (`new Project{ fileSystem }`) that get files from this worker. It might speed things up, but I'm not sure.

Yeah no worries. In the end it also seemed to be quite memory limited as well. Ie having 8 separate threads each with their own fully parsed tree of a large repo was basically using 30 GB of RAM 😄 . Basically its just not that helpful to split into threads as its just to resource intensive aside from CPU.

**Comment by noqcks** [comment]
> I found an alternative method that sped up the process almost 10x.

Please share 😄 we're also facing these issues in large repos

**Comment by dsherret** [comment]
https://ts-morph.com/manipulation/performance may help
