### ISSUE TITLE
tsconfig changes are not save

### ISSUE THREAD

**Issue by wizardnet972** [dsherret/ts-simple-ast#1308]
**Describe the bug**

Version: 15.1.0

I add `paths` to `tsconfig` and save the project, but `tsconfig` changes are not saved.

**To Reproduce**

```ts
import { Project } from "ts-morph";

const project = new Project({ tsConfigFilePath });
project.resolveSourceFileDependencies();

project.compilerOptions.set({ paths: { '@app/*': ["./src/app*"] } });
project.saveSync();

```

**Expected behavior**

`saveSync` should save the `tsconfig`.

**Comment by dsherret** [comment]
I can understand the confusion here, but ts-morph doesn't provide any functionality for modifying tsconfig.json files. When `project.compilerOptions` is modified, it only does that in memory for that project.

**Comment by wizardnet972** [comment]
@dsherret  Okay, I close this issue. but I think it would be nice if `ts-morph` will be able to save `tsconfig` changes because it's part of the source files changes. and especially because I use auto imports from `ts-morph`.
