### ISSUE TITLE
Denormalize / Fully resolve a type

### ISSUE THREAD

**Issue by alexpineda** [dsherret/ts-simple-ast#1312]
I'm exporting little slices of my types to a type definition to be consumed by plugin authors of my software. I'd like these types to be completely denormalized/fully resolved so I don't have to worry about references or other problems (like some files using node libs).

Ideal API;

```ts
// ... getSourceFiles etc..
node.getFullyResolvedType();
```
Which would transform something like:

```ts
type A = 1;
type B = A;
```

to:
```ts
type A = 1;
type B = 1;
```

at which point I can print out node B to a d.t.s file without worrying about type A being visible or worrying about including it (in case of imports).

**Comment by lazarljubenovic** [comment]
That's not possible in general, e.g. with recursive types. So I doubt there's a pre-made solution for this; you'd have to think about handling these edge cases firstly.

**Comment by alexpineda** [comment]
Alright well I haven't solved it yet as I prefer to use the compiler tools rather than re-implementing a lot of logic. Created to https://github.com/dsherret/ts-morph/issues/1346 be more specific.
