### ISSUE TITLE
Consider depending on `typescript` instead of bundling

### ISSUE THREAD

**Issue by kidonng** [dsherret/ts-simple-ast#1324]
**Is your feature request related to a problem? Please describe.**

Right now `@ts-morph/common` is bundled with `typescript.js`, which comes at a whooping 9 MB size.

**Describe the solution you'd like**

I feel most projects using `ts-morph` are already written in TypeScript, hence has `typescript` in their dependency list. `ts-morph` can depend on `typescript` directly without extra cost most of the time.

**Describe alternatives you've considered**

At least, we can slim down the size a little by minifying `typescript.js`, this proved to save up to 65% space.

**Comment by dsherret** [comment]
Definitely won't do this. It's such a mess having TypeScript as a dependency and actually ts-morph requires less space than depending on both TypeScript and ts-morph.

See https://github.com/dsherret/ts-morph/issues/932#issuecomment-780159410 and https://github.com/dsherret/ts-morph/issues/933 for more details.

**Comment by kidonng** [comment]
Thanks for the context. I see you also mentioned minifying in #932, is that a reasonable improvement to the size?

**Comment by dsherret** [comment]
I decided not to minify because then it makes it harder to debug things in the ts compiler, which can be important when using this library. People can minify the output if they need to after getting the package.
