### ISSUE TITLE
unwrap issue with small file.

### ISSUE THREAD

**Issue by dmeagor** [dsherret/ts-simple-ast#136]
EDIT posted wrong file sorry.  Will close until I can figure out exactly whats happened.

When unwrapping the module from this small file I'm getting the exception below.

NB. It works on the other 800 or so files, so I think this is just some edge case.

```

```

> c:\Users\dmeag\Source\Repos\updatecli\node_modules\ts-simple-ast\dist\manipulation\tree\nodeHandlers\StraightReplacementNodeHandler.js:23
>             throw new Error("Error replacing tree: Should not have new children left over."); // todo: better error message
>             ^
> 
> Error: Error replacing tree: Should not have new children left over.
>     at StraightReplacementNodeHandler.handleNode (c:\Users\dmeag\Source\Repos\updatecli\node_modules\ts-simple-ast\dist\manipulation\tree\nodeHandlers\StraightReplacementNodeHandler.js:23:19)
>     at StraightReplacementNodeHandler.handleNode (c:\Users\dmeag\Source\Repos\updatecli\node_modules\ts-simple-ast\dist\manipulation\tree\nodeHandlers\StraightReplacementNodeHandler.js:19:18)
>     at StraightReplacementNodeHandler.handleNode (c:\Users\dmeag\Source\Repos\updatecli\node_modules\ts-simple-ast\dist\manipulation\tree\nodeHandlers\StraightReplacementNodeHandler.js:19:18)
>     at StraightReplacementNodeHandler.handleNode (c:\Users\dmeag\Source\Repos\updatecli\node_modules\ts-simple-ast\dist\manipulation\tree\nodeHandlers\StraightReplacementNodeHandler.js:19:18)
>     at UnwrapParentHandler.handleNode (c:\Users\dmeag\Source\Repos\updatecli\node_modules\ts-simple-ast\dist\manipulation\tree\nodeHandlers\UnwrapParentHandler.js:20:49)
>     at ParentFinderReplacementNodeHandler.handleNode (c:\Users\dmeag\Source\Repos\updatecli\node_modules\ts-simple-ast\dist\manipulation\tree\nodeHandlers\ParentFinderReplacementNodeHandler.js:19:36)
>     at ParentFinderReplacementNodeHandler.handleNode (c:\Users\dmeag\Source\Repos\updatecli\node_modules\ts-simple-ast\dist\manipulation\tree\nodeHandlers\StraightReplacementNodeHandler.js:19:18)
>     at ParentFinderReplacementNodeHandler.handleNode (c:\Users\dmeag\Source\Repos\updatecli\node_modules\ts-simple-ast\dist\manipulation\tree\nodeHandlers\ParentFinderReplacementNodeHandler.js:22:19)
>     at Object.replaceTreeUnwrappingNode (c:\Users\dmeag\Source\Repos\updatecli\node_modules\ts-simple-ast\dist\manipulation\tree\replaceTreeUnwrappingNode.js:13:33)
>     at Object.unwrapNode (c:\Users\dmeag\Source\Repos\updatecli\node_modules\ts-simple-ast\dist\manipulation\removal\unwrapNode.js:13:12)
>     at NamespaceDeclaration.unwrap (c:\Users\dmeag\Source\Repos\updatecli\node_modules\ts-simple-ast\dist\compiler\base\UnwrappableNode.js:7:28)
>

**Comment by dsherret** [comment]
I should really fix that todo :)

```ts
// todo: better error message
```

Opened #137.
