### ISSUE TITLE
Is it possible to pass dynamic imported `ts` to ts-morph?

### ISSUE THREAD

**Issue by PupilTong** [dsherret/ts-simple-ast#1361]
**Is your feature request related to a problem? Please describe.**

Trying to implement a vscode language extension. In the language-server, the `ts` instance is provided by vscode integrated ts lib.

In general, it is something like this:
```javascript
function toUseTsMorph(ts: typeof import('typescript/lib/tsserverlibrary')){

}
```

**Describe the solution you'd like**

```javascript
function toUseTsMorph(ts: typeof import('typescript/lib/tsserverlibrary')){
  ts.initialize(ts)
}
```
**Describe alternatives you've considered**

I'm trying to use `ts` directly. However I'm stuck by the sourceMap issues. 
In `ts.transform` function, I create some new `ts.node` and append them to a sourceFile. 

However the `node.pos` and `node.end` properties are keeping `-1`. 

I guess the `sourceFile` should be emitted to assign some values to those properties, but the created nodes has no `parent`, which caused an exception in `typescript`

Thank you sooooo much!

**Comment by dsherret** [comment]
No, it's not a supported scenario because it's a huge maintenance burden. I wouldn't recommend using this in a language server because it's not really designed for that.

See https://github.com/dsherret/ts-morph/issues/1324#issuecomment-1264140179 and other previous comments on why.
