### ISSUE TITLE
Improve error message when manipulation throws error

### ISSUE THREAD

**Issue by dsherret** [dsherret/ts-simple-ast#137]
Should say:

1. Source file path.
2. File text (at least of the area that was manipulated)
3. Reason it went wrong.

**Comment by dsherret** [comment]
@spontaliku-softaria yeah, sorry about that. The message is definitely not helpful in this scenario. I am bumping up the priority of this issue.

Does the stack trace say what method being called causes the error happens on (ex. addParameter)? What is probably happening is that maybe a character is being inserted that causes more nodes to be inserted beyond what is expected. At the current moment it's really strict, but I would like to make it more flexible in the future. For example, doing something like `{ name: "Name<T>" }` instead of `{ name: "Name", typeParameters: [{ name: "T" }] }` would cause the above error.

**Comment by spontaliku-softaria** [comment]
@dsherret there was a mistake in my code and sometimes I was generating syntactically incorrect types. Some of them still was in the output, even incorrect, some was giving the error.

I guess it is fine that it's strict, just need better error message.

I fixed my code and everything works now. I can break it again and reproduce the issue if you want particular case where it failed.

**Comment by dsherret** [comment]
@spontaliku-softaria no, that's fine thanks. I know how to reproduce this error in a lot of ways. I will just make this error message better.

I'm glad you were able to find the issue.

**Comment by spontaliku-softaria** [comment]
Btw API is great. Among all AST-powered code generators I've used (acorn, recast, ts-simple-ast), this one is the easiest to use.

**Comment by dsherret** [comment]
@spontaliku-softaria thanks! :) Yeah, I also found everything that existed to be too complicated to make what I wanted to do feasible.
