### ISSUE TITLE
jsx element identifier erroring when using replaceWithText 

### ISSUE THREAD

**Issue by souporserious** [dsherret/ts-simple-ast#1373]
**Describe the bug**

Version: 17.0.1

I'm trying to rename a JSX element identifier and ran into the following issue when doing operations sequentially:

```
ManipulationError: Manipulation error: A syntax error was inserted.
error TS17008: JSX element 'Stack' has no corresponding closing tag.
```

**To Reproduce**

My issue is currently in a private codebase, so I'll work on trying to get reproduction. It does seem intermittent since the following worked on many other files:

```tsx
// node in this case is coming from a ReferencedSymbolEntry on a prop value that I traverse back up to find
const jsxElement = node.getFirstAncestorByKindOrThrow(
  ts.SyntaxKind.JsxElement
)

jsxElement
  .getOpeningElement()
  .getFirstDescendantByKind(ts.SyntaxKind.Identifier)
  .replaceWithText('Stack')

jsxElement
  .getClosingElement()
  .getFirstDescendantByKind(ts.SyntaxKind.Identifier)
  .replaceWithText('Stack')
```

This results in the error above _only for some files_. When reversing the logic and replacing the closing element text first it does work.

**Expected behavior**

I'd expect the order in which calling `replaceWithText` not to matter, but possibly just not understanding what's going on 😇

**Comment by souporserious** [comment]
My bad, I didn't realize `rename` was a thing. Using that instead of `replaceWithText` fixes it! 🎉

**Comment by poteboy** [comment]
Hi @souporserious ,

I have the following code, and I'm encountering this error: `Manipulation error: A syntax error was inserted`. I'm having difficulty in resolving this issue, and I couldn't find the rename method you've mentioned. Could you please guide me on how you fixed this?

Here's the code:
```ts
  if (Node.isJsxOpeningElement(jsxElement)) {
    const jsxElementParent = jsxElement.getParentIfKind(SyntaxKind.JsxElement);
    if (jsxElementParent) {
      const closingElement = jsxElementParent.getClosingElement();
      jsxElement.getTagNameNode().replaceWithText(rawHTMLTag);
      closingElement.getTagNameNode().replaceWithText(rawHTMLTag);
      jsxElement.getSourceFile().save();
    }
  } else if (Node.isJsxSelfClosingElement(jsxElement)) {
    jsxElement.getTagNameNode().replaceWithText(rawHTMLTag);
  }
```

**Comment by souporserious** [comment]
Yeah, definitely! The `rename` method exists on the identifier, here is an example of how you would rename a `div` to `span`:

```ts
const project = new Project({ useInMemoryFileSystem: true })
const sourceFile = project.createSourceFile("App.tsx", `
export default function App() {
  return <div>Hello World</div>
}
`)

sourceFile
  .getFirstDescendantByKindOrThrow(SyntaxKind.JsxElement)
  .getFirstDescendantByKindOrThrow(SyntaxKind.Identifier)
  .rename("span")
```

**Comment by poteboy** [comment]
@souporserious 
It worked! You really saved me there, thank you so much 🙌
