### ISSUE TITLE
JSDoc for "parameters with properties" is not handled well: Main param tag has invalid type expression and property param tags are not included

### ISSUE THREAD

**Issue by zivarah** [dsherret/ts-simple-ast#1384]
**Describe the bug**

Version: 17.0.1

The tags returned by `JSDoc.getTags()` are not an accurate representation of the actual JSDoc when the [Parameters with properties](https://jsdoc.app/tags-param.html#parameters-with-properties) concept is used. I identified two main issues:

1. We only get one tag, for the "parent" param tag. The param tags for the parameter's properties are not returned.
2. The "parent" param tag is corrupt. Its text includes the parameter's properties' tags' text, and the type expression's text is set to all of the properties' tags raw text. 

**To Reproduce**

```js
// test.js

/**
 * Does some stuff
 * @param {string} first First param
 * @param {object} opts The options
 * @param {string} opts.str Some string
 * @param {boolean} opts.bool Some bool
 * @param {string} last Last param
 */
function foo(first, opts, last) {
}
```

```ts
import { Project } from "ts-morph";

const project = new Project();
const sourceFile = project.createSourceFile("test.js", ``);

sourceFile.getFunctions().forEach(f => {
    f.getJsDocs().forEach(doc => {
        doc
            .getTags()
            .filter(AST.Node.isJSDocParameterTag)
            .forEach(tag => {
                console.log(`\r\n=== ${tag.getName()} ===`);
                console.log("tag.getText:");
                console.log(`"${tag.getText()}"`);

                console.log("tag.getTypeExpression().getText():");
                console.log(`"${tag.getTypeExpression()?.getText()}"`);
            });
    });
});

```
**Actual behavior**
This program gives the following output:
```
=== first ===
tag.getText:
"@param {string} first First param
 * "
tag.getTypeExpression().getText():
"{string}"

=== opts ===
tag.getText:
"@param {object} opts The options
 * @param {string} opts.str Some string
 * @param {boolean} opts.bool Some bool
 * "
tag.getTypeExpression().getText():
"@param {string} opts.str Some string
 * @param {boolean} opts.bool Some bool
 * "

=== last ===
tag.getText:
"@param {string} last Last param
 "
tag.getTypeExpression().getText():
"{string}"
```

As you can see, we have no tags returned for `opts.str` and `opts.bool` and the tag for `opts` is corrupt.

The fact that `getText` is returning the following line's opening ` * ` seems odd but not particularly problematic since `getCommentText()` appears to work correctly for all of the tags.

**Expected behavior**
I could see two correct behaviors here:
1. The `opts` tag is some root tag from which you can access the tags for `opts.str` and `opts.bool`
2. `getTags` returns separate tags for `opts.str` and `opts.bool`

In either case, there should be five total well-formed `JSDocTag`s.

**Comment by dsherret** [comment]
The `.getTags()` method only forwards what the compiler does, so I would say this is by design:

![image](https://user-images.githubusercontent.com/1609021/220751627-19bc0341-7825-454b-bd98-a399297205fa.png)

https://ts-ast-viewer.com/#code/PQKhCgAIUgRB7ApgZ0s+BbRaAuBXAMwKhgAEAHAQwCdKNIBvZHagSwDsBzAX0gNerNIAMQFCqtDCUgUadRvABGAK0QBjHL3jkcqACoALbNpyt47ZNNmTGzNly07kAOjuQAypmx2OnKxPkGRXh4ABtESnZHXWdgsI8vSDjQ-zl6JhZfXlDKIQAZXJxIAKloYHACPHYNM3Y+EIAKfkEcABpIE2R2nOYASkZwbiA

**Comment by zivarah** [comment]
Ah - you're totally right. I did not realize that the JSDocTypeExpression could be a JSDocTypeLiteral (which has a getPropertyTags API).

An updated program that uses this to correctly identify the properties would look like the following (though note that this may not be complete):

```typescript
function logTag(tag: AST.JSDocTag): void {
		const name =
			AST.Node.isJSDocPropertyLikeTag(tag) || AST.Node.isJSDocPropertyLikeTag(tag) ? tag.getName() : tag.getTagName();
		console.log(`\r\n=== ${name} ===`);
		console.log("tag.getText:");
		console.log(`"${tag.getText()}"`);

		if (
			AST.Node.isJSDocTypeExpressionableTag(tag) ||
			AST.Node.isJSDocTypeTag(tag) ||
			AST.Node.isJSDocPropertyLikeTag(tag)
		) {
			const typeExpression = tag.getTypeExpression();
			const typeNode = typeExpression.getTypeNode();
			if (AST.Node.isJSDocTypeLiteral(typeNode)) {
				typeNode.getPropertyTags().forEach(logTag);
			} else {
				console.log("tag.getTypeExpression().getText():");
				console.log(`"${tag.getTypeExpression().getText()}"`);
			}
		}
	}

	const sourceFile = new AST.Project({ compilerOptions: { allowJs: true } }).addSourceFileAtPath(
		__dirname + "\\MyFile.js",
	);
	sourceFile.getFunctions().forEach(f => {
		f.getJsDocs()
			.flatMap(doc => doc.getTags())
			.forEach(logTag);
	});
```

This outputs:

```
=== first ===
tag.getText:
"@param {string} first First param
 * "
tag.getTypeExpression().getText():
"{string}"

=== opts ===
tag.getText:
"@param {object} opts The options
 * @param {string} opts.str Some string
 * @param {boolean} opts.bool Some bool
 * "

=== opts.str ===
tag.getText:
"@param {string} opts.str Some string
 * "
tag.getTypeExpression().getText():
"{string}"

=== opts.bool ===
tag.getText:
"@param {boolean} opts.bool Some bool
 * "
tag.getTypeExpression().getText():
"{boolean}"

=== last ===
tag.getText:
"@param {string} last Last param
 "
tag.getTypeExpression().getText():
"{string}"
```

@dsherret Apologies for the false report, I should have double checked the AST before opening this.
