### ISSUE TITLE
`transform` looses `StringLiteral` nodes

### ISSUE THREAD

**Issue by ivanhofer** [dsherret/ts-simple-ast#1416]
**Describe the bug**

Version: 18.0.0

I want to replace a node with another node. As far as I understand thsi should be done using the `transform` method. It works as expected except when the replacement node contains `StringLiteral`s. In that case those literals get lost and are missing from the output.

**To Reproduce**

Replace a node containing a `StringLiteral` using the `transform` method.

```ts
import { Project, Node } from "ts-morph"

const printCode = (node: Node) => node.print().trim()

const parseCode = (code: string) => new Project()
	.createSourceFile("test.ts", code, { overwrite: true })
	.getStatement(Node.isVariableStatement)
	?.getDeclarationList()
	.getDeclarations()[0]
	.getInitializer()!

const toReplace = parseCode('const x = 1')
const parent = toReplace.getSourceFile()!

const replaceWith = parseCode('const y = console.log("test")')
toReplace.transform(() => replaceWith.compilerNode)

console.log('expected:    ', 'const x = console.log("test")');
console.log('actual:      ', printCode(parent));
```

The output of the code is:
```
expected:    const x = console.log("test")
actual:      const x = console.log()
```

**Expected behavior**

I would expect `transform` to replace the node with all it's children correctly.

**Comment by ivanhofer** [comment]
The issue comes from this line: https://github.com/dsherret/ts-morph/blob/46e50b010a7d2a892b78f4c2e906b908b45a619b/packages/ts-morph/src/compiler/ast/common/Node.ts#L1568

When changing `compilerSourceFile` to `transform.compilerNode.getSourceFile()` it seems to work:

`finalText += printer.printNode(common.ts.EmitHint.Unspecified, transform.compilerNode, transform.compilerNode.getSourceFile());`

I don't fully understand the codebase. I'm not sure if this has other implications when changing it.

**Comment by dsherret** [comment]
> ```ts
> const replaceWith = parseCode('const y = console.log("test")')
> toReplace.transform(() => replaceWith.compilerNode)
> ```

This will cause a lot of issues in TypeScript and is not the intended way to use the API. I don't recommend mixing two nodes from different source files. Instead use the factory functions, which don't have a `sourceFile` parent.

For replacing a node with text, use the `replaceWith` method:

```ts
toReplace.replaceWith('const y = console.log("test")');
```

**Comment by dsherret** [comment]
I had forgot how this code works. Looking into it more now.

**Comment by ivanhofer** [comment]
> For replacing a node with text, use the `replaceWith` method

Ah thanks. Then I will replace it with the node's string representation.
