### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by vogloblinsky** [dsherret/ts-simple-ast#143]
Hi,

Is it possible to have a CHANGELOG for this project ?

Searching for breaking changes between versions is a bit difficult.

Thanks.

**Comment by dsherret** [comment]
Yes, I was thinking about starting to do that last week now that more people are using the project, but never got around to it. I'll start doing that in upcoming releases.

By the way, do you know if referencing this library with a `^` (ex. `^0.97.0 `) in *package.json* is safe to do while the major version number is 0? Or will npm automatically use the latest version? I would think so, but I'm not sure. I searched a bit online, but couldn't find anything. I will strictly keep with semantic versioning after deciding to move to version 1, but in the meantime there could be some breaking changes between minor revisions while the major version is 0.

**Comment by dsherret** [comment]
CHANGELOG.md is added. It will be maintained from version 0.97.1 onwards.

**Comment by vogloblinsky** [comment]
Thanks

**Comment by dsherret** [comment]
FYI, I have switched the library over to semantic versioning. I don't expect too many breaking changes, but I'll just liberally bump the major revision number when necessary.

**Comment by ruscon** [comment]
@dsherret Hey, it will be nice if you use [github semantic releases](https://github.com/semantic-release/github)

**Comment by karlhorky** [comment]
> I'll just liberally bump the major revision number when necessary

@dsherret I was recently looking at [the changelog for `ts-morph@27.0.0`](https://github.com/dsherret/ts-morph/releases/tag/27.0.0) and I didn't see any explicitly breaking changes there:

> ## What's Changed
> 
> - perf: switch to tinyglobby by benmccann in https://github.com/dsherret/ts-morph/pull/1635
> - fix: re-export StandardizedFilePath from @ts-morph/common by kronodeus in https://github.com/dsherret/ts-morph/pull/1637
> - chore: fix ci by dsherret in https://github.com/dsherret/ts-morph/pull/1645
> - feat: TypeChecker - add getAwaitedType by JHawk0224 in https://github.com/dsherret/ts-morph/pull/1643
> - feat: TypeScript 5.9 by dsherret in https://github.com/dsherret/ts-morph/pull/1646
> - feat: wrap OptionalTypeNode by dsherret in https://github.com/dsherret/ts-morph/pull/1647
> - feat: wrap JSDocImportTag by dsherret in https://github.com/dsherret/ts-morph/pull/1648
> - fix: remove invalid sourceMappingURL from build output by dsherret in https://github.com/dsherret/ts-morph/pull/1649
> - feat: ability to add and remove the defer keyword in imports by dsherret in https://github.com/dsherret/ts-morph/pull/1651

To make the upgrade process easier for consumers, could you mark the breaking changes which appear in major version bumps? (maybe it's about TS 5.9?)

Or alternatively, if there are some major version bumps where there are no perceived breaking changes (eg. majors are bumped via vibes), add a short note in each of those majors explaining this rationale?
