### ISSUE TITLE
InterfaceDeclarationStructure has no get or set accessors

### ISSUE THREAD

**Issue by ajvincent** [dsherret/ts-simple-ast#1431]
**Describe the bug**

Version: 19.0.0

**To Reproduce**

```ts
import ts from "ts-morph";
const TSC_CONFIG: ts.ProjectOptions = {
  "compilerOptions": {
    "lib": ["es2022"],
    "module": ts.ModuleKind.ESNext,
    "target": ts.ScriptTarget.ESNext,
    "moduleResolution": ts.ModuleResolutionKind.NodeNext,
  },
  skipAddingFilesFromTsConfig: true,
  useInMemoryFileSystem: true,
};

const project = new ts.Project(TSC_CONFIG);

const sourceFile = project.createSourceFile("file.ts", `
interface Foo {
  get A(): string;
}
`.trim() + "\n");

const decl = sourceFile.getInterfaceOrThrow("Foo");
const structure = decl.getStructure();
console.log(JSON.stringify(structure, null, 2));
```

```json
{
  "name": "Foo",
  "isExported": false,
  "isDefaultExport": false,
  "hasDeclareKeyword": false,
  "docs": [],
  "typeParameters": [],
  "extends": [],
  "callSignatures": [],
  "constructSignatures": [],
  "indexSignatures": [],
  "methods": [],
  "properties": [],
  "kind": 19
}

```

[ts-ast-viewer link](https://ts-ast-viewer.com/#code/JYOwLgpgTgZghgYwgAgGIHt3IN4ChkHIDmEYyAggBQCUAXMgM5hShEDcuAvkA)
**Expected behavior**

I wanted to see the get accessor for `A` in the output structure.

I believe the fault is in `TypeElementMemberedNodeStructure`.  It lists methods and properties but not get accessors or set accessors.

**Comment by ajvincent** [comment]
I can already see there would be a lot to build out.

- [x] Updating `StructureKind`
- [x] `GetAccessorSignatureStructure`, extrapolated from `GetAccessorDeclarationStructure`
- [x] `SetAccessorSignatureStructure`, extrapolated from `SetAccessorDeclarationStructure`
- [ ] Implementing `GetAccessorSignatureNode` with tests
- [ ] Implementing `SetAccessorSignatureNode` with tests
- [ ] Static methods `Node.isGetAccessorSignature()`, `Node.isSetAccessorSignature()`
- [ ] Modifying `TypeElementMemberedNodeStructure` to include `getAccessors` and `setAccessors` properties
- [ ] Adding `GetAccessorSignatureStructure` and `SetAccessorSignatureStructure` to `TypeElementMemberStructures`
- [ ] Updates to the `TypeElementMemberedNode` interface to reach accessors from a `Node`
- [ ] Implementing fixes to `InterfaceDeclaration::getStructure()`
- [ ] Tests for the same
- [ ] Updates to `forEachStructureChild` and `Structure`
- [ ] Updating an `InterfaceDeclaration` from a structure having accessors
- [ ] Tests for the same
- [ ] Documentation in `docs/details/interfaces.md`

I think briefly about taking this on, but this would be a big chunk of time when I don't have much to spare.  I'm writing this comment as a brainstorm attempt at a roadmap, and I'm wondering what I'm missing.

**Comment by forivall** [comment]
I have a need for this, so I might collaborate with you on this; i'll let you know if I start on it @ajvincent

**Comment by ajvincent** [comment]
@forivall Sweet.  It's always nice to have a motivated collaborator.

I would be quite happy if you took the lead on this.  For me, this is more of an annoyance / future need rather than an immediate need.   I do have a current clean fork of this repository already, and branches are cheap... so I could invite you as a collaborator there if you'd prefer to use my fork.

I did discover one missed part in my checklist earlier, a few days ago:

- [ ] [`Writers.objectType`](https://github.com/dsherret/ts-morph/blob/382f0c8a9d53326bc295111d722973bbd428d805/packages/ts-morph/src/structurePrinters/Writers.ts#L55) support, and tests.  (See [`TypeElementMemberedNodeStructurePrinter.ts`](https://github.com/dsherret/ts-morph/blob/latest/packages/ts-morph/src/structurePrinters/interface/TypeElementMemberedNodeStructurePrinter.ts#L7))

Of course, I would still like to get a review of the roadmap to see what else we missed before we dive in too deep.

**Comment by ajvincent** [comment]
@forivall https://github.com/dsherret/ts-morph/pull/1450/commits/453a86a035317a44fd9e600b0dfd812ee3dc08c5 might provide some useful hints too.  

@dsherret thanks for the RestTypeNode fix, and I'm wondering if you're going to beat us to the punch on this one... or if you want to tell us what we're missing.

**Comment by ajvincent** [comment]
@forivall I might start on this very soon.  That "future need" is getting close.  My need is for a "type-to-class" functionality (more accurately a "membered-type-to-class"), and I'm envisioning having the getters and setters defined on the interface before I start running.  This would be nicer than modifying the type inside the class builder.

**Comment by ajvincent** [comment]
@dsherret I am formally asking for a design review per [CONTRIBUTING.md](https://github.com/dsherret/ts-morph/blob/latest/CONTRIBUTING.md).

If we do not have enough details here for a proper design, please say so and point me to a good example design you've approved in the past.  I want to move forward as soon as practical.

**Comment by dsherret** [comment]
Adding this sounds good! I think it should be fairly straightforward, but a bit of work.

**Comment by ajvincent** [comment]
@forivall https://github.com/ajvincent/ts-morph/tree/interface-getters-setters just starting out.

**Comment by ajvincent** [comment]
I've just hit the first of probably many stumbling blocks.  (I've been busy the last few weeks.)  Specifically, I'm looking at building  `packages/ts-morph/src/compiler/ast/interface/GetAccessorSignature.ts`.  I'm trying to take inspiration from [PropertySignature.ts](https://github.com/dsherret/ts-morph/blob/latest/packages/ts-morph/src/compiler/ast/interface/PropertySignature.ts).

I started by trying to figure out what I need to add to [`TypeElementMemberedNode.ts`](https://github.com/dsherret/ts-morph/blob/latest/packages/ts-morph/src/compiler/ast/base/TypeElementMemberedNode.ts) to implement a `getGetAccessorSignatures()` method.  I have to use a `SyntaxKind` that already exists.

The stumbling block is the `SyntaxKind` enum.  I assumed, incorrectly, the get accessors of interfaces would have a different `SyntaxKind` than those of classes.  (Because both `SyntaxKind.PropertySignature` and `SyntaxKind.PropertyDeclaration` exist.)  Nope, they're both `SyntaxKind.GetAccessor`.

So I end up with:

```typescript
    getGetAccessorSignatures() /* : GetAccessorDeclaration[] */{
      return this.compilerNode.members.filter(m => m.kind === SyntaxKind.GetAccessor)
        .map(m => this._getNodeFromCompilerNode(m as ts.GetAccessorDeclaration))
    }
```

[`GetAccessorDeclaration` already exists.](https://github.com/dsherret/ts-morph/blob/latest/packages/ts-morph/src/compiler/ast/class/GetAccessorDeclaration.ts).  Great!  Except for that "you can't have statements in an interface" part.

So if I can reuse the existing `GetAccessorDeclaration` class, then maybe this is less work than I thought, but it also means a design rethink.

@dsherret advice please?

**Comment by dsherret** [comment]
@ajvincent would you be able to open a PR with what you've done so far? I'm going to do a major release of ts-morph this weekend probably and can finish this up in case it's not done by then.

It should use GetAccessorDeclaration (see how they're the same [here](https://ts-ast-viewer.com/#code/JYOwLgpgTgZghgYwgAgCoQM5mQbwFDKHIDmE2kWAFAJQBcyWUoxA3HgL554IA2cGGNJmz4iJMsgpga9Rs1wEindkA)) and not a new node type. GetAccessorDeclaration already has an optional body (it's a [BodyableNode](https://github.com/dsherret/ts-morph/blob/a90dc9118166ec484ea486a9d952c08d761dc6bc/packages/ts-morph/src/compiler/ast/class/GetAccessorDeclaration.ts#L14C72-L14C84) and not a BodiedNode). Also see https://github.com/dsherret/ts-morph/blob/a90dc9118166ec484ea486a9d952c08d761dc6bc/packages/ts-morph/src/structurePrinters/class/GetAccessorDeclarationStructurePrinter.ts#L28 (probably that should be updated to always write that when writing in an interface)

Thanks for working on this!

**Comment by ajvincent** [comment]
You are most welcome, though I think you'll find I didn't get very deep into this - and I wish I had.  I'm pretty good about writing tests and documentation... and I'd be happy to write a follow-up PR for those purposes.

**Comment by ajvincent** [comment]
@dsherret where do we stand on this?  I've been battling an illness this week, though it seems to be fading.  I'm willing to pick this up again so you can ship the next version of ts-morph without it, if you so desire.

**Comment by dsherret** [comment]
@ajvincent I'll finish it up right now. I was too busy throughout the week to do it. Hope you feel better soon!
