### ISSUE TITLE
Seemingly one-character emojis (in source) get counted as two characters in SourceFile.getFullText()

### ISSUE THREAD

**Issue by fuhrmanator** [dsherret/ts-simple-ast#1454]
**One character emojis (in source) get counted as two characters in SourceFile.getFullText()**

Version: 19.0.0

Some source code can contain emojis, such as 💷, e.g., https://github.com/Chuzzy/Emojiopoly/blob/223e031c0f1fcee9ca98aa5cbcbf93ffd5f95715/src/monopoly/MonopolyGame.ts#L83

In an editor, the emoji above is one character. However, when ts-morph calculates positions of e.g., variables, inside `SourceFile.getFullText()`, the emoji above is counted as **two** characters. In my case, I'm using this information in another environment that doesn't count the emojis as two characters, but as one (as in the text editor). 

**To Reproduce**

Here's a minimal program:

```typescript
// emojiBug.ts
import { Project } from "ts-morph";

const project = new Project();

project.createSourceFile("simple.ts",
   `let a = "💷", b = 5;`);
// dump out each character in the file to the console
const sourceFile = project.getSourceFileOrThrow("simple.ts");
const text = sourceFile.getFullText();
for (let i = 0; i < text.length; i++) {
    console.log(i + ": " + text[i]);
}

// get the starting character of the source text for the variable 'a'
const variableA = sourceFile.getVariableDeclarationOrThrow("a");
const startA = variableA.getStart();
console.log("a's start: " + startA); // 4 (0-based, cursor after the 'a')

// get the starting character of the source text for the variable 'b'
const variableB = sourceFile.getVariableDeclarationOrThrow("b");
const startB = variableB.getStart();
console.log("b's start: " + startB); // 13 (0-based, cursor after the 'b')
```

The output shows 💷 is character 9 and 10 (two characters and not one):

```terminal
$ ts-node emojiBug.ts 
0: l
1: e
2: t
3:
4: a
5:
6: =
7:
8: "
9: �
10: �
11: "
12: ,
13:
14: b
15:
16: =
17:
18: 5
19: ;
a's start: 4
b's start: 14
```

**Expected behavior**

I'd expect b's start to be 13 -- since unicode characters are treated as one character and not two. This is a problem for me in other software that opens the source file and doesn't count the emoji here as two characters.

**Comment by fuhrmanator** [comment]
OK, I discovered this problem of Grapheme Splitting in JavaScript. https://github.com/orling/grapheme-splitter -- so maybe this is more a feature-request to support that for code that has multi-character graphemes.

**Comment by dsherret** [comment]
`getStart()` calls a typescript compiler api method, so ts-morph just forwards the result.

**Comment by fuhrmanator** [comment]
Yes, definitely not a bug in ts-morph. For people who want the gory details: https://stackoverflow.com/questions/3744721/javascript-strings-outside-of-the-bmp

Closing this, since it's documented.
