### ISSUE TITLE
Question: Is it possible to have custom JSDoc tags?

### ISSUE THREAD

**Issue by tpluscode** [dsherret/ts-simple-ast#1496]
I would like to add a custom JSDoc tag to our functions which has some structure. We do a lot of streams, so something like below would annotate the expected in/out chunks

```
* @in {string}
* @out {Record<string, Foobar>}
```

I see that these will return `JSDocUnknownTag`. I would like to have the contents inside braces interpreted similarly to `@returns` tag.

**Comment by JulianCataldo** [comment]
Suggestion: https://www.npmjs.com/package/comment-parser
TS doesn't handle custom JSDocs.

See also: https://github.com/shoelace-style/shoelace/blob/83fe1ff28e88b1982b528161bf8215d61b4f4592/custom-elements-manifest.config.js#L96

**Comment by tpluscode** [comment]
So the JSDoc structure comes directly from TS API and ts-morph cannot extend it?

I think I should close the issue then. Nothing to do here. Thank you
