### ISSUE TITLE
How to add an empty line to a SourceFile at certain position?

### ISSUE THREAD

**Issue by Maximaximum** [dsherret/ts-simple-ast#151]
It would be great to have a possibility to add an empty line after a certain node (or at a certain position?).

For instance, I use to add an empty line after all of my `import` declarations before the actual code.

Something like this would be cool:
```
const file: SourceFile;
file.addNewLine(importDeclaration.getEnd());
```

Maybe there is already a way to do this, but I could not find it.

**Comment by Maximaximum** [comment]
Needless to say, `addNewLine()` should respect the `newLineKind` settings

**Comment by dsherret** [comment]
I didn't test this, but it might be possible by doing:

```typescript
file.insertStatements(importDeclaration.getChildIndex() + 1, writer => writer.blankLine());
```

I agree though that a general way to add a blank line at a specified position would be useful.

**Comment by Maximaximum** [comment]
I've tried the code sample you provided, but it does not seem to add a new line for some reason.

**Comment by Maximaximum** [comment]
Double-checked and found out that the problem was that I was calling `this.sourceFile.formatText();` after adding the lines, so all the empty lines got removed. Opened a bug: https://github.com/dsherret/ts-simple-ast/issues/157
