### ISSUE TITLE
Different `typescript` module uncompatible with original `typescript`

### ISSUE THREAD

**Issue by phpcoder2022** [dsherret/ts-simple-ast#1534]
Author of `tsuml2` set your package `ts-morph` in dependencies. Uml diagrams draw with wrong class properties types.

Versions:

- @ts-morph/common: 0.20.0
- ts-morph: 19.0.0
- tsuml2: 0.16.1

**To Reproduce**

1. Parse any typescript class contains properties with modifier.
2. Call `getCombinedModifierFlags(node)` from you `typescript` file and original `typescript` module.
3. See that results are different.

**Expected behavior**

Its are equal.

You wrote in description of package:

> Please do not depend on this library!

Thus uncompability with original `typescript` is error.

**Comment by dsherret** [comment]
I don't understand the issue body, but I'll assume based on the title. ts-morph is not compatible with multiple typescript versions. If using typescript, use the ts export from ts-morph:

```ts
import { ts } from "ts-morph"
```

**Comment by dsherret** [comment]
Just re-read the issue and yeah this is expected behaviour because typescript often has breaking changes in even patch releases. Please only depend on the typescript from ts-morph if using ts-morph

https://github.com/dsherret/ts-morph/issues/1324#issuecomment-1264140179

**Comment by phpcoder2022** [comment]
Okay, write this to README, please. I will write to tsuml2 author.
