### ISSUE TITLE
Security Issue: Transitive Dependency Braces 3.0.2

### ISSUE THREAD

**Issue by tomfrenken** [dsherret/ts-simple-ast#1535]
**Describe the bug**

Version: 22.0.0

Hey all,

Our pipeline is failing due to a security vulnerability in one of your transitive dependencies, `braces` version `3.0.2`.
Could you please resolve the issue?

**Comment by tomfrenken** [comment]
Dependency tree for reference:

![image](https://github.com/dsherret/ts-morph/assets/54979414/4130a200-b391-4295-9eae-8f7bc0d66838)

**Comment by dsherret** [comment]
Can you provide more details? Does purging your lockfile to get braces 3.0.3 solve the issue?

**Comment by dsherret** [comment]
> The NPM package braces fails to limit the number of characters it can handle, which could lead to Memory Exhaustion. In lib/parse.js, if a malicious user sends "imbalanced braces" as input, the parsing will enter a loop, which will cause the program to start allocating heap memory without freeing it at any moment of the loop. Eventually, the JavaScript heap limit is reached, and the program will crash.

Ah, yeah just bump it in your project to 3.0.3
