### ISSUE TITLE
Support for EditorConfig settings

### ISSUE THREAD

**Issue by Maximaximum** [dsherret/ts-simple-ast#155]
It would be awesome if `ts-simple-ast` supported all of the `.editorconfig` settings: http://editorconfig.org/#file-format-details

Most of the settings are already supported (it's not a problem to manually read the `.editorconfig` file and provide the settings to the `Ast` constructor). 

But there is still no way to use `insert_final_newline` setting. (am I missing something?)

**Comment by dsherret** [comment]
I think it's not worth bringing this into the library, but yes, it would be nice to also add:

* `trim_trailing_whitespace`
* `insert_final_newline`

I'd need to finish my refactoring planned in #133 for this to be feasible.

**Comment by Maximaximum** [comment]
The full editorconfig support (including parsing the `.editorconfig file`) could be easily added via https://github.com/vvakame/typescript-formatter library. It supports parsing all of the different config files that might be relevant to a typescript file (like tslint.json, tsconfig.json, .editorconfig etc) and aggregates all the formatting options into a single data structure.

**Comment by dsherret** [comment]
Not going to add support for this. I recommend people parse editor config files themselves and then pass the options into the [manipulation settings](https://dsherret.github.io/ts-simple-ast/manipulation/settings). I will be adding a `trimTrailingWhitespace` option to `FormatCodeSettings` (ex. `sourceFile.formatText({ trimTrailingWhitespace: true })`) in #465 (a `ensureNewLineAtEndOfFile` already exists).

Alternatively people can pass the source file texts through a code formatter like tsfmt or prettier.

**Comment by maxgalbu** [comment]
I'm doing something like this, for indentation and new line kind:

```ts
import { IndentationText, NewLineKind, Project } from "ts-morph";
import { parse as parseEditorConfig } from "editorconfig";

const indentConfig = await parseEditorConfig(__dirname + "/.editorconfig");

let indentationText;
if (indentConfig.indent_style === "space" && indentConfig.indent_size === 2) {
    indentationText = IndentationText.TwoSpaces;
} else if (indentConfig.indent_style === "space" && indentConfig.indent_size === 4) {
    indentationText = IndentationText.FourSpaces;
} else if (indentConfig.indent_style === "tab") {
    indentationText = IndentationText.Tab;
}

let newLineKind;
if (indentConfig.end_of_line === "lf") {
    newLineKind = NewLineKind.LineFeed;
} else if (indentConfig.end_of_line === "crlf") {
    newLineKind = NewLineKind.CarriageReturnLineFeed;
}

const project = new Project({
    //other config values 

    manipulationSettings: {
        indentationText: indentationText,
        newLineKind: newLineKind,
    },
});
```

Other stuff is not supported like OP said
