### ISSUE TITLE
Need documentation for working with positions

### ISSUE THREAD

**Issue by Maximaximum** [dsherret/ts-simple-ast#156]
`SourceFile.getPos()`, `SourceFile.getStartLinePos()`, `SourceFile.getEnd()` - what do all these exactly return?

When I try this code `sourceFile.insertStatements(sourceFile.getEnd());`, I get an `Invalid index: The max index is 39, but 2173 was specified.` error. So what is the meaning of the parameter this function expects?

I assumed that all these positions are compatible, but it seems they are not?

**Comment by dsherret** [comment]
Mostly all the add/insert methods take an index (not a position). The exception is insertText and replaceText because those allow you to insert or replace text at any position within the file.

You would want to do: `sourceFile.insertStatements(sourceFile.getStatements().length, "codeGoesHere;");`

I can add more documentation around `pos`, `end`, `start`, etc. though.

**Comment by dsherret** [comment]
Sidenote: Perhaps `insertText` and `replaceText` should be renamed `insertTextAtPos` and `replaceTextAtPos`. I will open an issue for that later.

**Comment by Maximaximum** [comment]
Oh, I see! Position means index among the statements, not a character position in the file. Indeed, this should be documented so that other can easily find this out.

Thanks!

**Comment by dsherret** [comment]
@Maximaximum no, position (ex. getPos(), getEnd()) means a character position in the file. The index parameter in this case means the index among the children. I guess that's confusing. I will change the `index` parameter to be `childIndex` in all these cases.

**Comment by Maximaximum** [comment]
No, I think `index` is fine, but it would rather be helpful to clearly state the meaning of the parameters in the method documentation comments.

**Comment by dsherret** [comment]
I was recently reading/skimming a few chapters about comments from a book and it made me realize I don't do documentation comments well. I've made a few improvements, but this will be part of an ongoing effort to. I'll improve the comments over time. Closing this.
