### ISSUE TITLE
Check out tree-sitter

### ISSUE THREAD

**Issue by kibiz0r** [dsherret/ts-simple-ast#1571]
I just came across this project and immediately thought of ts-morph. I'm sure it would be a huge effort to switch away from tsc, but just in case you're interested in swapping it out someday: https://github.com/tree-sitter/tree-sitter-typescript

**Comment by dsherret** [comment]
> I'm sure it would be a huge effort to switch away from tsc

Thanks, but a big benefit to using typescript is having the type checker.

**Comment by kibiz0r** [comment]
Fair enough. Thanks for your work on ts-morph btw! It's a big help!
