### ISSUE TITLE
Any statements added after SourceFile.formatText() do not actually get added

### ISSUE THREAD

**Issue by Maximaximum** [dsherret/ts-simple-ast#158]
When I add any statements **after** calling `formatText()`, they don't get added to the output text file:
```
    exportsFile.formatText();
    exportsFile.addStatements(writer => writer.newLine().newLine().writeLine('something();'));
    this.ast.saveUnsavedSourceFilesSync();
```

No newlines, no `something();` statement. If I remove the `    exportsFile.formatText();`, everything is ok.

**Comment by dsherret** [comment]
Fixed in v2.0.0.
