### ISSUE TITLE
NotImplementedError: Unexpected! Inserting syntax kind of ExportAssignment, but FunctionDeclaration was inserted.

### ISSUE THREAD

**Issue by bennycode** [dsherret/ts-simple-ast#1586]
**Describe the bug**

Version: 24.0.0

I cannot default export a function declaration.

**To Reproduce**

The following default export is allowed in JavaScript/TypeScript ([see here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export#syntax)):

```ts
export default function functionName() {}
```  

I want to insert such default export with a function declaration using `insertExportAssignment`:

```ts
sourceFile.insertExportAssignment(position, {
  expression: 'function functionName() {}',
  isExportEquals: false,
});
```

Unfortunately, it makes my code crash:

> NotImplementedError: Unexpected! Inserting syntax kind of ExportAssignment, but FunctionDeclaration was inserted.

I have to work around this error by using:

```ts
sourceFile.insertExportAssignment(position, {
  expression: 'functionName() {}',
  isExportEquals: false,
});
``` 

Or by doing:

```ts
sourceFile.insertStatements(position, 'export default function functionName() {}');
```
**Expected behavior**

Not crashing when using:

```ts
sourceFile.insertExportAssignment(position, {
  expression: 'function functionName() {}',
  isExportEquals: false,
});
```

**Comment by dsherret** [comment]
In this case, you'll want to use `addFunction` with `isDefaultExport: true`.

Function declarations with a default export and export assignments are represented differently in the typescript compiler:

1. https://ts-ast-viewer.com/#code/KYDwDg9gTgLgBAE2AMwIYFcA28bAM4wDcQA
2. https://ts-ast-viewer.com/#code/KYDwDg9gTgLgBAE2AMwIYFcA29noHYDGMAlhHnKKgLZibAAUAlHAN4C+QA
