### ISSUE TITLE
Is ts-morph suitable to replace @babel/types + @babel/generator combo?

### ISSUE THREAD

**Issue by shinebayar-g** [dsherret/ts-simple-ast#1588]
It seems ts-morph is easier to work with and first class typescript support makes it favorable over `@babel/types` + `@babel/generator` combo that I was using.

My use case is purely code generation, not really focused on code refactoring. And the documentation doesn't cover that much around code generation part. Would you recommend ts-morph for pure code generation tasks? If so, could you add some documentation to the website as well?

Thanks.

**Comment by shinebayar-g** [comment]
Based on my experience, it seems using `sourceFile.addX` method is pretty slow. Swapping it with `sourceFile.addXes` method significantly boosted the performance as [mentioned in the docs](https://ts-morph.com/manipulation/performance). Without it, it was outright impossible to generate code after a few hundred thousand of lines. ts-morph got stuck without any feedback.

Surprisingly using `.forget()` method made it a few seconds slower somehow.

Overall, it was a great experience.

**Comment by dsherret** [comment]
For just code generation, I'd recommend using https://github.com/dsherret/code-block-writer, but that said, there are some structure printers internally in ts-morph that might be nice to expose sometime: https://github.com/dsherret/ts-morph/tree/latest/packages/ts-morph/src/structurePrinters (https://github.com/dsherret/ts-morph/blob/latest/packages/ts-morph/src/factories/StructurePrinterFactory.ts)

**Comment by shinebayar-g** [comment]
Nice. It feels like `ts-morph` is already well positioned to replace @babel/generator with those additions.
