### ISSUE TITLE
getType of method's parameter returns ANY (for union or intersection types)

### ISSUE THREAD

**Issue by lrondanini** [dsherret/ts-simple-ast#1589]
Hey guys,

I'm quite new to ts-morph and possibly I may have missed something (apologies if this is the case) but I cannot find a way to parse the type of a parameter using ts-morph.

To be clear, the problem shows only if a function has a parameter of type union or intersection. For example, I have a class like this:

```js
class MyClass {

    SomeFunction(param: string[] & MyTpe<5>) {
    }

}
```

while parsing I get this output (see comments):

```js
classDef.getMethods().forEach((method) => {
   method.getParameters().forEach((param) => {
          console.log(param.getType().getText()); // WRONG: prints any
          console.log(param.getType().isIntersection()); // WRONG: prints false
          console.log(param.getTypeNode().getText()); // CORRECT: prints string[] & MyTpe<5>
          console.log(param.getTypeNode().getType().getText()); // WRONG: prints "any"
   });
})
```

Any idea?

I tried to parse param.getTypeNode() but it does not have the same functionalities as param.getType(). Any suggestion?

If this is a bug, I'm willing to do some work and fix it

Thanks

**Comment by lrondanini** [comment]
found this workaround:

    const type = typeChecker.getTypeAtLocation(param);

this way everything works

**Comment by dsherret** [comment]
That workaround is what ts-morph does internally. Check what's in `project.getPreEmitDiagnostics()`, there's probably an error.
