### ISSUE TITLE
Add SemicolonToken

### ISSUE THREAD

**Issue by gregjacobs** [dsherret/ts-simple-ast#173]
Hey David, can you add SemicolonToken as a node type? Seems walking through the children of an `ExpressionStatement` can give me this guy. Would be good to have on the TypeGuards.

Thanks!

**Comment by dsherret** [comment]
Within the compiler, there's not a node specifically for SemicolonToken. In this case, I added a type guard for SemiColonToken, but it still just returns a plain Node.

**Comment by gregjacobs** [comment]
Ah, interesting. Ok, thanks then!
