### ISSUE TITLE
Add ExportAssignment

### ISSUE THREAD

**Issue by dsherret** [dsherret/ts-simple-ast#175]
As title.

**Comment by dsherret** [comment]
This is a breaking change because `.getExports()` on source file is going to be renamed to `getExportDeclarations()`

**Comment by gp187** [comment]
`.getExportDeclarations()` doesn't return anything now
while `getExportedDeclarations()` returns correctly by `Node`s

**Comment by dsherret** [comment]
@gp187 can you show an example of it not returning? The unit tests show it returning export declarations (ex. `export * from "./file"; export { somethingElse } from "./otherFile";`)
