### ISSUE TITLE
Support AST transformations / node factories

### ISSUE THREAD

**Issue by gregjacobs** [dsherret/ts-simple-ast#176]
See discussion below

**Comment by gregjacobs** [comment]
By the way, is there any way to manipulate the underlying compiler nodes directly, and tell `ts-simple-ast` about it?

I realized I could replace the Identifier node with a `PropertyAccessExpression` by calling:

```ts
compilerNode.expression = ts.createPropertyAccess( ts.createThis(), 'myProp' );
```

But when I go to output the source using `sourceFile.getFullText()` it seems that the update didn't take place.

**Comment by dsherret** [comment]
Hey Greg, I'll take a look and see. This looks like it would be useful to have.

Regarding using the `ts.createX` methods, those methods only change the tree and not the underlying source file text. For example, try this out:

```ts
// untested, but from my memory I believe it works this way
compilerNode.expression = ts.createPropertyAccess( ts.createThis(), 'myProp' );
compilerNode.getText(); // won't have this.myProp
compilerNode.getSourceFile().getFullText(); // won't have this.myProp
```

I'm not entirely sure how to propagate that change back up to the parent source file's text or the other node's properties (ex. pos and end) based on the changes. Do you know a way? I know they do this with [code fixes](https://github.com/Microsoft/TypeScript/blob/19ea189b429e426bff88753249745f4292b04343/src/services/codefixes/fixForgottenThisPropertyAccess.ts). If we figure that out, then it would make sense to add a method to SourceFile that will run that code. There's also some extra work that would need to be done in the `replaceTree` code to ensure the old nodes are removed from the underlying cache.

**Comment by gregjacobs** [comment]
Hey David,

Interesting.. Yes, I did notice that the text wasn't changed, and also after asking this question I did some more digging. Is it that `ts-simple-ast` pretty much does all manipulations on the original source text, and then creates a new AST out of that new source text afterwards?

I thought of a possible workaround yesterday as well to try to achieve my source transformations of expressions / variable assignments / function calls, which is to:

1. Take the node's `compilerNode`, for instance a `ClassDeclaration`'s compilerNode
2. Perform raw AST transformations on it by using a `transformer` and visitor (http://blog.scottlogic.com/2017/05/02/typescript-compiler-api-revisited.html)
3. Pretty-print the new AST using `ts.createPrinter()` (https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#creating-and-printing-a-typescript-ast) 
4. Take that pretty-printed text and use it with `classNode.replaceWithText(prettyPrinted)`

Feels like a total hack though.. Maybe it would be good to have an API to more easily allow for these kinds of visitor transformations?

**Comment by gregjacobs** [comment]
Also a downside of my workaround is that I'm losing single line comments and such that are in the source :/

**Comment by dsherret** [comment]
I'll respond in a bit, but there is a `removeComments` option on the printer. Try setting that to false. It will nuke any blank lines though and change a lot of formatting. I've tried to use it before... definitely not ideal to use.

By the way, this discussion has been overtaken by supporting node factories. Would you mind creating a new issue that's a copy and paste of the first comment and then renaming this one to something about node factories? I think this discussion would be useful for other people to read and it would be nice to have a searchable title for it :)

**Comment by gregjacobs** [comment]
So I figured out my issue with missing comments. 

It seems the printer won't remove comments by default, but I was creating a synthesized copy of each AST node using `ts.getSynthesizedClone(node)` (as to not mutate the original), and that's what was actually making me lose my comments. 

Removing the cloning and mutating the original AST + printing it at least got me my comments back :) (although I lose my original source formatting, like extra line breaks where it makes sense in the code)

Still wish there was a cleaner way to do this where I could mutate the AST and keep the original formatting around the mutated nodes

**Comment by dsherret** [comment]
This is implemented now. Some examples:

```ts
import * as ts from "typescript";

const project = new Project();
const sourceFile = project.createSourceFile("Example.ts", "1; 2; 3;");

// this can be done starting on any node and not just the root node
sourceFile.transform(traversal => {
    const node = traversal.visitChildren(); // return type is `ts.Node`

    if (ts.isNumericLiteral(node)) {
        const incrementedValue = parseInt(node.text, 10) + 1;
        return ts.createNumericLiteral(incrementedValue.toString());
    }

    return node;
});

// outputs: 2; 3; 4;
console.log(sourceFile.getFullText());
```

```ts
import * as ts from "typescript";

const project = new Project();
const sourceFile = project.createSourceFile("Example.ts", `
class C1 {
    myMethod() {
        function nestedFunction() {
        }
    }
}

class C2 {
    prop1: string;
}

function f1() {
    console.log("1");

    function nestedFunction() {
    }
}`);

sourceFile.transform(traversal => {
    // this will skip visiting the children of the classes
    if (ts.isClassDeclaration(traversal.currentNode))
        return traversal.currentNode;

    const node = traversal.visitChildren();
    if (ts.isFunctionDeclaration(node))
        return ts.updateFunctionDeclaration(node, [], [], undefined, ts.createIdentifier("newName"),
            [], [], undefined, ts.createBlock([]))
    return node;
});
```
