### ISSUE TITLE
Adding imports not working

### ISSUE THREAD

**Issue by atasak** [dsherret/ts-simple-ast#186]
When adding imports to reference runtime code used after manipulation, the method silently fails. It doesn't give me an error, nor diagnostic, but no imports appear in the compiled code. I attached a [minimal not-working example](https://github.com/dsherret/ts-simple-ast/files/1573728/example.zip). **Edit:** you should run `dist/compiler/runner.js` with node after compiling with `npm run build` or `npm run build:linux`, depending on your os. 

When running the script in the debugger, it stops at some point in typescript.js. I included a stack trace of this stop. Maybe it will clarify something for you, but as I only have your compiled javascript, I can't make much of it. Also, I'm sorry it a png, but webstorm didn't let me copy the text. 

Am I doing something wrong? 

![stack trace](https://user-images.githubusercontent.com/12663070/34184999-4a5163e6-e523-11e7-856a-033d93f7f7d7.png)

**edit**: I noticed I didn't include all files in the example. I uploaded a new one.

**Comment by dsherret** [comment]
I'm not able to run the code because `apioneconfig.json` is missing. Could you attach a very simple example?

This looks like a similar issue to #122. I'm pretty sure you're using a version > 0.87.0.

Maybe this will fix the problem... open up *node-modules/ts-simple-ast/dist/compiler/tools/Program.js*. In it you will find:

```typescript
    Program.prototype.reset = function (rootNames, host) {
        var compilerOptions = this.global.compilerOptions;
        var oldProgram = this._compilerObject;
        this._compilerObject = getNewProgram();
        this.typeChecker.reset(this._compilerObject.getTypeChecker());
        function getNewProgram() {
            try {
                // try to reuse the old compiler object
                return ts.createProgram(rootNames, compilerOptions, host, oldProgram);
            }
            catch (err) {
                utils_1.Logger.warn("Could not create new program from old program. " + err);
                // if that fails, try without using the old program
                return ts.createProgram(rootNames, compilerOptions, host);
            }
        }
    };
```

Try changing that to:

```typescript
    Program.prototype.reset = function (rootNames, host) {
        var compilerOptions = this.global.compilerOptions;
        var oldProgram = this._compilerObject;
        this._compilerObject = ts.createProgram(rootNames, compilerOptions, host);
        this.typeChecker.reset(this._compilerObject.getTypeChecker());
    };
```

Does that solve the issue? If so, I'm just going to drop trying to pass in the old program because it seems like the typescript compiler isn't handling it well.

**Comment by atasak** [comment]
The fix doesn't work. I'll try to create a simpler example tomorrow.

**Comment by atasak** [comment]
I tried to create a new not-working example from scratch, but I can't get it to not-work... Maybe you can spot something you handle differently in some special cases?

I included both projects. In both, run `npm install`, `npm run build[:linux]` and `npm run run` inside the root directory (the one with package.json). 

[Minimal working example](https://github.com/dsherret/ts-simple-ast/files/1575227/example.zip)
[Minimal not-working example](https://github.com/dsherret/ts-simple-ast/files/1575222/not-working.zip)

**Comment by dsherret** [comment]
Hey @atasak, I just tried it out and I'm seeing the imports being added to the file (doing `source.getFullText()` shows it in there).

Note that typescript's emitter will not emit imports that are not used. In the "not-working" example, if I write a statement that uses one of the imports (ex. `source.addStatements("console.log(ClassWrapper);");`) then I see the import being emitted. I see that in the "working" example, the import is being used in the class and so that's why it's being emitted. Does this solve the issue?

**Comment by atasak** [comment]
Hey @dsherret, 

> Note that typescript's emitter will not emit imports that are not used. In the "not-working" example, if I write a statement that uses one of the imports (ex. source.addStatements("console.log(ClassWrapper);");) then I see the import being emitted. 

I did do that, but as it turns out there was a typo in the name of the type I gave the variable (it was also generated), so eventually there wasn't any variable with the type I was trying to import. At first I assumed this wasn't the case, because I didn't get any diagnostic warnings or errors about unresolved types and constructors... Maybe you'll want to look into that. The code as it was should have been unable to compile. The `source.getFullText()` really helped though, thanks!

**Comment by dsherret** [comment]
@atasak hmmm interesting. Maybe there weren't any emit diagnostics, but were there any compiler diagnostics?

```typescript
const diagnostics = ast.getDiagnostics();
```

**Comment by atasak** [comment]
The ast.getDiagnostics() seem to be working. I didn't realize there were more ways to get diagnostics... Everything is working now. 

One thing remains though: there is a `debugger;` statement in a function `fail()` in `typescript.js:3666`. I manually deleted the `debugger;` statement because the node debugger treats it as a breakpoint I cannot turn of, but something still may be wrong because the method is called fail. Everything seems to work normal, but maybe you'll want to look into it.
