### ISSUE TITLE
Forget block crashes when removing node from ast

### ISSUE THREAD

**Issue by atasak** [dsherret/ts-simple-ast#192]
When removing a node (in my case a propertyNode from a class) when inside a [forget block](https://dsherret.github.io/ts-simple-ast/manipulation/performance#forget-blocks-advanced), the forget block crashes when trying to clean up (forget) all nodes it doesn't have to remember. The error thrown is: 

`Attempted to get information from a node that was removed or forgotten.`

I tried remembering the node just before deleting it (with the same remember function, as well as in a new forget block), but it doesn't seem to help. 

```typescript
ast.forgetNodesCreatedInBlock(remember => {
    ...
    remember(propertyNode); // Doesn't seem to help...
    propertyNode.remove();
    ...
});
```
gives:
```
Error: Attempted to get information from a node that was removed or forgotten.
    at InvalidOperationError.BaseError [as constructor] (C:\Users\niekj\projects\projects\apione\node_modules\ts-simple-ast\dist\errors\BaseError.js:16:28)
    at new InvalidOperationError (C:\Users\niekj\projects\projects\apione\node_modules\ts-simple-ast\dist\errors\InvalidOperationError.js:17:28)
    at PropertyDeclaration.get [as compilerNode] (C:\Users\niekj\projects\projects\apione\node_modules\ts-simple-ast\dist\compiler\common\Node.js:87:23)
    at PropertyDeclaration.Node.getKind (C:\Users\niekj\projects\projects\apione\node_modules\ts-simple-ast\dist\compiler\common\Node.js:138:21)
    at ForgetfulNodeCache.forgetNodes (C:\Users\niekj\projects\projects\apione\node_modules\ts-simple-ast\dist\factories\ForgetfulNodeCache.js:85:26)
    at ForgetfulNodeCache.forgetLastPoint (C:\Users\niekj\projects\projects\apione\node_modules\ts-simple-ast\dist\factories\ForgetfulNodeCache.js:51:18)
    at CompilerFactory.forgetNodesCreatedInBlock (C:\Users\niekj\projects\projects\apione\node_modules\ts-simple-ast\dist\factories\CompilerFactory.js:415:28)
    at TsSimpleAst.forgetNodesCreatedInBlock (C:\Users\niekj\projects\projects\apione\node_modules\ts-simple-ast\dist\TsSimpleAst.js:334:37)
```

It may also be interesting to investigate whether newly created nodes (created as in created with code generation/manipulation, not created from existing code) are forgotten as they should. This may have the same bug, only the other way around. It's less impactfull as it doesn't crash, but it may cause a performance issue with bigger projects. 

I have currently commented out the forget blocks in the code as a workaround, but that may not be feasable when going to bigger test cases.

**Comment by dsherret** [comment]
Thanks @atasak! Will be fixed in 4.3.0 (releasing that very shortly).

**Comment by dsherret** [comment]
Also, I investigated whether created nodes are forgotten and they are.

**Comment by atasak** [comment]
That was a quick one. Thanks!

**Comment by Roaders** [comment]
Is there any workaround for this issues? I am on ts-morph `2.30` and need to wait to get access to later versions. I am trying to remove import declaration nodes. Is there any other way of doing this that won't trigger this error (until I get version `5.0.0`

**Comment by Roaders** [comment]
OK, I have 5.0.0 now (faster than usual) and I still have this issue...

```
function removeMatchingImport(node: ImportDeclaration, file: SourceFile, removeImports: RemoveImport[]) {
    const matches = removeImports.filter(removeImport => matchImport(node, removeImport));

    if (matches.length === 0) {
        return;
    }

    console.log(`Removing '${node.getText()}' from '${file.getFilePath()}'`);

    node.remove();
}
```

```
C:\ts-morph.js:8623
            throw new common.errors.InvalidOperationError(message);
            ^

Error: Attempted to get information from a node that was removed or forgotten.

Node text: import { IImport } from '@myOrganisation/package-name';
```

**Comment by dsherret** [comment]
@Roaders hmmm that's strange. What line is this being thrown on? Is the import declaration being used after it was removed?

I think it might be unrelated to the issue here—could you open a new issue with reproduction steps? Thanks!

**Comment by Roaders** [comment]
Ok, an `ID 10T` issue.. I was trying to call `forEachChild` on the node after I had removed it.

Nothing to see here, move along...

**Comment by dsherret** [comment]
That's ok! I'm thinking I could capture the stack at the moment it's removed and then display that to the user in the error message as well. I know these can be hard to figure out sometimes (I've done it many times). Opened #751.

**Comment by Roaders** [comment]
BTW - really impressed with ts-morph. I was initially doing this with ts-lint but this is much easier.
I was at ts-conf (the first time) and saw your talk. Only recently realised how useful this project is.
Thanks for your work and continued support.

**Comment by dsherret** [comment]
@Roaders thanks! :) I'm glad it's been useful for you.
