### ISSUE TITLE
When copying, imports to outside the ast sources are lost

### ISSUE THREAD

**Issue by atasak** [dsherret/ts-simple-ast#197]
When emitting a directory as described in #182 #183, with the workaround from #195, imports to pre-compiled sources are lost. I only tested it when using the tsconfig compiler options `baseUrl` and `paths`. Example project:

```
root/dist/compiler/*                    // Directory with code manipulation code using ts-simple-ast
root/dist/runtime/something.ts          // Runtime component imported after code manipulation
root/test/src/test.ts                   // Code to test above on
root/test/dist/test.[js, js.map, d.ts]  // Only existing after running root/dist/compiler
root/test/gen/test.ts                   // Only exists after running root/dist/compiler
root/src/*                              // Source directory of root/dist
root/tsconfig.json                      // tsconfig to compile root/src
root/tsconfig.test.json                 // tsconfig used to compile and manipulate root/test/src with root/dist/compiler
```

tsconfig.test.json subset:
```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "something": [
        "dist/runtime/something"
      ]
    }
  }
}
```

During code manipulation of `roots/test/src/test.ts` with `root/dist/compiler`, the code is first copied to `root/test/gen/test.ts`, then manipulated so it includes `MyType` from `something` (the typescript compiler should dereference this via `paths` in `tsconfig.test.json`), saved in `root/test/gen/test.ts` and finally emitted to `root/test/dist/test.[js, js.map, d.ts]`. I expected the referencing of `something` to work (as it did without copying`, but it throws ast diagnostics: 

`root/test/gen/test.ts.linenr: Cannot find name 'Something'. `

**Comment by atasak** [comment]
OK, apparently I added the code to the wrong code. My bad ...

**Comment by dsherret** [comment]
That's ok :)
