### ISSUE TITLE
Absolute imports

### ISSUE THREAD

**Issue by atasak** [dsherret/ts-simple-ast#198]
I currently use `compilerOptions.path` in `tsconfig.test.ts` because working with relative imports gets tedious when trying to reference code outside of the sources you are trying to manipulate. This can be when your code manipulation code has a runtime component that will be includes by the code manipulation. My issue with it will disappear as soon as I create a npm package for it, but the issue in general remains. I don't currently have any good proposals to resolve this, but I just wanted to point it out.

**Comment by dsherret** [comment]
Hey @atasak, I'm not entirely sure what you mean. Could you elaborate on this?

Do you mean you would like the ability to specify a module specifier for an import declaration using an absolute path and then that will be changed into a relative path based on the current file path?

**Comment by dsherret** [comment]
@atasak closing this for now. Please reopen if you respond.

**Comment by atasak** [comment]
Hey @dsherret 

When generating code, chances are there also is a static runtime component you'll want to include in generated code. I thought it would be nice (almost necessary) to be able to reference this with an absolute path so you don't have to keep track of which file you are manipulating/generating (and add multiple `../` accordingly). I realized however, when you create an npm package for your code, it doesn't matter because you can just import from `'./package'`. When creating/testing the package, you can use `compilerOptions.path` in the tsconfig you use with `ts-simple-ast`, creating a sort of `virtual package`. This way you don't have to distinguish between test-code (which runs in the package, so without having runtime code installed in node_modules) and end-user code (which has your package including runtime code installed in node_modules). 

I'm leaving this issue closed for now. Let me know if you don't understand something or have different thoughts on this. 

Also, sorry for the late response. I have been away a while ago and kind of forgot about it...
