### ISSUE TITLE
Add TrueKeyword and FalseKeyword node types

### ISSUE THREAD

**Issue by gregjacobs** [dsherret/ts-simple-ast#200]
And TypeGuards for them too! ;)

**Comment by gregjacobs** [comment]
Btw man, just wanted to tell you, I'm making huge progress on this AngularJS->Angular2 converter thanks to you..

**Comment by dsherret** [comment]
@gregjacobs awesome! :) I can imagine that's quite complicated to do. I'd be interested to see it when it's ready.

**Comment by gregjacobs** [comment]
Man, I'd love to show it to you, but unfortunately I made the mistake of starting it in my company's system and that's where it is :( 

I'm going to try to see if I can get approval to open source it though!

**Comment by dsherret** [comment]
`BooleanLiteral` will be available in the next version (whenever that's released).
