### ISSUE TITLE
Add missing Statement classes

### ISSUE THREAD

**Issue by dicarlo2** [dsherret/ts-simple-ast#204]
Hi @dsherret, first off, thanks for creating a great library, it's proven to be invaluable for a project I'm currently working on. There are some missing wrappers that I'd like to see in the library. I need this rather urgently, so I'll likely publish my own package while waiting for reviews/release, but I'd love to contribute back to the library. I don't see contributor guidelines, so I'm going to just mimic some of your previous commits.

**Comment by dsherret** [comment]
Sounds great! Yeah, I was thinking last night about how I can make contributing easier. I'm going to devote some time to that over the next few weeks and clean up some of the internals in the library so things are more straightforward.

**Comment by dsherret** [comment]
@dicarlo2 I'll do a minor release when I get home tonight.

**Comment by dicarlo2** [comment]
With these prs all statements should be there except `WithStatement`, honestly not going to bother because it's not valid typescript or strict javascript, so it basically shouldn't ever show up in a program.

**Comment by dsherret** [comment]
@dicarlo2 I was feeling up for it so I went ahead and added `WithStatement`. I'm thinking perhaps someone in the future might want to write a script that automatically removes all `WithStatements` from an application.

**Comment by dsherret** [comment]
I believe this is implemented now. Closing.

**Comment by dicarlo2** [comment]
Thanks for the quick reviews!
