### ISSUE TITLE
[BUG] Expose ArrayLiteralExpression, ObjectLiteralExpression, SpreadElement

### ISSUE THREAD

**Issue by vogloblinsky** [dsherret/ts-simple-ast#228]
```
import * as tsa from 'ts-simple-ast';
```

`tsa.ArrayLiteralExpression` `tsa.SpreadElement` and `tsa.ObjectLiteralExpression` are not available.

**Comment by dsherret** [comment]
@vogloblinsky are you using 6.2.0 and can you try restarting your IDE? Maybe the auto complete cache is out of date. I'm able to import these in a test project.

**Comment by vogloblinsky** [comment]
Stop and restart VS Code, yes it works, thanks !

**Comment by dsherret** [comment]
No problem! It's annoying when the IDE can't figure it out the first time.
