### ISSUE TITLE
IndexSignatureDeclaration suggestions

### ISSUE THREAD

**Issue by kjpou1** [dsherret/ts-simple-ast#245]
Hey David

Thanks for the wrapping and have a couple of suggestions after incorporating it.  

The following might be useful as the IndexSignatureDeclaration looks more or less like a Property.

- [x] getModifiers()  `=> <ModifierableNode>`
- [x] isReadonly()  `=> <ReadonlyableNode>`

Not sure if anyone else will find them useful and I have worked around them.

Thanks again

**Comment by dsherret** [comment]
Thanks! I forgot it could have a readonly keyword... it's pretty simple to add so I just did a quick release. This is available in 6.12.0.

**Comment by kjpou1** [comment]
Thanks @dsherret.  Works great.
