### ISSUE TITLE
Generic Support on Interface and Class Definitions

### ISSUE THREAD

**Issue by kjpou1** [dsherret/ts-simple-ast#254]
For navigation support the following would be nice:

From the handbook http://www.typescriptlang.org/docs/handbook/generics.html.

Generic classes have a generic type parameter list in angle brackets (<>) following the name of the class.  Interfaces would have the same definition.

- [ ] isGenericDeclaration - The interface or class declaration contains generic types.
- [ ] getGenericTypes() - Returns an array of the generic definition types.
- [ ] getGenericTypeNodes() - Returns an array of the generic definition nodes
- [ ] getGenericConstraints - Returns an array of constraints if any exist

The above is probably a simplistic interface and may contain other definitions that may help in navigation.

Other types may be included later i.e. function/method declarations etc...

**Comment by dsherret** [comment]
Hey @kjpou1, this already exists:

```ts
classDeclaration.getTypeParameters();
classDeclaration.getType().getTypeParameters();
TypeGuards.isTypeParameteredNode(classDeclaration);
```

It's just not in the documentation because I seem to have never added it there.

**Comment by dsherret** [comment]
I've opened #255.
