### ISSUE TITLE
failed to recognize union type

### ISSUE THREAD

**Issue by Leooonard** [dsherret/ts-simple-ast#258]
```
interface Person {
    name: string | null
}
```

when i use ts-simple-ast to get the type of name attribute, it gives the error result. 

example:

```
// property is PropertySignature.
console.log(property.getType().isUnionType()) // output false;
```

**Comment by dsherret** [comment]
Hey @Leooonard, this has got me in the past too. Make sure that the `strictNullChecks` or the `strict` compiler option or is enabled.

This can be specified in the `tsconfig.json` when initializing like this:

```ts
const ast = new Ast({ tsConfigFilePath: "src/tsconfig.json" });
```

Or by specifying it in the `compilerOptions` object:

```ts
const ast = new Ast({
    compilerOptions: {
        strictNullChecks: true
    }
});
```

Or override what's in `tsconfig.json` like so:

```ts
const ast = new Ast({
    tsConfigFilePath: "src/tsconfig.json",
    compilerOptions: {
        strictNullChecks: true
    }
});
```

**Comment by Leooonard** [comment]
@dsherret after add tsconfig, everything works fine, thx a lot!
