### ISSUE TITLE
Error thrown when working with class containing semicolon-terminated constructor or method declaration

### ISSUE THREAD

**Issue by coditect** [dsherret/ts-simple-ast#265]
A TypeError is thrown when `getInstanceMembers` or `getStaticMembers` is called on a class that contains a method or constructor whose body is followed by a semicolon, as shown in the example below.
```ts
import TsSimpleAst from 'ts-simple-ast';

const ast = new TsSimpleAst();
const sourceFile = ast.createSourceFile('example.ts', `

export class Example1 {
  method() {}
}

export class Example2 {
  method() {};
}

`);

sourceFile.getClass('Example1').getInstanceMembers(); // works
sourceFile.getClass('Example2').getInstanceMembers(); // throws
sourceFile.getClass('Example1').getStaticMembers(); // works
sourceFile.getClass('Example2').getStaticMembers(); // throws
```

I'm not sure why one would want to put a semicolon after a constructor or method declaration, but it happened on my project nonetheless.  The stack trace seems to indicate that such declarations are parsed as something other than a normal `ConstructorDeclaration` or `MethodDeclaration`.  We're using ts-simple-ast v8.2.0, ts-node v3.3.0. node v6.12.3, and typescript v2.6.2.

```
~/node_modules/ts-simple-ast/dist/compiler/class/ClassDeclaration.js:470
        return this.getMembers().filter(function (m) { return !utils_1.TypeGuards.isConstructorDeclaration(m) && (utils_1.TypeGuards.isParameterDeclaration(m) || !m.isStatic()); });
                                 ^
TypeError: m.isStatic is not a function
    at ~/node_modules/ts-simple-ast/dist/compiler/class/ClassDeclaration.js:470:166
    at Array.filter (native)
    at ClassDeclaration.getInstanceMembers (~/node_modules/ts-simple-ast/dist/compiler/class/ClassDeclaration.js:470:34) 
    at Object.<anonymous> (~/test.ts:21:33)
    at Module._compile (module.js:570:32)
    at Module.m._compile (~/node_modules/ts-node/src/index.ts:392:23)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .ts] (~/node_modules/ts-node/src/index.ts:395:12)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```

**Comment by dsherret** [comment]
Interesting. Thanks for reporting this! The compiler in this case is creating a `SemicolonClassElement` node (see with [ts-ast-viewer.com](http://ts-ast-viewer.com/)):

![image](https://user-images.githubusercontent.com/1609021/36820814-c5c715bc-1cbd-11e8-9585-cdd0c36e089f.png)

I submitted a fix and it's now released in v8.2.1.

Sidenote: While looking at this I wasn't too happy with the state of `ClassDeclaration`. It was one of the first parts I added to this library. I opened #266.
