### ISSUE TITLE
Creating an empty file

### ISSUE THREAD

**Issue by lazarljubenovic** [dsherret/ts-simple-ast#272]
Thanks for the amazing library! Codegen has never been this easy and this fun.

Is there an "official" way of creating a new file and saving it? I want to generate TypeScript code based on my source files, which is then ready for the usual TypeScript compilation as a new project. I guess I could use `fs` for this, but was wondering if it's possible to do so via some nice wrapper utility from this lib.

**Comment by lazarljubenovic** [comment]
I'm stupid. There's a `createSourceFile`, but looks like it's documented only in the Readme of the repo and not on the docs site.

**Comment by dsherret** [comment]
Sorry that’s my bad! In the future I will either be doing some analysis between the code and the documentation to identify gaps, or will be generating some documentation from the code.

I’m glad you are enjoying the library though! :)
