### ISSUE TITLE
type.isTupleType does not exist

### ISSUE THREAD

**Issue by Gerrit0** [dsherret/ts-simple-ast#278]
According to the [Type](https://dsherret.github.io/ts-simple-ast/details/types#telling-type) docs, I should be able to use `type.isTupleType()` in order to check if a type is a tuple type. 

It looks like this method was added to the docs in 15360cb154f281c21e8d262179146244515c1ff8, but I can't seem to find if the `isTupleType` method ever existed. Am I missing something here? 

(I'd open a PR, but I haven't figured out how to tell if a type is a Tuple yet, it doesn't seem to be saved in the `flags`)

**Comment by dsherret** [comment]
@Gerrit0 Sorry, it's added now. I'll do a release sometime later today. Thanks for reporting the issue with the docs!

By the way, I also just added a `getTupleElements()` method.

**Comment by Gerrit0** [comment]
Thanks much! I'll need to do a comparison once I've finished refactoring, but I started using this project in one of my own instead of using the compiler api directly and so far it seems to have cut down the code size by about 1/3 per file. Amazing :)

**Comment by dsherret** [comment]
@Gerrit0 awesome! :D I've experienced similar improvements with some of my other code. It also makes it easier for other people to almost immediately understand and contribute to your code.

By the way, this is now published in 9.3.0.
