### ISSUE TITLE
Efficient way to get all descendant statements

### ISSUE THREAD

**Issue by dsherret** [dsherret/ts-simple-ast#279]
Would be nice if there was an efficient `.getDescendantStatements()` method.

```ts
// examples of statements
const a = () => {
    const b = "";
};
const c = 5;
function d() {
    function e() {
        const f = "";
    }
}
class MyClass {
    prop = () => console.log("here"); // need these statements not in a block too
}
```

**Comment by dsherret** [comment]
This is good enough for now. Would be nice to make this more efficient in the future.

**Comment by cancerberoSgx** [comment]
Quick question about forEachChild library's method. I'm trying to use it like I use ts.forEachChild but I can't figure out how. Concretely, how would you implement this the following? 

```
export function findSmallestDescendantContainedInRange(sourceFile:SourceFile, r:TextRange):Node | undefined {
  function find(node:Node):Node | undefined {
    if (r.pos >= node.getStart() && r.end <= node.getEnd()) {
      return node.forEachChild(find) || node
    }
  }
  return find(sourceFile)
}
```

I want to migrate lots of functions I have so I can use the library without working with the compiler nodes, but I cannot reach a clean solution. And performance here is really important. At the time I implemented those, my conslusion was that something like that, using ts.forEachChild should be the best approach?

My problem is the find() function declaration, that needs to comply with (unfamiliar to me) node.forEachChild signature. I know, from the tests that calling the stop() property is possible to stop and return that node, but I cannot figure out how ....  If you have any idea or tip I thank you. Really have about 10 methods working fine that I want to port and the best way I can. Thanks in advanced, sorry to bother,

**Comment by dsherret** [comment]
@cancerberoSgx can you open new issues for questions? This is an issue about a task and that question isn't related to descendant statements. I'll answer if you open up an issue.

**Comment by cancerberoSgx** [comment]
Thanks!
