### ISSUE TITLE
Possible Error with TypeLiteralNode validation?

### ISSUE THREAD

**Issue by kjpou1** [dsherret/ts-simple-ast#282]
When using TypeGuards.isTypeLiteralNode the kinds that are being verified are different from the value actually passed.

[TypeGuards.isTypeLiteralNode](https://github.com/dsherret/ts-simple-ast/blob/master/src/utils/TypeGuards.ts#L2189) is checking against TypeLiteral which is kind `164` but the TypeLiteralNode kind is `174`.

This may also affect [TypeGuards.isTypeNode](https://github.com/dsherret/ts-simple-ast/blob/master/src/utils/TypeGuards.ts#L2197) but not sure.

Or am I looking at it incorrectly?

**Comment by dsherret** [comment]
Hey @kjpou1, `LiteralType` is 174 and `TypeLiteral` is 164. Very easy to mix them up! :) (Maybe I am mixing them up right now and not realizing...)

Here's the definition from the compiler for `TypeLiteralNode` and `LiteralTypeNode`:

```ts
export interface TypeLiteralNode extends TypeNode, Declaration {
    kind: SyntaxKind.TypeLiteral; // 164
    members: NodeArray<TypeElement>;
}

export interface LiteralTypeNode extends TypeNode {
    kind: SyntaxKind.LiteralType; // 174
    literal: BooleanLiteral | LiteralExpression | PrefixUnaryExpression;
}
```

Perhaps you mean to use `TypeGuards.isLiteralTypeNode(...)`?

**Comment by kjpou1** [comment]
@dsherret yes it looks like that was it !!!  Thanks for pointing that out.
