### ISSUE TITLE
newLineIfLastNotNewLine() is deprecated. Use newLineIfLastNot() instead.

### ISSUE THREAD

**Issue by ChuckJonas** [dsherret/ts-simple-ast#301]
Keep getting this warning as well as `spaceIfLastNotSpace() is deprecated. Use spaceIfLastNot() instead.` when I'm generating classes.  Haven't quite narrowed down exactly what method it is yet...

**Comment by ChuckJonas** [comment]
https://github.com/dsherret/ts-simple-ast/search?utf8=%E2%9C%93&q=newLineIfLastNotNewLine&type=

**Comment by dsherret** [comment]
@ChuckJonas That's annoying. It was a problem down in code-block-writer. Can you try re-doing `npm install` and see if it doesn't do that anymore?

**Comment by ChuckJonas** [comment]
@dsherret its says my package is already up to date... No change if I do rebuild and run

**Comment by dsherret** [comment]
@ChuckJonas sorry, can you try deleting `node_modules/code-block-writer` and `node_modules/ts-simple-ast/node_modules/code-block-writer` if it exists, then try running `npm install`?

**Comment by lazarljubenovic** [comment]
Try explicity installing the `@latest` version. The lockfile could be
keeping you from getting the new one, even if you delete it from
`node_modules`.

**Comment by dsherret** [comment]
The lockfile uses an old version that wouldn't have the console.warn in it.

**Comment by ChuckJonas** [comment]
doing a clean install fixed it.  Awesome package; keep up the good work!!!

**Comment by dsherret** [comment]
@lazarljubenovic ah yes, I forgot about that. Good point! Thanks!

@ChuckJonas no problem! I'm glad that cleared it up. Sorry for introducing this.
