### ISSUE TITLE
Improve getNodeProperty by using conditional types

### ISSUE THREAD

**Issue by dsherret** [dsherret/ts-simple-ast#304]
Looks like this:

```ts
export type TsNodePropertyNames<NodeType extends ts.Node> = {
    [KeyName in keyof NodeType]:
        KeyName extends "_tsSimpleAstBrand" | CompilerApiNodeBrandPropertyNamesType ? never : KeyName;
}[keyof NodeType];
export type TsNodeToWrappedType<NodeType extends ts.Node, KeyName extends TsNodePropertyNames<NodeType>, NonNullableNodeType = NonNullable<NodeType[KeyName]>> =
    NodeType[KeyName] extends ts.NodeArray<infer ArrayNodeType> ? Node<ArrayNodeType>[] :
    NodeType[KeyName] extends ts.Node ? Node<NodeType[KeyName]> :
    NonNullableNodeType extends ts.Node ? Node<NonNullableNodeType> | undefined :
    NodeType[KeyName];
```

But unfortunately only compiles in typescript@next due to bugs so I'll have to wait. Maybe it will work in the next 2.8.x version. In the meantime, I've checked this into the getNodeProperty branch.

**Comment by cancerberoSgx** [comment]
Hello, Just curious, I've noticed that sometimes is hard to access the AST using getters that return Node|undefined. I wonder if this issue try to attack that ? For example, because ts-simple-ast uses methods and not properties sometimes I end up using local variables and && like the following snippet if tsc is configure with strict=true: 

```ts
function importDeclaration2Structure(importDecl: ImportDeclaration): ImportDeclarationStructure {
  let defImport:Identifier | undefined, namedImport:  ImportSpecifier[], namespaceImport: Identifier | undefined, 
  return { 
    namedImports: (namedImport = importDecl.getNamedImports()) && namedImport.map(ni => ni.getText()), 
    defaultImport: (defImport = importDecl.getDefaultImport()) && defImport.getText(), 
    namespaceImport: (namespaceImport = importDecl.getNamespaceImport()) && namespaceImport.getText(), 
    moduleSpecifier: importDecl.getModuleSpecifier().getText() 
  }
}
```

**Comment by dsherret** [comment]
@cancerberoSgx that's a different issue than this one.

I've often wondered about switching this library to using properties instead of methods, but it would probably be too large of a breaking change at this point.

So with properties you would be able to do:

```ts
defImport: importDecl.defaultImport && importDecl.defaultImport.getText()
```

With methods you can do:

```ts
defImport: importDecl.getDefaultImport() && importDecl.getDefaultImportOrThrow().getText()
```

Basically, once typescript supports the null propagation operator then our troubles will go away:

```ts
defImport: importDecl.getDefaultImport()?.getText()
```

Probably best to just wait for that.

**Comment by cancerberoSgx** [comment]
Didn't knew that one, nice! Also , a helper (at least temporary for debuging) is using ! for example, without "!" the following fails in strict=true: 

`node.getExpression().getSymbol()!.getDeclarations()`

my two cents

**Comment by dsherret** [comment]
Yes, or by using `getSymbolOrThrow()`.

**Comment by lazarljubenovic** [comment]
I'm personally using `orThrow` variants so much I'd almost prefer them being the regular ones and the others `orNull`. :sweat_smile:

**Comment by dsherret** [comment]
@lazarljubenovic it might be nice in some scenarios, but it's good for people to prompted about something possibly being possibly null and then from there decide whether they want to handle it being null or do something else like throwing an exception.
