### ISSUE TITLE
output TS file.

### ISSUE THREAD

**Issue by navid9675** [dsherret/ts-simple-ast#318]
Hi first of all. great work thanks a lot.
I have a question, how can emit a source as a '.ts' file? cause when I save a project (after I make some changes) it outputs JavaScript files but I need TypeScript files.
Thanks.

**Comment by dsherret** [comment]
Ok, actually I wrote it out just now. Try this:

```ts
// untested
const srcDir = project.getDirectoryOrThrow("./src"); // get the root directory of the source of your project
const destDir = project.getDirectoryOrThrow("./destination");
const fileSystem = project.getFileSystem();
const promises: Promise<void>[] = [];

for (const sourceFile of srcDir.getDescendantSourceFiles()) {
    const relativePath = srcDir.getRelativePathTo(sourceFile);
    promises.push(fileSystem.writeFile(path.join(destDir.getPath(), relativePath), sourceFile.getFullText()));
}

await Promise.all(promises);
```

**Comment by navid9675** [comment]
Thanks a lot.

**Comment by dsherret** [comment]
@navid9675 I've been thinking about this a bit and I think this will be covered by #256. Basically the code would look like this:

```ts
// get the directory you want to copy
const srcDir = project.getDirectoryOrThrow("./src");
// copy the directory
const newDir = srcDir.copy("./destination"); // method doesn't exist yet
// save it to the file system
await newDir.save();
```

I'll comment back here when #256 is implemented.

**Comment by navid9675** [comment]
Thank you @dsherret, that would be great. Should I reopen the issue?

**Comment by dsherret** [comment]
@navid9675 no it's ok. I'm working on #256 right now and this will be covered by that.

By the way, it looks like there is a `directory.copy` method that currently exists, but there's a problem with it in that it doesn't update module specifiers appropriately when copying (I'm updating it for version 11 along with #256). I don't believe that matters for your scenario though so the above code should work today.

**Comment by dsherret** [comment]
@navid9675 in version 11 the following code should work:

```ts
const srcDir = project.getDirectoryOrThrow("./src");
// need to specify false here to prevent it from including other files in the directory
const newDir = srcDir.copy("./destination", { includeUntrackedFiles: false });
await newDir.save();
```

Let me know if you run into any issues.

**Comment by navid9675** [comment]
@dsherret  thanks a lot, it worked like a charm. Great job!

 if I found anything else I will let you know.  thank you
