### ISSUE TITLE
Able to create Project from existent native ts.server.Project

### ISSUE THREAD

**Issue by cancerberoSgx** [dsherret/ts-simple-ast#326]
It will be very common that people use this library to facilitate LanguageService plugins development. There one already have a Project instance  and since you basically are wrapping objects should be easy and straightforward to have an api to build a ts-simple-ast.Project from a ts.server.Project directly. 

THis is a very very small issue, is any, actually just wanted to thank you for the project. I was doing something similar, while learning and developing my first LanguageService plugins. You solved LOTS of the problems I was envision to reach my goals. Just discovered this, thanks! :)

**Comment by cancerberoSgx** [comment]
The way I found to do this is as follow, but is dirty. Can you think on a better way  ? Thanks: 

```ts
/**dirty way of getting path to cnofig file of given program */
function getConfigFilePath(project: ts_module.server.Project){
  return project.getFileNames().find(p=>basename(p.toString())==='tsconfig.json')
}
/** dirty way of creating a ts-simple-ast Project from an exiting ts.server.Project */
function createSimpleASTProject(project: ts_module.server.Project){
  return new Project({
    tsConfigFilePath: getConfigFilePath(info.project)
  });
}
const project = new Project({
  tsConfigFilePath: getConfigFilePath(info.project)
});
```

**Comment by cancerberoSgx** [comment]
And I guess the same apply for all the rest of your wrappers. For example, in my plugin I already have the ts.Node of what I want to refactor and I want to get your wrappers for use your helpers, for example, ClassDeclaration Nodes. Is that possible ? thanks

**Comment by dsherret** [comment]
Hey @cancerberoSgx, the `Project` object (and this library in general) wasn't created with language service plugins in mind and internally it doesn't use `ts.server.Project`.

At the moment, for this scenario, it's probably best to just use the `createWrappedNode` function, though it's somewhat limiting:

```ts
// from the readme.md
import { createWrappedNode, ClassDeclaration, ts } from "ts-simple-ast";

// some code that creates a class declaration using the ts object
const classNode: ts.ClassDeclaration = ...; 

// create and use a wrapped node
const classDec = createWrappedNode(classNode) as ClassDeclaration;
const firstProperty = classDec.getProperties()[0];
```

I think perhaps there's a way forward that I could refactor some of the code so that the library could work on top of an existing `ts.server.Project`, but it would be a bit of work to do that.

**Comment by cancerberoSgx** [comment]
Thanks! No worries, I think I can make some helpers. Please don't waste time in this and keep working on your plan! :) I thought perhaps was an easy / straight forward way. When solving my problems, will share with you the helpers I have. Thanks again and keep it up

**Comment by cancerberoSgx** [comment]
Just in case I've improved the code. I find that the call always takes around 1.5 seconds no matter how big the project is. right now I'm always creating the object (each time the user actions a refactor) and I'm investigating the possibility of maintaining this object in a variable and update the source files that changed somehow before using it (or test if that is neccesary - will simple-ast project get changes made by third parties ? )

```
import { basename } from 'path';
import Project from 'ts-simple-ast';
import * as ts_module from 'typescript/lib/tsserverlibrary';

/** gets the config file of given ts project or undefined if given is not a ConfiguredProject or tsconfig cannot be found */
function getConfigFilePath(project: ts_module.server.Project): string | undefined {
  if ((project as ts_module.server.ConfiguredProject).getConfigFilePath) {
    return (project as ts_module.server.ConfiguredProject).getConfigFilePath()
  }
  else {
    return project.getFileNames().find(p => basename(p.toString()) === 'tsconfig.json')
  }
}
/**
 * (dirty way) of creating a ts-simple-ast Project from an exiting ts.server.Project. Given project must be a
 * configured project (created with a tsconfig file. It will recreates the project from scratch so it can take
 * some time. Use it with discretion
 */
export function createSimpleASTProject(nativeProject: ts_module.server.Project): Project {
  const tsConfigFilePath = getConfigFilePath(nativeProject)
  const project = new Project({
    tsConfigFilePath: getConfigFilePath(nativeProject)
  })
  return project
}


// create example: 
const project = new Project({
  tsConfigFilePath: getConfigFilePath(info.project)
});
```
