### ISSUE TITLE
Error: Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by punithnpg** [dsherret/ts-simple-ast#334]
Getting this error 
```
throw new errors.InvalidOperationError(err.message + "\n" +
        ^

Error: Cannot read property 'kind' of undefined
```
for the code: 
```
function addMethod(methodName, componentName) {
  sourceFile = project.addExistingSourceFile(
    './' + componentName + '/' + componentName + '.component.ts'
  );
  
  classDeclaration = sourceFile.getClass(<ClassName HERE>);
  
  
  classDeclaration.addMethod({
    name: methodName
  });

  project.save();
}
```

**Comment by dsherret** [comment]
@punithnpg any chance you could provide some code that reproduces the problem? I'm curious about this one. Thanks!

**Comment by punithnpg** [comment]
@dsherret I changed the implementation of this to 
```
function addMethod(methodName, component) {
  var componentClass = sourceFile.getClass(component + 'Component');
  componentClass .addMethod({
    name: methodName
  });
  sourceFile.save();
}
```
and this worked well for me!

**Comment by dsherret** [comment]
@punithnpg could you help me see the difference? Does the error happen when calling `.save()` on `project` instead of `sourceFile`?

It would still be nice to know what was going on here in case it arises again in the future. It was already reported before in #344.

**Comment by punithnpg** [comment]
@dsherret Hi, I tried to replicate the same.  Couldn't produce the error on both save of project and save of sourceFile.
