### ISSUE TITLE
SourceFile getClasses and getInterfaces Not In Auto-Complete

### ISSUE THREAD

**Issue by sfrooster** [dsherret/ts-simple-ast#34]
Maybe this is unavoidable, but as the documentation is under construction not having these appear in the IDE is problematic.

**Comment by sfrooster** [comment]
Interestingly - these have now shown up.  I'll keep this open for now in case I can figure out a pattern.  If I can't, I'll close it.

**Comment by dsherret** [comment]
Hmmm... that's really weird. I'm making extensive use of mixins in this library so it might be related to that. Maybe it's slow to figure out what to show in the auto-complete.

**Comment by sfrooster** [comment]
It does eventually show-up so it seems to be a vscode thing.  Closing.
