### ISSUE TITLE
remove PropertyAssignament from ObjectLiteralExpression

### ISSUE THREAD

**Issue by cancerberoSgx** [dsherret/ts-simple-ast#342]
Hello, before throwing myself to the water and implement it, I would like to know if there is some way of removing a `PropertyAssignament` from an `ObjectLiteralExpression`, example: 

given an object literal `{name: 'seba', lastname: 'gurin'}`

and I want to remove property 'name' so the resulting object is `{lastname: 'gurin'}`

Thanks in advanced

**Comment by dsherret** [comment]
Nope. Looks like that was never implemented (same for `ShorthandPropertyAssignment` and `SpreadAssignment`). It looks like that would be a good one to implement and add `.remove()` methods on them. Thanks for checking 😄

**Comment by cancerberoSgx** [comment]
thanks! nice to know - will PR then. 

Idea / suggestion - from my point of view (user manipulating the AST) exporting removeChildren() (/src/manipulation/manipulations/removal.ts) would give a lot of flexibility. I know is low level - and I know is one more signature to maintain backwards compatibility - but this would be very very useful for advanced users . These things could be exported in a "lowLevel" namespace or something like that to not disturb common users :P .. the same applies to other utilities in manipulations/ my two cents.

**Comment by cancerberoSgx** [comment]
aside question - I feel like there should be a couple extra interfaces for this  kind of artificialities. For example, Removable (for this case), StructureFillable (fill), StructureGetable (getStructure)  (and a couple more that I can't remember now), Also typeguards for those would be nice. I wonder if you agree with this....

**Comment by dsherret** [comment]
I'd rather implement it for the scenario and have people submit pull requests/report an issue when something's not implemented. That way everyone can benefit. Additionally, there can be a lot of edge cases and exposing `removeChildren` would just lead to people opening bug reports when it doesn't work the way they expect it to.

**Comment by cancerberoSgx** [comment]
https://github.com/dsherret/ts-simple-ast/pull/343

**Comment by dsherret** [comment]
I missed a few things in the review so did a new commit. This should be good to go so I'm doing a release now.
