### ISSUE TITLE
ArrowFunction should be a FunctionLikeDeclaration to be consistent with typescript

### ISSUE THREAD

**Issue by cancerberoSgx** [dsherret/ts-simple-ast#345]
I don't see any reason why it we can easily add FunctionLikeDeclaration to ArrowFunction, am I missing something? This is typscript: 

```
interface ArrowFunction extends Expression, FunctionLikeDeclarationBase
```

The main consequence I found because of this is that TypeGuard.isFunctionLikeDeclaration() will return false for ArrowFunction which is inconsistent with `function isFunctionLike(node: Node): node is SignatureDeclaration;`. If not possible, then perhaps can we create a new TypeGuard isFunctionLike to cast to SignatureDeclaration like typescript's ? 

I'm using `TypeGuards.isSignaturedDeclaration` but IMO that's not obvious I think we should use same TypeScript naming if possible... 

I would be able to attack the issue, but first I wanted to ask you, thanks

**Comment by dsherret** [comment]
Hi @cancerberoSgx, thanks for reporting this! I will take a look at this later because this is a breaking change and it requires some changing of where the mixins are placed.

For now, please continue to use `isSignaturedDeclaration`.

**Comment by cancerberoSgx** [comment]
is not critical, more like a question I think - IMO you should take it as low priority and if you decide this should be tackled I would like to help you -  perhaps a little documentation note is enough to alleviate the problem...
