### ISSUE TITLE
getSourceFiles returning multiple instances of the same file

### ISSUE THREAD

**Issue by crisbeto** [dsherret/ts-simple-ast#348]
I'm sorry for the vague report, but this is part of a larger project and I haven't been able to isolate the issue. I have a setup that looks like this:

```ts
const project = new Project({
  useVirtualFileSystem: true
});

glob(someFilePattern).forEach(filePath => {
  project.createSourceFile(filePath, readFileSync(filePath).toString());
});

console.log(project.getSourceFiles().map(sf => sf.getFilePath()));
```

In the `console.log` at the end I get an array that has multiple instances of each file (for a 42-file project I get back 663 results), e.g. the array looks like `['foo.ts', 'bar.ts', 'foo.ts', 'bar.ts']`. A few notes:

* I'm confident that the logic that creates the source files in the first place doesn't have any duplicates, and even if it did, `ts-simple-ast` would throw an error if I tried to create the file again.
* This started happening after updating from `10.2.0` to `12.4.0`.
* The references in the array returned by `getSourceFiles` are all pointing to the same object which means that it's probably not creating multiple instances of the same file.
* The issue can be worked around using `getSourceFiles('**/*.ts')`.

**Comment by dsherret** [comment]
Hmmm that’s strange. Usually I’m really fast at fixing bugs, but unfortunately I’m moving this week so I’ll take a look sometime next week.

**Comment by cancerberoSgx** [comment]
Hey @crisbeto , just out of curiosity, since I can't reproduce this, could you share the value of someFilePattern and more or less the structure of the current folder ? is it a TypeScript project ? does it have tsconfig.json and package.json files ? what happen if you run it using absolute glob from another folder ? What happens if you add a minimal compilerOptions  ? : 
```
compilerOptions: {
        target: ScriptTarget.ES3
    }
```
Thanks

**Comment by dominique-mueller** [comment]
I am experiencing the same issue, suddenly 133 files become 135, two files are duplicate. Also, I can confirm that the workaround of selecting source files using `getSourceFiles( "**/*.ts" )` works.

**Comment by dsherret** [comment]
@crisbeto @dominique-mueller I didn't mean to close this just yet. Since I wasn't able to reproduce this could you see if the latest fix in 12.4.1 resolved this issue? Thanks!

Also, sorry for the delay. I finally got my desk setup last night.

**Comment by dominique-mueller** [comment]
I did upgrade to `12.5.0` right away, and the issue no longer appears in my project! Thanks for the quick fix!

**Comment by crisbeto** [comment]
I can also confirm that the issue is fixed. Thank you @dsherret!
