### ISSUE TITLE
Setting isAbstract:true on a method still puts in a blank implementation

### ISSUE THREAD

**Issue by joseph-whiting** [dsherret/ts-simple-ast#356]
When including a method in a declaration of abstract class, providing `isAbstract: true` still produces an empty implementation, like

```typescript
abstract class {
   abstract myMethod() {}
}
```

instead it should not provide an implementation

**Comment by dsherret** [comment]
Ah yes thanks! This was actually fixed by @cancerberoSgx in this PR https://github.com/dsherret/ts-simple-ast/pull/346/files#diff-9428f443549f69ecf41f4d9aeaa833daR31

@cancerberoSgx would you be willing to submit your fix to that as a separate PR? Otherwise I will fix this soon as I can.

**Comment by dsherret** [comment]
Ok, this was too easy of a bug fix so I just fixed it now in 12.5.1.
