### ISSUE TITLE
typedoc error: expected ','

### ISSUE THREAD

**Issue by gp187** [dsherret/ts-simple-ast#371]
_throws error when trying to generate documentation using typedoc_
Replicate: 

*Install typedoc*
`npm i typedoc` 

*Run typedoc*
`typedoc --out docs src/`

ERROR:
`Error: /project/super_project/node_modules/ts-simple-ast/dist/main.d.ts(4441)
 ',' expected.`

_Nothing else is special about the project. Even a brand new project same result_

**Comment by dsherret** [comment]
What version of TypeDoc are you using? I bet it’s not using a version of TypeScript that will compile it (need conditional types—ts 2.9 probably is necessary)
