### ISSUE TITLE
ArrayBindingPattern not wrapped

### ISSUE THREAD

**Issue by osyrisrblx** [dsherret/ts-simple-ast#375]
It would be useful to have for identifying destructuring statements/patterns.

**Comment by dsherret** [comment]
@osyrisrblx this will be in version 14. In the meantime, you can [fall back to using the compiler nodes](https://dsherret.github.io/ts-simple-ast/navigation/compiler-nodes), though the experience won't be so nice.

**Comment by dsherret** [comment]
@osyrisrblx this is now released in v14.
