### ISSUE TITLE
Cannot create new nodes

### ISSUE THREAD

**Issue by osyrisrblx** [dsherret/ts-simple-ast#376]
Attempting to create a node gives the error:
```Error: Constructing a node is not supported. Please create a source file from the default export of the package and manipulate the source file from there.```

However, creating dummy nodes (not inserted into the AST) can be useful for passing into functions which operate on node data.

**Comment by dsherret** [comment]
Hey @osyrisrblx, could you provide some example code that shows a use case of how this would be useful? Thanks!

**Comment by osyrisrblx** [comment]
Might be better to explain my use case:

I'm working on a TypeScript -> Lua transpiler project.
Occasionally, I want to create a dummy node to pass into other functions. For example, I have the function "transpileConstructor" which takes a ConstructorDeclaration as an argument. However, some classes do not have constructors. For this case, it would be useful to pass in a blank constructor with a single statement of "super();"

**Comment by cancerberoSgx** [comment]
@osyrisrblx just an idea, what about using structures instead of nodes? , i.e.   `aClass.addConstructor({bodyText: 'super()'})`
