### ISSUE TITLE
Special not-really-a-method name "constructor"

### ISSUE THREAD

**Issue by lazarljubenovic** [dsherret/ts-simple-ast#391]
It's not really a bug (sorry for deviating from the template)... It's more of a conversation starter about thoughts on this.

Basically, when you do

```ts
const methodDeclaration = classDeclaration.getMethod('constructor')
```

it returns `undefined`. Which makes sense, because _technically_ (from AST POV) there's no method named `constructor`. I'm wondering, however, if people expect this to return the constructor, since you cannot have a method named `constructor`, and for all other purposes constructor behaves like a method. I'd certainly like this behavior, but I'm thinking if there are any footguns and if it fits the mental model of "easyness" that this library is supposed to offer.

Thoughts?

**Comment by dsherret** [comment]
Does it return the method declaration in this scenario? I don't think I've tested for this:

```ts
class MyClass {
    "constructor"() {
    }
}
```

The other issue I see is that `.getMethod(...)` returns [`MethodDeclaration`s](https://github.com/dsherret/ts-simple-ast/blob/ce85b5b38660535282ff1236338c5462802d4fac/lib/ts-simple-ast.d.ts#L3436), while `getConstructors()` returns [`ConstructorDeclaration`s](https://github.com/dsherret/ts-simple-ast/blob/ce85b5b38660535282ff1236338c5462802d4fac/lib/ts-simple-ast.d.ts#L3223).

**Comment by lazarljubenovic** [comment]
I had no idea you can define method names as strings :open_mouth: And yeah, the different type's somehow flown over me. Thanks for the response!

**Comment by dsherret** [comment]
@lazarljubenovic no problem! It's good to explore these ideas.

Yeah, I've found out some things about the language I never knew was possible because of looking at the ast. I've never seen anyone define a method name with a string, but the support is there.
