### ISSUE TITLE
Make the documentation page sections linkable

### ISSUE THREAD

**Issue by dsherret** [dsherret/ts-simple-ast#395]
Right now it's not possible to link to a specific part of the page.

**Comment by Gerrit0** [comment]
I might be missing something, but this is already done, it just isn't immediately obvious as links aren't presented to the user. Example: https://dsherret.github.io/ts-simple-ast/details/classes#base-class

**Comment by dsherret** [comment]
Oh cool. I didn't know that! I wonder if there's a way to make it automatically show those links on the page.

**Comment by dsherret** [comment]
@Gerrit0 great idea! Would you be willing to do a PR? If not, I'll do this sometime later. Probably keep the styling/content looking the same (so add css for no link styling on the headers) and just nest the text within the header tags to be within an anchor element.
