### ISSUE TITLE
Type.getProperties() throws TypeError

### ISSUE THREAD

**Issue by rhys-vdw** [dsherret/ts-simple-ast#397]
**Describe the bug**
Version: 14.1.0

`Type.getProperties()` throws the following error:

```
/Users/rhys/Projects/ts-simple-ast-test/node_modules/ts-simple-ast/dist/compiler/common/Symbol.js:94
        return this.compilerSymbol.declarations.map(function (d) { return _this.context.compilerFactory.getNodeFromCompilerNode(d, _this.context.compilerFactory.getSourceFileForNode(d)); });
                                                ^
TypeError: Cannot read property 'map' of undefined
    at Symbol.getDeclarations (/Users/rhys/Projects/ts-simple-ast-test/node_modules/ts-simple-ast/dist/compiler/common/Symbol.js:94:49)
    at new Symbol (/Users/rhys/Projects/ts-simple-ast-test/node_modules/ts-simple-ast/dist/compiler/common/Symbol.js:18:14)
    at /Users/rhys/Projects/ts-simple-ast-test/node_modules/ts-simple-ast/dist/factories/CompilerFactory.js:388:74
    at WeakCache.getOrCreate (/Users/rhys/Projects/ts-simple-ast-test/node_modules/ts-simple-ast/dist/utils/collections/WeakCache.js:14:20)
    at CompilerFactory.getSymbol (/Users/rhys/Projects/ts-simple-ast-test/node_modules/ts-simple-ast/dist/factories/CompilerFactory.js:388:33)
    at /Users/rhys/Projects/ts-simple-ast-test/node_modules/ts-simple-ast/dist/compiler/type/Type.js:130:106
    at Array.map (<anonymous>)
    at Type.getProperties (/Users/rhys/Projects/ts-simple-ast-test/node_modules/ts-simple-ast/dist/compiler/type/Type.js:130:50)
    at Object.<anonymous> (/Users/rhys/Projects/ts-simple-ast-test/pick.ts:53:6)
    at Module._compile (module.js:641:30)
```

**To Reproduce**

I've created [a repo that can reproduce the error](https://github.com/rhys-vdw/ts-simple-ast-test/blob/master/pick.ts) with full code to reproduce issue.

Run `yarn install && yarn run pick`.

Strangely it only fails if I set the config file which I copied from my other project.

Essence of the issue:

```ts
const sourceFile = project.createSourceFile(
    "src/index.ts", `
    interface Foo {
        a: number,
        b: number,
    }
    export type Picked = Pick<Foo, "a">
`);

const type = sourceFile.getTypeAliases()[0].getType();

type.getProperties() // <-- THIS LINE THROWS
```

**Expected behavior**

Return an array of properties.

**Comment by dsherret** [comment]
Thanks a lot for the detailed instructions. I'll have this fixed when I get home from work. Looks like a case of the compiler api saying something will not be undefined, but it actually may be undefined.

Note to self: Need to also ensure these eagerly retrieved nodes from a symbol are memoized.

**Comment by rhys-vdw** [comment]
FYI when I use the config supplied by JS the `type.getText()` is `any`, when I use my config file it is `Pick<Foo, "a">` and the error occurs.

**Comment by dsherret** [comment]
Fixed in 14.1.1 (just released).

The reason it's `any` when using the virtual file system is because the `lib.d.ts` files need to be loaded in manually to the virtual file system. Read here: https://dsherret.github.io/ts-simple-ast/setup/file-system#virtual-file-system

**Comment by rhys-vdw** [comment]
> The reason it's any when using the virtual file system...

Ah, thanks!

So, looking at [your change](https://github.com/dsherret/ts-simple-ast/commit/80787725318c88b9f83ef57b3ac1ee46f011af00#diff-0c07e6e27ea821fe6baab27fdd642bb2R109). Just out of interest, was this an upstream error?

How would one actually handle the properties of `Pick<Foo, "a">`? I'd like to treat it as if it were exactly this code:

```tsx
export type = {  a: number }
```

**Comment by dsherret** [comment]
Yeah it was because that property (`this.compilerSymbol.declarations`) was nullable when the compiler api's definitions say it won't be. I'm too lazy to create a simple reproducible example and report it to them at the moment though (it will probably be fixed sometime in the future anyway because they've been doing some analysis on where they do suspicious non-null assertions).

What do you mean by handling the properties of that? For that, I believe you're on the right track and `type.getProperties()` should return that single `a` property as is happening in this [test](https://github.com/dsherret/ts-simple-ast/blob/80787725318c88b9f83ef57b3ac1ee46f011af00/src/tests/issues/397tests.ts).

**Comment by rhys-vdw** [comment]
> I believe you're on the right track...

Oh, yeah. Awesome. It does do what I want. Misinterpreted the change. Think I'm close to finishing my lib now.
