### ISSUE TITLE
getExportedDeclarations() throws exception if file is empty

### ISSUE THREAD

**Issue by ihorskyi** [dsherret/ts-simple-ast#410]
Version: 14.2.1

Error is:
```
.../node_modules/ts-simple-ast/dist/errors/BaseError.js:7

var _this = _super.call(this, message) || this;
                           ^
Error: Could not find the node's symbol.
```

**To Reproduce**
just call `typingsFile.getExportedDeclarations()` on empty file

**Expected behavior**
return empty array

**Comment by dsherret** [comment]
Thanks for reporting this @ihorskyi! This is now fixed and available in 14.4.1.

By the way, that `.getExportedDeclarations()` is one of my favourite methods. Let me know if you run into any more problems with it.
