### ISSUE TITLE
memory leak: getVariableStatements & getExportedDeclarations 

### ISSUE THREAD

**Issue by gp187** [dsherret/ts-simple-ast#432]
**Describe the bug**
Version: 15.1.0
Node: 10.9.0

**To Reproduce**

Loop `.ts` 10 files from a directory, read each one of them and run `getExportedDeclarations` on the `sourceFile`

**Expected behavior**

It returns correctly the resulting classes and `Nodes` but it takes so much RAM it often crashes node.

For looping 10 files I had to add `--max-old-space-size=8192` to make it work. And it takes ~50 seconds

**Comment by dsherret** [comment]
@gp187 I'm not sure if this is a memory leak. Perhaps it is just using a lot of memory?

Here's an example script that I believe should demonstrate a memory leak, but I'm not seeing one. All the numbers are holding fairly stable:

```ts
const project = setupProject();
const files = project.getDirectory("src").getDirectories().map(d => d.getSourceFile("index.ts")!).filter(s => s != null);
const dummySourceFile = project.createSourceFile("test.ts", "");

for (let i = 0; i < 10_000; i++) {
    for (const file of files)
        file.getExportedDeclarations();
    forceTypeCheckerRecreation();
    global.gc(); // garbage collection
    console.log(`Memory: ${memoryUsage.heapUsed} | ${memoryUsage.heapTota} | ${memoryUsage.rss}`);
}

function forceTypeCheckerRecreation() {
    // manipulations will cause the internal compiler API type checker to be recreated
    dummySourceFile.addStatements("test;");
}
```

Honestly, I'm not that experienced running memory profiles in node.js/javascript (I am only used to doing it with c# and there are some pretty good tools there that show me everything going on), so I may be doing something wrong or not looking in the right place.

**Comment by dsherret** [comment]
Closing. Please reopen if I'm mistaken and this actually is a memory leak.
