### ISSUE TITLE
findReferencesAsNodes undefined entry

### ISSUE THREAD

**Issue by maximelkin** [dsherret/ts-simple-ast#437]
**Describe the bug**
Version: latest

findReferencesAsNodes for property which is used via ['prop'] syntax returns undefined for this place
**To Reproduce**

const f: {a: string} = {a: '23'};

f['a'];

**Expected behavior**

Not undefined

**Comment by dsherret** [comment]
Thanks for reporting this! Bug on my side. I'll fix it this weekend.

**Comment by dsherret** [comment]
Will be fixed in v16.
