### ISSUE TITLE
Do not publish empty files

### ISSUE THREAD

**Issue by dsherret** [dsherret/ts-simple-ast#444]
Files that only have type information in them seem to be placed in the `dist` folder and published. They contain the following text:

```ts
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
```

I wish TypeScript wouldn't emit these files in the first place though.

**Comment by maximelkin** [comment]
Importing empty file !== importing no file, because second will throw
If someone wants to make stub file for dynamic import - this logic can break his code
For example
```ts
Files:
logic1.ts
logic2.ts
default.ts // empty
Usage:
import(pathToLogic + logicName)
```

**Comment by dsherret** [comment]
@maximelkin not sure what you mean. This is regarding some published js files by this library. For example, [this file](https://github.com/dsherret/ts-simple-ast/blob/176825d03a866146231c5d4b1c589c9503a6e05f/src/structures/function/FunctionDeclarationStructure.ts) published looks has the output above. From my understanding, it's needless to publish them as part of the library.

**Comment by maximelkin** [comment]
Oh, I misunderstood your issue, sorry

**Comment by dsherret** [comment]
@maximelkin that's ok! I wasn't too clear in the description.
