### ISSUE TITLE
getAmbientModule does not work on no quote declare module

### ISSUE THREAD

**Issue by TigerWest** [dsherret/ts-simple-ast#476]
**Describe the bug**
Version: 17.1.1

getAmbientModule does not work at no quote declare module

**To Reproduce**
```ts
const project = new Project();
const sourceFile = project.createSourceFile("test.ts", `declare module 'jquery' {}`);
const jquerySym = project.getAmbientModule(`jquery`);
console.log(jquerySym); // this is work

// but if i remove quote at module ...
 project.createSourceFile("test.ts", `declare module jquery {}`);
const jquerySym = project.getAmbientModule(`jquery`);
console.log(jquerySym); // this is undefined

// 
```

**Expected behavior**

getAmbientModule should be worked on no quote module

**Comment by dsherret** [comment]
Hey @TigerWest, this is working as intended. That method is filtering the results of `ts.TypeChecker`'s `.getAmbientModules()` method ([see here](https://github.com/Microsoft/TypeScript/blob/14c328e706f37446306484cb5770fa2d06c6875c/lib/typescript.d.ts#L1947)).

See here for terminology: https://www.typescriptlang.org/docs/handbook/namespaces-and-modules.html ...basically, this is equivalent to a namespace: `declare module jquery {}` ...and this is a module: `declare module "jquery" {}`

If you want the namespace declaration (`declare module jquery {}`) then you will need to call `const namespaceDec = sourceFile.getNamespace("jquery");` (or `.getNamespaceOrThrow`) on the source file.
