### ISSUE TITLE
organizeImports throws 

### ISSUE THREAD

**Issue by cancerberoSgx** [dsherret/ts-simple-ast#484]
The following code will throw an error when trying to execute sourceFile.organizeImports() after sourceFile.addImportDeclaration(). 

In my case is important that organizeImports() not to throw because I'm using it for refactor tools that must work on any arbitrary project, this is a simple one with two files: 

```
import {Project} from 'ts-simple-ast'

const project = new Project()

const lionFile = project.createSourceFile('src/animal/lion/Lion.ts', `
import {Food} from '../../food/Food' // <<<----- if this import is changed to point to something else then error dones't happen
/* import {Animal} from '../Animal'  <<<<<---- if I remove this line, even if it's commented as it is the error doesn't happen */
export class Lion {
  eat(meat: Food){}
}
`)

const foodFile = project.createSourceFile('src/food/Food.ts', `
export class Food {
  energy: number
  canEatBy: number[]
}
` )

const Food = foodFile.getClass('Food')

console.log('ERRORS: ' + project.getPreEmitDiagnostics().map(e => e.getMessageText() + ' - ' + e.getSourceFile().getFilePath()).join('\n'))

Food.findReferences(); // If i comment this call the error doesn't happen 

lionFile.addImportDeclaration({ // it doesn't matter if the import points to something that exists or not
  moduleSpecifier: '../foo',
  namedImports: [{ name: 'Foo'}]
})
lionFile.organizeImports()
console.log(lionFile.getText());
```

the error is on SourceFile.manipulation() : 

```
/home/sg/git/typescript-plugins-of-mine/typescript-plugin-proactive-code-fixes/node_modules/ts-simple-ast/dist/errors/classes/BaseError.js:8
        var _this = _super.call(this, message) || this;
                           ^
Error: Cannot read property 'kind' of undefined
-- Details --
Path: /home/sg/git/typescript-plugins-of-mine/typescript-plugin-proactive-code-fixes/src/animal/lion/Lion.ts
Text: "\nimport { Food } from '../../food/Food';\n\n // <<<----- if this import is changed to point to something else then error dones't happen\n/* import {Animal} from '../Animal'  <<<<<---- if I remove this line, even if it's commented as it is the error doesn't happen */\nexport class Lion {\n  eat(meat: Food){}\n}\n"
    at InvalidOperationError.BaseError [as constructor] (/home/sg/git/typescript-plugins-of-mine/typescript-plugin-proactive-code-fixes/node_modules/ts-simple-ast/dist/errors/classes/BaseError.js:8:28)
    at new InvalidOperationError (/home/sg/git/typescript-plugins-of-mine/typescript-plugin-proactive-code-fixes/node_modules/ts-simple-ast/dist/errors/classes/InvalidOperationError.js:9:23)
    at Object.doManipulation (/home/sg/git/typescript-plugins-of-mine/typescript-plugin-proactive-code-fixes/node_modules/ts-simple-ast/dist/manipulation/manipulations/doManipulation.js:12:15)
    at Object.replaceNodeText (/home/sg/git/typescript-plugins-of-mine/typescript-plugin-proactive-code-fixes/node_modules/ts-simple-ast/dist/manipulation/manipulations/replaction.js:10:22)
    at SourceFile.applyTextChanges (/home/sg/git/typescript-plugins-of-mine/typescript-plugin-proactive-code-fixes/node_modules/ts-simple-ast/dist/compiler/ast/module/SourceFile.js:631:24)
    at SourceFile.organizeImports (/home/sg/git/typescript-plugins-of-mine/typescript-plugin-proactive-code-fixes/node_modules/ts-simple-ast/dist/compiler/ast/module/SourceFile.js:620:14)
    at Object.<anonymous> (/home/sg/git/typescript-plugins-of-mine/typescript-plugin-proactive-code-fixes/assets/tests/organizeImportsTest.ts:30:10)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Module.m._compile (/home/sg/.npm-prefix/lib/node_modules/ts-node/src/index.ts:439:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:699:10)
```

This error is an injection, since in older library version "12.5.4" like [my playground's is not reproducible](https://typescript-api-playground.glitch.me/#__editor_code__=import%20Project%20from%20'ts-simple-ast'%0A%0Aexport%20function%20main(code%3A%20string%2C%20log%3A%20(msg%3A%20string)%20%3D%3E%20void)%20%7B%0A%20%20const%20project%20%3D%20new%20Project()%0A%0A%20%20const%20lionFile%20%3D%20project.createSourceFile('src%2Fanimal%2Flion%2FLion.ts'%2C%20%60%0Aimport%20%7BFood%7D%20from%20'..%2F..%2Ffood%2FFood'%20%2F%2F%20%3C%3C%3C-----%20if%20this%20import%20is%20changed%20to%20point%20to%20something%20else%20then%20error%20dones't%20happen%0A%2F*%20import%20%7BAnimal%7D%20from%20'..%2FAnimal'%20%20%3C%3C%3C%3C%3C----%20if%20I%20remove%20this%20line%2C%20even%20if%20it's%20commented%20as%20it%20is%20the%20error%20doesn't%20happen%20*%2F%0Aexport%20class%20Lion%20%7B%0Aeat(meat%3A%20Food)%7B%7D%0A%7D%0A%60)%0A%0A%20%20const%20foodFile%20%3D%20project.createSourceFile('src%2Ffood%2FFood.ts'%2C%20%60%0Aexport%20class%20Food%20%7B%0Aenergy%3A%20number%0AcanEatBy%3A%20number%5B%5D%0A%7D%0A%60%20)%0A%0A%20%20const%20Food%20%3D%20foodFile.getClass('Food')%0A%0A%20%20log('ERRORS%3A%20'%20%2B%20project.getPreEmitDiagnostics().map(e%20%3D%3E%20e.getMessageText()%20%2B%20'%20-%20'%20%2B%20e.getSourceFile().getFilePath()).join('%5Cn'))%0A%0A%20%20Food.findReferences()%3B%20%2F%2F%20If%20i%20comment%20this%20call%20the%20error%20doesn't%20happen%20%0A%0A%20%20lionFile.addImportDeclaration(%7B%20%2F%2F%20it%20doesn't%20matter%20if%20the%20import%20points%20to%20something%20that%20exists%20or%20not%0A%20%20%20%20moduleSpecifier%3A%20'..%2Ffoo'%2C%0A%20%20%20%20namedImports%3A%20%5B%7B%20name%3A%20'Foo'%20%7D%5D%0A%20%20%7D)%0A%20%20log(lionFile.getText())%3B%0A%20%20lionFile.organizeImports()%0A%20%20log(lionFile.getText())%3B%0A%7D%0A%0A__editor_input__=class%20Animal%20implements%20Living%20%7B%0A%20%20energy%3A%20number%0A%20%20constructor(public%20name%3A%20string)%20%7B%20%7D%0A%20%20move(distanceInMeters%3A%20number%20%3D%200)%20%7B%0A%20%20%20%20console.log(%20%60%24%7Bthis.name%7D%20moved%20%24%7BdistanceInMeters%7Dm.%60)%0A%20%20%7D%0A%7D%0Ainterface%20Living%7B%0A%20%20energy%3A%20number%0A%7D%0Aclass%20Snake%20extends%20Animal%20%7B%0A%20%20constructor(name%3A%20string)%20%7B%20super(name)%3B%20%7D%0A%20%20move(distanceInMeters%20%3D%205)%20%7B%0A%20%20%20%20%20%20console.log(%22Slithering...%22)%3B%0A%20%20%20%20%20%20super.move(distanceInMeters)%3B%0A%20%20%7D%0A%7D%0Aconst%20words%20%3D%20%5B%5D%0Afunction%20randomIdentifier(what%3A%20'variable'%20%7C%20'class'%20%3D%20'variable'%2C%20amountOfWords%3A%20number%20%3D%202)%3A%20string%20%7B%0A%20%20let%20w%20%3D%20words%5Brandom(0%2C%20words.length%20-%201)%5D%0A%20%20return%20what%20%3D%3D%3D%20'class'%20%3F%20camel(w)%20%3A%20w%0A%7D%0Afunction%20random(a%2C%20b)%20%7B%0A%20%20return%20Math.floor(Math.random()%20*%20b)%20%2B%20a%0A%7D%0Afunction%20camel(w%3A%20string)%20%7B%0A%20%20return%20w.substring(0%2C%201).toUpperCase()%20%2B%20w.substring(1%2C%20w.length)%0A%7D)

**Comment by dsherret** [comment]
Thanks for reporting @cancerberoSgx! Will be fixed in the next release (which I will do probably sometime today).

**Comment by cancerberoSgx** [comment]
Thanks, just in case, this is my workaround: 

```ts
let tmpSourceFile: SourceFile
function safeOrganizeImports(f: SourceFile, project: Project) {
  if(!tmpSourceFile){
    tmpSourceFile= project.createSourceFile('tmp.ts', '')
  }
  tmpSourceFile.replaceWithText(f.getText())
  tmpSourceFile.organizeImports()
  f.replaceWithText(tmpSourceFile.getText())
}
```
