### ISSUE TITLE
Project.applyFileTextChanges()

### ISSUE THREAD

**Issue by cancerberoSgx** [dsherret/ts-simple-ast#489]
There is SourceFile.applyTextChanges that accepts TextChanges[].

Would be great to have a project.applyFileTextChanges() that accept a FileTextChanges[] .   This objects contains information about which files should be modified or created and are returned by LanguageService. This way I don't have to apply the changes manually to each file.

Alternatively, if the resulting file text is empty, project.applyChanges could automatically  call project.removeSourceFile(). (This could be configurable.)

Can I ? :)

Thanks

**Comment by dsherret** [comment]
@cancerberoSgx sounds good! Based on the interface of `FileTextChanges` this probably shouldn't ever remove a file though. People can manually go through the files from the `FileTextChanges` objects and decide themselves if they want to remove them.

**Comment by cancerberoSgx** [comment]
Nice! I already have it implemented and tested in a separate project. I will integrate those changes in ts-simple-ast after https://github.com/dsherret/ts-simple-ast/pull/488 is integrated since I need a couple of features from there and both kind of intersect. Thanks

**Comment by dsherret** [comment]
Implemented by @cancerberoSgx in #491.
