### ISSUE TITLE
Method for adding source files to project based on current files

### ISSUE THREAD

**Issue by dsherret** [dsherret/ts-simple-ast#492]
For example, given the following files:

```ts
// src/main.ts
export * from "./classes";

// src/classes.ts
export class Test {}
```

And following tsconfig.json:

```ts
{
    "files": ["src/main.ts"],
    "compilerOptions" {
        // etc...
    }
}
```

The following setup...

```ts
const project = new Project({ tsConfigFilePath: "tsconfig.json" });
```

...will cause only *main.ts* to be added to the project.

It would be nice to have a method that adds all the referenced files to the project. I'm not sure what this would be called, but it should be in an `addX` format to be consistent with the other methods on `Project`.

**Comment by dsherret** [comment]
I'm beginning to think this should be done always and instead add a "skip" property to the project options to skip doing this.

**Comment by Gerrit0** [comment]
I would expect that all referenced files be added to the project by default, especially since that is what happens when using `ts.createProgram` directly.

"skip" is a bit ambiguous, maybe "resolveFileDependencies"?

**Comment by dsherret** [comment]
Yeah, it wouldn't be "skip," but I do like your idea of `resolveFileDependencies`. I think people might think setting that to `false` would disable it completely... so working off what you said maybe `skipDependencyResolution`?

For a method name, I'm thinking either `addDependencySourceFiles()`, `resolveDependencies()`, `resolveFileDependencies()` or `resolveSourceFileDependencies()`.

**Comment by dsherret** [comment]
This will be in v19. I'm making this a breaking change because more source files may appear in the project after constructing it.
