### ISSUE TITLE
Unable to update a value of property

### ISSUE THREAD

**Issue by kyyash** [dsherret/ts-simple-ast#503]
**Describe the bug**
protected configVariable: ITestConfiguration = {
    "params": {
      "fgroup1": {
        "name": "group1",
        "type": "string",
        "value": ""
      }
    },
    "events": {
      "subscribed": [],
      "published": []
    }
  };

Version: 18.0.0

**To Reproduce**

```ts
import { Project, ts } from "ts-simple-ast";

console.log(ts.version); // x.x.x <-- provide this

const project = new Project();
const sourceFile = project.createSourceFile("test.ts", ``);

// reproduce the problem here
```
const property = classDeclaration.getPropertyOrThrow(propertyName);
					property.setInitializer(propertyValue);
**Expected behavior**
I should be rest the value of this property to any string I want.

**Comment by dsherret** [comment]
Hi @kyyash,

I'm unable to reproduce the problem you're describing. If you'd like me to resolve the issue you're having, then please take the time to fill out the bug report template properly with a reproducible example.

Here was my attempt at reproducing what you mentioned, but I'm not able to reproduce:

```ts
import { Project, ts } from "ts-simple-ast";

console.log(ts.version); // 3.1.6

const project = new Project();
const sourceFile = project.createSourceFile("test.ts", `class Test {
    protected configVariable: ITestConfiguration = {
        "params": {
            "fgroup1": {
                "name": "group1",
                "type": "string",
                "value": ""
            }
        },
        "events": {
            "subscribed": [],
            "published": []
        }
    };
}`);

const classDeclaration = sourceFile.getClassOrThrow("Test");
const property = classDeclaration.getPropertyOrThrow("configVariable");
property.setInitializer("value"); // works

console.log(sourceFile.getFullText());
```

Outputs the following as expected:

```ts
class Test {
    protected configVariable: ITestConfiguration = value;
}
```

**Comment by kyyash** [comment]
We were able to achieve using setInitializer
