### ISSUE TITLE
tsconfig.json expected in js projects

### ISSUE THREAD

**Issue by marikaner** [dsherret/ts-simple-ast#516]
I was using `ts-simple-ast` with js and it took me a long time to figure out why I got the following error: `throw this.getFileNotFoundErrorIfNecessary(err, filePath);` as it cannot find the `tsconfig.json`. But I don't need it in my js project...

Creating an empty config with `touch tsconfig.json` solved the issue. When I find the time I will post a more exact desciption in the future, but I guess the main problem is clear.

**Comment by dsherret** [comment]
@marikaner could you post some reproduction code? You shouldn't need to specify a tsconfig and it should only be loaded when specified.

**Comment by marikaner** [comment]
@dsherret Sorry for the sloppyness, I found the error in our own code.

Just FYI: we basically had a code generator (written in ts) using `ts-simple-ast`, that was relying on a `./tsconfig.json` in the project (which I missed).
When packing it and sharing it with other colleagues, they got the mentioned error.
The fix was simple:
```ts
const project = new Project({
    tsConfigFilePath: path.resolve(__dirname, './tsconfig.json')
});
```

Thank you for your support, though!
