### ISSUE TITLE
feature request : add a " add all missing import " method in LanguageService

### ISSUE THREAD

**Issue by WanderWang** [dsherret/ts-simple-ast#518]
**Is your feature request related to a problem? Please describe.**

I want to convert a big size  typescript library from " global-variable-based " to ES6 modules

Here is a example :  

from:

```typescript

//a.ts
class A {
    public b:B;
}

//b.ts
class B {
}
```

to :  
```typescript
// a.ts
import { B } from ".b";
class A {
    public b:B;
}

//b.ts

export class B {
}
```

First step , I have added a  export keyword with all classes  , It works now .

Second step , I need to " add all missing import " ( such as manual in vscode ) programmicly , but failed .

**Describe the solution you'd like**

Please add a " add all missing import " method on LanguageService ,such as ``` languageService.orginazeImports ```

Thanks you

**Comment by dsherret** [comment]
This will be in version 21. Hopefully will release later today.

**Comment by dsherret** [comment]
By the way, this is done using `#getCombinedCodeFix()` on the language service, but is available as a simple method call on the source file like so: `sourceFile.fixMissingImports()` (similar to `sourceFile.organizeImports()`)

**Comment by WanderWang** [comment]
great jobs ! could you publish a tag ( such as  ts-simple-ast@next ) in npm before you release  version21 ?

**Comment by WanderWang** [comment]
Thanks for you hard working in ts-simple-ast again ! . This feature  saved me tens of hours 👍
