### ISSUE TITLE
feature request : support rename filename

### ISSUE THREAD

**Issue by WanderWang** [dsherret/ts-simple-ast#526]
**Is your feature request related to a problem? Please describe.**

I want to rename my sourcefile's filename via languageService

**Describe the solution you'd like**

here is source file

```
// a.ts
export class A {
}

//b.ts
import { A } from './a'
const a = new A();
```

when i execute this script
```
languageService.renameFileName("a.ts","c.ts“);
```

it should be

```
// c.ts
export class A {
}

//b.ts
import { A } from './c'
const a = new A();
```

**Describe alternatives you've considered**

**Comment by dsherret** [comment]
Hey @WanderWang, does `sourceFile.move(“c.ts”)` already do what you want? It should change module specifiers automatically.

**Comment by WanderWang** [comment]
it works ! thanks u david !

by the way , could you improve https://dsherret.github.io/ts-simple-ast/manipulation/renaming with this method ???

**Comment by dsherret** [comment]
Good idea! I’ll do that soon.
