### ISSUE TITLE
QU: How do I insert text between the brackets of a function?

### ISSUE THREAD

**Issue by chrisgervang** [dsherret/ts-simple-ast#62]
Once I've navigated to the function like the example below, I'd like to fill it with a string of code. 
```
render() {
  // insert here
}
```
Is this possible?

**Comment by dsherret** [comment]
@chrisgervang, I was going to implement this after removing nodes, but since you asked for it, it's now implemented in 0.55.0. Let me know if you run into any issues.

Use the `setBodyText` method:

```typescript
methodDeclaration.setBodyText("// insert here");
```

Or:

```typescript
sourceFile.addFunction({
    name: "myFunction",
    bodyText: "// insert here"
});
```

**Comment by chrisgervang** [comment]
Thank you so much! Great job with this library. It's amazing work!

**Comment by dsherret** [comment]
Thanks for the compliment. I'm glad it's useful! :)
