### ISSUE TITLE
Performance: Faster replace tree

### ISSUE THREAD

**Issue by dsherret** [dsherret/ts-simple-ast#70]
Right now, whenever a manipulation happens, the entire tree is replaced.

It would be better to only bother replacing nodes that are currently in the node cache.

**Comment by dsherret** [comment]
I'm thinking this would create too much complexity for not much benefit. I'm going to close this for now as "won't fix".

**Comment by dsherret** [comment]
The performance is actually becoming somewhat of an annoyance for me. It takes maybe ~5 mins to do a release of this library because the code manipulation is slow and I'm manipulating a large file (Node.ts).

I thought of how to solve this without too much complexity:

1. When inserting into the cache, make sure the parent already exists in the cache... if not, keep looping up the tree until a wrapped parent is reached.
2. When replacing the tree, only bother with children that have been wrapped previously.

So point #1 is what makes doing this very easy.

Additionally, it might be nice to add a `.forget()` method (or `.destroy()` method) to every node that will call `.dispose()` internally. That would allow people who need it to get maximum performance on large files. It's easy to do so might as well provide that option.

**Comment by dsherret** [comment]
Implemented in 0.97.0 along with `.forget()`. I'm glad I ended up implementing this... it wasn't too bad and my releases are back to being pretty fast now. Some data on how fast my release script takes to run on my computer now:

```typescript
==
setSyntaxKindOverloads code generation times
==
Original: 9min 38s
This change with forgetting nodes: 2min 21s
Overall increase: 346% faster
```

**Comment by ChuckJonas** [comment]
@dsherret I wrote a code generator using this library (to generate interfaces and classes for an external database mapping).  I've noticed that as the size of the code I'm generating grows, it seems to get exponentially slower.  In one project I'm using, my generated asset is up to about 5k lines (writing about 15 classes to a single file).

I'm sure that my approach has something to do with it.  For simplicity, I'm writing everything to a single file.  

My code looks something like this: 

```
let source = ast.addSourceFileFromStructure(config.outPath, {});
for(schema in retrieveSchemas()){
   let props = generatePropertyDef(schema)
   sourceFile.addInterface({properties: props, ...})
   let class = sourceFile.addClass({properties: props, ...})
   class.addConstructor()
   ...
}
source.save();
```

I've done some very simple profiling and it seems the vast majority of the time in spent in the `addInterface` & `addClass` methods.  The more properties that are passed it, the slower it goes.  

Do you have any suggestion to how I might be able to speed this code up?  I'm sure I'm not using this library in the most efficient manor.

**Comment by dsherret** [comment]
I'll reply back tomorrow (just going to sleep now). I added a bit of information here: https://dsherret.github.io/ts-simple-ast/manipulation/performance

In summary: the more nodes that become wrapped, the more nodes that need to be tracked and replaced between manipulations.

You should be able to get a decent performance boost by using those "forget blocks," or by manually forgetting nodes you don't need anymore. There's still lots of performance improvements that can be made internally in the library that I'll be working on over the next while though.

**Comment by ChuckJonas** [comment]
Actually, it doesn't seem like `myClass` in the example above has a `forget()` method?
