### ISSUE TITLE
Renaming a class with comments

### ISSUE THREAD

**Issue by redlock** [dsherret/ts-simple-ast#76]
Hi, I was trying to rename a class using the example given. However, if there is a comment block above the class the new text is inserted in the wrong position. Removing the comment block fixes the problem but it isn't really a viable solution for processing large projects.

Thanks for a great job with the library.

**Comment by dsherret** [comment]
Hey, thanks for reporting this and for the compliment about the library. This is fixed in 0.61.2. Let me know if the issue still persists or if you run into any other issues.

**Comment by redlock** [comment]
Thanks for the quick fix.
