### ISSUE TITLE
Add recommendations for AST viewers in documentation

### ISSUE THREAD

**Issue by dsherret** [dsherret/ts-simple-ast#79]
Would be good to recommend some AST viewers to people. It's much easier to use this library in conjunction with an AST viewer when working on harder problems.

**Comment by dsherret** [comment]
@gdeividas thanks for that! I had looked at it before, but didn't realize it supported TypeScript... it's in the second menu. I'll probably recommend that one because it's easy to access. I guess the one downside is that it only navigates the tree via properties. That's not so bad though.

**Comment by gdeividas** [comment]
Yeah for me who is just starting to code/learn the AST on the go was quite helpful. 
Anyways good job on the library - please continue improving it.

**Comment by dsherret** [comment]
Implemented. I ended up only recommending the one available in atom-typescript. I also evaluated "TypeScript AST Explorer" in vs code and the "AST Explorer" web site.

I think in order to add an AST viewer to this page, it must have the following:

1. Show parent/child relationship between nodes.
2. Have ability to show all nodes (ex. `SyntaxList` nodes must not be excluded)

In the future, I'll probably add my own ast viewer to the documentation that has everything I'd like.

**Comment by dsherret** [comment]
I've created a basic web-based AST viewer that shows the parent/child relationship between the nodes, shows the SyntaxList nodes, along with all the other small features many AST viewers leave out: https://dsherret.github.io/ts-ast-viewer/
