### ISSUE TITLE
ourDir fails to create directory structrure.

### ISSUE THREAD

**Issue by brad-jones** [dsherret/ts-simple-ast#95]
When specifying a custom "outDir", attempting to emit source file(s) will result in failure if the directory containing the final transpiled source file does not exist.

Simple test case:
```js
const ast = new TsSimpleAst({ compilerOptions: { outDir: __dirname + "/dist" } });
ast.addSourceFileFromText("MyFile.ts", "const num = 1;");
ast.addSourceFileFromText("Foo/MyFile.ts", "const num = 1;");
ast.addSourceFileFromText("Foo/Bar/MyFile.ts", "const num = 1;");
ast.emit();
```

Fails with an `no such file or directory` error.
If you then create the require directory structure the above works fine.

My current work around is to do this just before emitting:
```js
for (let srcFile of ast.getSourceFiles())
{
    shell.mkdir('-p', path.dirname(srcFile.getFilePath().replace(__dirname + '/src', __dirname + '/dist')));
}
```

**Comment by dsherret** [comment]
Thanks for reporting this Brad! This would also occur when calling:

* `sourceFile.save()`
* `sourceFile.saveSync()`
* `ast.saveUnsavedSourceFiles()`
* `ast.saveUnsavedSourceFilesSync()`

Fixed in 0.72.1. Let me know if there are any issues.
