### ISSUE TITLE
Ability to replace text of any Node

### ISSUE THREAD

**Issue by dsherret** [dsherret/ts-simple-ast#98]
Taking a property access expression like this:

```typescript
let myVar = Some.Property.Access;
```

You should be able to replace its text. For example:

```typescript
(varDeclaration.getInitializer() as PropertyAccessExpression).replaceWithText("SomePropertyAccess");
```

Would change the file to:

```typescript
let myVar = SomePropertyAccess;
```

Since this replaces the text of the node, that could make it become something else. Because of that, it should dispose the existing node and `replaceWithText` should return the new node.

Maybe this could go on a `TextReplaceableNode` mixin.

**Comment by dsherret** [comment]
Adding this functionality on any node. I can't see a reason not to do that.

**Comment by dmeagor** [comment]
Looks great.  Does replaceWithText allow renaming from foo.bar.ISomething to fooBar.ISomething?

I'll test this out on Monday.

**Comment by dsherret** [comment]
@dmeagor yup, that will be possible for sure.
